import { EMPTY_OPTION } from "../../../lib/variables";

/**
 * @CategoryName Araç İçi Telefon Tutucu Elektronik > Elektronik Aksesuarlar > Cep Telefonu Aksesuarları > Araç İçi Telefon Tutucu
 * @Category 1056
 * @Field Telefon Tutucu Özellikleri
 * @Optional
 */
export const InCarPhoneHolder_StandProperties = [
  "Akrobat",
  "Hızlı Şarj",
  "Kablosuz Şarj",
  "Mıknatıslı",
  EMPTY_OPTION,
] as const;

/**
 * @CategoryName Araç İçi Telefon Tutucu Elektronik > Elektronik Aksesuarlar > Cep Telefonu Aksesuarları > Araç İçi Telefon Tutucu
 * @Category 1056
 * @Field Garanti Süresi
 */
export const InCarPhoneHolder_GuaranteePeriods = [
  "Belirtilmemiş",
  "1 Yıl",
  "2 Yıl",
  "3 Yıl",
  "4 Yıl",
  "5 Yıl",
  "6 Ay",
] as const;

/**
 * @CategoryName Araç İçi Telefon Tutucu Elektronik > Elektronik Aksesuarlar > Cep Telefonu Aksesuarları > Araç İçi Telefon Tutucu
 * @Category 1056
 * @Field Türü
 * @Optional
 */
export const InCarPhoneHolder_Type = [
  "Dikiz Aynası",
  "Direksiyon",
  "Havalandırma",
  "Torpido Üstü",
  "Vantuzlu",
  EMPTY_OPTION,
] as const;

/**
 * @CategoryName Araç İçi Telefon Tutucu Elektronik > Elektronik Aksesuarlar > Cep Telefonu Aksesuarları > Araç İçi Telefon Tutucu
 * @Category 1056
 * @Field Materyal
 * @Optional
 */
export const InCarPhoneHolder_Material = [
  EMPTY_OPTION,
  "%100 Akrilik",
  "%100 Çam",
  "%100 Keten",
  "%100 Organik Pamuk",
  "%100 Pamuk",
  "%100 Pişmiş Toprak",
  "%100 Viskoz",
  "%1 Akrilik, %96 Pamuk, %2 Polyester, %1 Viskon",
  "%50 Bambu %50 Silikon",
  "%50 Silikon",
  "%60 Keten %40 Pamuk",
  "%70 Ahşap, %5 Keten, %25 Metal",
  "%80 Pamuk %20 Rejene",
  "%98 Pamuk %2 Likra",
  "2 İplik",
  "2 İplik Şardonlu",
  "3 İplik",
  "3 İplik Şardonlu",
  "Aerobin",
  "Ağaç",
  "Ahşap",
  "Akfil",
  "Akrilik",
  "Akrilik - Bambu",
  "Akrilik - Doğal İplik",
  "Akrilik Karışımlı",
  "Akrilik - Pamuk",
  "Akrilik - Polyester",
  "Alçı",
  "Aloevera",
  "Altın",
  "Altın Kaplama",
  "Alüminyum",
  "Asetat",
  "Ateş Kehribar",
  "Baby Face",
  "Bakır",
  "Balıksırtı",
  "Bambu",
  "Bambu + Polyester",
  "Bambu - İpek",
  "Bambu-Pamuk",
  "Basket",
  "Belmando",
  "Beton",
  "Beyaz Altın",
  "Bio Diamond",
  "Bio Granit",
  "Boncuk",
  "Bone China",
  "Boyalı",
  "Boynuz",
  "Brode",
  "Bronz",
  "Bubble Saten",
  "Bürümcük",
  "Cam",
  "Caz",
  "Ceviz Ağacı",
  "Compact",
  "Cotonel",
  "Crinkle",
  "Cupro Karışımlı",
  "Çam",
  "Çelik",
  "Çini",
  "Çinko",
  "Çömlek",
  "Çubuk Malzeme",
  "Dalgıç/Scuba",
  "Damla",
  "Dana Derisi",
  "Dantel",
  "Demir",
  "Denim",
  "Deniz Çimi",
  "Deniz Sazı",
  "Deri",
  "Dobby",
  "Doğal Taş",
  "Dokuma",
  "Dolomite",
  "Double Face",
  "Döküm",
  "Elastan",
  "Elastan-Viskon-Polyester",
  "Elastodiyen",
  "Elyaf",
  "Emaye",
  "Epoksi",
  "EVA",
  "EVA / PVC",
  "Ferforje",
  "Fibre",
  "File",
  "Fine Cream",
  "Finike",
  "Flamlı Pamuk",
  "Flanel",
  "Floş",
  "Gabardin",
  "Galvaniz",
  "Gauze",
  "Gore",
  "Grafit",
  "Granit",
  "Granit Döküm",
  "Granit Kaplama",
  "Gümüş",
  "Gümüş Kaplama",
  "H.M. Grafit",
  "Hakiki Deri",
  "Halat",
  "Hasır",
  "Havlu",
  "Hindistan Cevizi Kabuğu",
  "İnci",
  "İnterlok",
  "İp",
  "İpek",
  "İpek / Kaşmir",
  "İpek Jakar",
  "İpek Krep Saten",
  "İpek Modal",
  "İpek Tivil",
  "İpek Varaklı",
  "İpek Vual",
  "İpek - Yün",
  "İplik",
  "Jakar",
  "Jarse",
  "Jel",
  "Jerry",
  "Jessica",
  "Jüt",
  "Kabuk",
  "Kadife",
  "Kağıt",
  "Kalın Crep",
  "Kanguru Derisi",
  "Kanvas",
  "Kapitone",
  "Kapri",
  "Karbon",
  "Karbon Çelik",
  "Karton",
  "Kaşe",
  "Kaşkorse",
  "Kaşmir",
  "Katelin",
  "Kauçuk",
  "Kayadamla",
  "Kayın",
  "Kaz Tüyü",
  "Keçe",
  "Kehribar Tozu",
  "Kemik",
  "Kereste",
  "Kesik Elyaf",
  "Keten",
  "Keten Görünümlü",
  "Keten Karışımlı",
  "Keten-Viskon",
  "Kıl",
  "Koko",
  "Kontraplak",
  "Koshiba",
  "Köpük",
  "Krep",
  "Kristal Taş",
  "Kroko",
  "Krom",
  "Krom Kaplama",
  "Krom Kaplı Pirinç",
  "Kroşetalı",
  "Kuka",
  "Kumaş",
  "Kültür İncisi",
  "Laboratuvar Pırlantası",
  "Lak Kaplama",
  "Lazer Kesim",
  "Led Işıklı",
  "Likra",
  "Liyosel",
  "Lureks",
  "Lyocell Karışımlı",
  "Mantar",
  "Mantar Derisi",
  "Maroken",
  "MDF",
  "MDF & Suntalam",
  "Medine İpeği",
  "Melamin",
  "Membran",
  "Memory Foam",
  "Mermer",
  "Mermerit",
  "Merserize",
  "Mesh",
  "Metal",
  "Metalik İplik",
  "Micro",
  "Micro-Modal",
  "Micro Saten",
  "Mika",
  "Mikrofiber",
  "Mikro Petek",
  "Mikro Saten",
  "Modal",
  "Modal-Pamuk",
  "Moonlight",
  "Mozaik",
  "Mukavva",
  "Muline",
  "Müslin",
  "Nakışlı / İşlemeli",
  "Nano Cam",
  "Nano Film",
  "Nanometric XT",
  "Naylon",
  "Nefes Alabilen Kumaş",
  "Neopren",
  "Nikel",
  "Nonwoven",
  "Nubuk",
  "Okyanus İncisi",
  "Oltu",
  "Organze",
  "Ottoman",
  "Outlast",
  "Oxford",
  "Örme",
  "Pamuk",
  "Pamuk Akrilik",
  "Pamuk-Akrilik-Polyester",
  "Pamuk - Elastan",
  "Pamuk-Elyaf",
  "Pamuk-İpek",
  "Pamuk Keten",
  "Pamuklu",
  "Pamuklu Havlu",
  "Pamuk - Poliamid",
  "Pamuk - Polietilen",
  "Pamuk Polyester",
  "Pamuk-Polyester-Elastan",
  "Pamuk Saten",
  "Pamuk-Saten",
  "Pamuk Viskon",
  "Pamuk - Viskon",
  "Pamuk Viskon Polyester",
  "Pamuk-Viskon-Polyester",
  "Pamuk - Yün",
  "Paper Clay",
  "Paraşüt",
  "Paslanmaz Çelik",
  "Payetli",
  "Peluş",
  "Penye",
  "Percale",
  "Pike",
  "Pirinç",
  "Plain",
  "Plastik",
  "Platinyum Kaplama",
  "Plywood",
  "Polar",
  "Poliamid",
  "Poliamid Karışımlı",
  "Poliamid Metalik İplik",
  "Polietilen",
  "Polikoton",
  "Polimer Kil",
  "Polipropilen",
  "Polipropilen - Polyester",
  "Poliresin",
  "Poliüretan",
  "Poliviskon",
  "Polyamid",
  "Polyester",
  "Polyester - Elastan",
  "Polyester Karışımlı",
  "Polyester - Viskon",
  "Poly Koton",
  "Poly Saten",
  "Poly Twill",
  "Polyviskon",
  "Poly Viskon",
  "Ponpon Şifon",
  "Ponpon Viskon",
  "Poplin",
  "Porselen",
  "Poylviskon",
  "Protect Kaplama",
  "Protect Tal Plus Kaplama",
  "PU",
  "PVC-Polyester",
  "Queen Crep",
  "Rafya",
  "Ranforce",
  "Rattan",
  "Rayon Karışımlı",
  "Reçine",
  "Rigid",
  "Rodyum",
  "Rose Gold",
  "Rugan",
  "Sac",
  "Saf İpek",
  "Sandy",
  "Saten",
  "Saten / Tafta",
  "Seacell",
  "Sedef",
  "Selanik",
  "Seramik",
  "Seramik Hamuru",
  "Sıkıştırılmış Taş",
  "Sıkma Kehribar",
  "Sıkma Rozu",
  "Silikon",
  "Simli Örme",
  "Sisal",
  "Sisal halat",
  "Spandeks",
  "Stiren Bütadien Stiren",
  "Stoneware",
  "Strafor",
  "Su Geçirmez",
  "Su Kabağı",
  "Suni Deri",
  "Suni Kürk",
  "Suntalam",
  "Süet",
  "Sünger",
  "Süprem",
  "Şardon Akrilik",
  "Şardonlu",
  "Şerpa",
  "Şifon",
  "Şimşir",
  "Şönil",
  "Tafta",
  "Taş",
  "Taşlı",
  "Taş Tozu",
  "Tatlı Su İncisi",
  "Tay Tüyü",
  "Teflon",
  "Tekstil",
  "Tela",
  "Tericotton",
  "Termoform",
  "Terracotta",
  "test",
  "test2",
  "Thermolon",
  "Titanyum",
  "Toprak",
  "TPE",
  "Triko",
  "Tuğla",
  "Tül",
  "Tüvit",
  "Twill",
  "Vinyl",
  "Visco",
  "Viskon",
  "Viskon Akrilik",
  "Viskon Karışımlı",
  "Viskon Polyester",
  "Viskoz Karışımlı",
  "Vual",
  "Waffle",
  "Wellsoft",
  "Yonga Levha",
  "Yoryo Şifon",
  "Yün",
  "Yün - Akrilik - Polyester",
  "Yünlü",
  "Zamak",
  "Zamak Kaplama",
  "Zar kehribar",
  "Zincir",
  "Zirkon Taş",
  "Zirkonyum",
] as const;
