/**
 * @CategoryName Telefon > Cep Telefonu Aksesuarları > Akıllı Saat ve Bileklik Aksesuarları
 * @Field Renk
 */
export const WatchBand_Colors = [
  "Abyss",
  "Ahşap Rengi",
  "Alaska Mavi",
  "Alaskan Blue",
  "Alice Mavi",
  "Altuni",
  "Altın",
  "Altın - Beyaz",
  "Altın - Gold",
  "Altın - Golden",
  "Altın - Kahverengi",
  "Altın - Kırmızı",
  "Altın - Mavi",
  "Altın - Pembe",
  "Altın - Rose Gold",
  "Altın - Siyah",
  "Altın - Turkuaz",
  "Altın - Yeşil",
  "Anchor Gray",
  "Angel Mavi",
  "Antik Beyaz",
  "Antik Beyaz - Siyah",
  "Antique White",
  "Antrasit",
  "Antrasit - Altın",
  "Antrasit - Gri",
  "Antrasit - Siyah",
  "Apricot Peach",
  "Arı - Mor - Yeşil - Fıstık Yeşili - Bronz",
  "Asker Yeşili",
  "Asker Yeşili - Bej",
  "Asker Yeşili - Beyaz",
  "Asker Yeşili - Beyaz - Mavi",
  "Asker Yeşili - Beyaz - Mavi - Sarı - Kırmızı",
  "Asker Yeşili - Gri - Sarı",
  "Asker Yeşili - Gri - Sarı - Beyaz - Turuncu",
  "Asker Yeşili - Kırmızı - Siyah",
  "Asker Yeşili - Kırmızı - Siyah - Beyaz - Gri",
  "Asker Yeşili - Sarı",
  "Asker Yeşili - Siyah",
  "Asker Yeşili - Turuncu",
  "Asker Yeşili - Turuncu - Lila - Beyaz - Lacivert",
  "Askeri Yeşil - Kırmızı - Siyah",
  "Ay Beyazı",
  "Ayçiçeği",
  "Azur Mavi",
  "Açık Beyaz",
  "Açık Bordo",
  "Açık Cam Göbeği",
  "Açık Gri",
  "Açık Gri - Beyaz",
  "Açık Gökkuşağı",
  "Açık Gümüş",
  "Açık Haki",
  "Açık Kahverengi",
  "Açık Kahverengi - Kırmızı",
  "Açık Kahverengi - Siyah",
  "Açık Kahverengi - Yeşil",
  "Açık Kot Mavisi",
  "Açık Kırmızı",
  "Açık Lacivert",
  "Açık Lacivert - Beyaz",
  "Açık Mavi",
  "Açık Mavi - Beyaz",
  "Açık Mavi - Kahverengi",
  "Açık Mavi - Koyu Mavi",
  "Açık Mavi - Lacivert",
  "Açık Mavi - Mavi",
  "Açık Mavi - Pembe",
  "Açık Mavi - Sarı",
  "Açık Mavi - Siyah",
  "Açık Mavi - Yeşil",
  "Açık Mor",
  "Açık Nektarin",
  "Açık Pembe",
  "Açık Pembe - Beyaz",
  "Açık Pembe - Gri",
  "Açık Pembe - Lila - Gri -Beyaz - Sarı",
  "Açık Pembe - Mint",
  "Açık Pembe - Pembe - Kırmızı - Yavruağzı - Bronz",
  "Açık Pembe - Siyah",
  "Açık Pembe - Turkuaz",
  "Açık Sarı",
  "Açık Turkuaz",
  "Açık Turuncu",
  "Açık Yeşil",
  "Açık Yeşil - Açık Mavi - Beyaz - Açık Pembe - Gri",
  "Açık Yeşil - Beyaz",
  "Açık Yeşil - Gri",
  "Açık Yeşil - Koyu Yeşil - Turkuaz - Fıstık Yeşili - Yeşil",
  "Açık Yeşil - Mavi",
  "Açık Yeşil - Turuncu - Sarı",
  "Baby Mavi",
  "Bakır",
  "Bal Rengi",
  "Barut Mavisi",
  "Bebe Mavisi",
  "Bebek Mavisi",
  "Bebek Mavisi - Siyah",
  "Bej",
  "Bej - Beyaz",
  "Bej - Gümüş",
  "Bej - Lacivert",
  "Bej - Lansman Yeşili",
  "Bej - Sarı",
  "Bej - Siyah",
  "Bej - Turuncu",
  "Bej - Zeytinyağı Yeşili",
  "Benekli Pembe",
  "Beton Rengi",
  "Beyaz",
  "Beyaz - Açık Gri",
  "Beyaz - Açık Kahverengi",
  "Beyaz - Açık Mavi",
  "Beyaz - Açık Pembe",
  "Beyaz - Açık Pembe - Yeşil - Açık Yeşil Açık Mavi",
  "Beyaz - Açık Yeşil",
  "Beyaz - Bej",
  "Beyaz - Bordo",
  "Beyaz - Bordo - Lacivert - Sarı - Siyah",
  "Beyaz - Fuşya",
  "Beyaz - Gold",
  "Beyaz - Gri",
  "Beyaz - Gökkuşağı",
  "Beyaz - Gümüş",
  "Beyaz - Kahverengi",
  "Beyaz - Krem",
  "Beyaz - Kırmızı",
  "Beyaz - Kırmızı - Lila",
  "Beyaz - Kırmızı - Turuncu",
  "Beyaz - Lacivert",
  "Beyaz - Lacivert - Bordo",
  "Beyaz - Lila",
  "Beyaz - Mavi",
  "Beyaz - Mavi - Pembe",
  "Beyaz - Mavi - Sarı",
  "Beyaz - Mor",
  "Beyaz - Pembe",
  "Beyaz - Pembe - Kırmızı",
  "Beyaz - Pembe - Lila",
  "Beyaz - Pembe - Mor",
  "Beyaz - Renkli",
  "Beyaz - Rose",
  "Beyaz - Rose Gold",
  "Beyaz - Sarı",
  "Beyaz - Sarı - Kırmızı",
  "Beyaz - Sarı - Lacivert",
  "Beyaz - Siyah",
  "Beyaz - Siyah - Açık Mavi - Lacivert - Kırmızı",
  "Beyaz - Siyah - Gri",
  "Beyaz - Turkuaz",
  "Beyaz - Turkuaz - Fuşya",
  "Beyaz - Turuncu",
  "Beyaz - Turuncu - Pembe",
  "Beyaz - Turuncu - Sarı - Bordo - Lacivert",
  "Beyaz - Turuncu - Turkuaz",
  "Beyaz - Yeşil",
  "Beyaz - Yeşil - Pembe",
  "Beyaz Gökkuşağı",
  "Black",
  "Blue Cobalt",
  "Blue Horizon",
  "Bordo",
  "Bordo - Açık Kırmızı",
  "Bordo - Lila - Beyaz",
  "Bordo - Mavi",
  "Bordo - Mavi - Beyaz",
  "Bordo - Rose Gold",
  "Bordo - Siyah",
  "Bordo - Turuncu",
  "Bordo - Yeşil",
  "Briliant Blue",
  "Bronz",
  "Bronz - Altın",
  "Bronz - Gümüş",
  "Bronz - Kırmızı",
  "Bronz - Siyah",
  "Bulut",
  "Buz Mavi",
  "Buz Mavisi",
  "Buzlu Beyaz",
  "Buzlu Kırmızı",
  "Buzlu Lila",
  "Buzlu Pembe",
  "Buzlu Sarı",
  "Buzlu Saydam",
  "Buzlu Siyah",
  "Buzlu Turkuaz",
  "Buzlu Turuncu",
  "Buzlu Yeşil",
  "Buzlu Şeffaf",
  "Cam Göbeği",
  "Camel",
  "Canary Yellow",
  "Canlı Mavi",
  "Cape Cod Blue",
  "Cape Mavisi",
  "Cardiac Blue",
  "Cargo Haki",
  "Carnelian",
  "Celestial Teal",
  "Cerulean",
  "Ceviz Ağacı",
  "Ceviz Rengi",
  "Charcoal",
  "Chery Green",
  "Chinese Red",
  "Civit",
  "Clementine",
  "Cobalt Blue",
  "Cocoa",
  "Colorful Black",
  "Colorful Green",
  "Colorful Orange",
  "Colorful Red",
  "Concrete Gri",
  "Cornflower",
  "Cream Color",
  "Dark",
  "Dark Olive",
  "Deep Navy",
  "Deep Purple",
  "Demir Grisi",
  "Denim Blue",
  "Deniz Kabuğu",
  "Deniz Mavisi",
  "Deniz Yeşili",
  "Deniz Yeşili - Sarı",
  "Derin Mavi",
  "Derin Mor",
  "Derin Pembe",
  "Desert Sand",
  "Desert Sand - Volt Nike",
  "Dragonfruit",
  "Duman - Siyah - Lacivert",
  "Duman Mavi",
  "Dumanlı Mor",
  "Ebruli",
  "Eflatun - Beyaz",
  "Ejder Meyvesi",
  "Ekru",
  "Elder Berry",
  "Elegant Gri - Siyah",
  "Elektrik Pembe",
  "Erik Kırmızı",
  "Erik Kırmızısı",
  "Estoril Blue",
  "Estroil Blue",
  "Fallow",
  "Fenjianbai",
  "Fildişi",
  "Fink",
  "Flash",
  "Flash Light",
  "Fog Gray",
  "Fosforlu Kırmızı",
  "Fosforlu Pembe",
  "Fosforlu Yeşil",
  "Fosforlu Yeşil - Siyah",
  "Frambuaz",
  "Fuşya",
  "Fuşya - Lila - Pembe",
  "Fuşya - Siyah",
  "Füme",
  "Füme - Gri",
  "Füme - Pembe",
  "Füme - Siyah",
  "Fırtına Gri",
  "Fırtına Grisi",
  "Fıstık Yeşil - Siyah",
  "Fıstık Yeşili",
  "Fıstık Yeşili - Gri",
  "Fıstık Yeşili - Siyah",
  "Gece Mavi",
  "Gece Mavisi",
  "Gece Mavisi - Beyaz",
  "Gece Mavisi - Gri",
  "Gece Mavisi - Sarı",
  "Gece Mavisi - Siyah",
  "Gece Mavisi - Turuncu",
  "Gece Yarısı Mavisi",
  "Gold",
  "Gold - Bal Rengi",
  "Gold - Beyaz",
  "Gold - Gümüş",
  "Gold - Koyu Mavi",
  "Gold - Kırmızı",
  "Gold - Lila - Krem",
  "Gold - Lila - Yeşil",
  "Gold - Mavi",
  "Gold - Pembe - Yeşil",
  "Gold - Siyah",
  "Gold - Turkuaz",
  "Gold - Yeşil",
  "Gold - İnci Beyazı",
  "Greyfurt",
  "Greyfurt Rengi",
  "Gri",
  "Gri - Altın",
  "Gri - Açık Gri",
  "Gri - Açık Yeşil",
  "Gri - Beyaz",
  "Gri - Deniz Mavisi",
  "Gri - Füme",
  "Gri - Gold",
  "Gri - Grey",
  "Gri - Gümüş",
  "Gri - Kahverengi",
  "Gri - Koyu Mavi",
  "Gri - Koyu Mavi - Siyah - Koyu Yeşil - Yeşil",
  "Gri - Kırmızı",
  "Gri - Mavi",
  "Gri - Mor",
  "Gri - Nane Yeşili",
  "Gri - Neon Yeşil",
  "Gri - Pembe",
  "Gri - Pembe - Açık Gri",
  "Gri - Rose",
  "Gri - Rose Gold",
  "Gri - Sarı",
  "Gri - Sarı - Kırmızı",
  "Gri - Sarı - Lacivert",
  "Gri - Siyah",
  "Gri - Turkuaz",
  "Gri - Turuncu",
  "Gri - Turuncu - Lacivert",
  "Gri - Yeşil",
  "Gri - Yeşil - Beyaz",
  "Gri Beyaz",
  "Gri Çiçek",
  "Griseo",
  "Gök Kuşağı - Beyaz",
  "Gök Mavi",
  "Gökkuşağı",
  "Gökyüzü Mavi",
  "Gökyüzü Mavisi",
  "Göl Mavisi",
  "Gül Kurusu",
  "Gül Kırmızısı",
  "Gül Pembe",
  "Gül Pembesi",
  "Gümüş",
  "Gümüş - Altın",
  "Gümüş - Açık Yeşil",
  "Gümüş - Bal Rengi",
  "Gümüş - Beyaz",
  "Gümüş - Bronz",
  "Gümüş - Gold",
  "Gümüş - Gri",
  "Gümüş - Gökkuşağı",
  "Gümüş - Haki",
  "Gümüş - Kahverengi",
  "Gümüş - Koyu Yeşil",
  "Gümüş - Krem",
  "Gümüş - Kırmızı",
  "Gümüş - Lacivert",
  "Gümüş - Mavi",
  "Gümüş - Pembe",
  "Gümüş - Pembe - Yeşil",
  "Gümüş - Rose",
  "Gümüş - Rose Gold",
  "Gümüş - Sarı",
  "Gümüş - Siyah",
  "Gümüş - Turuncu",
  "Gümüş - Yeşil",
  "Gümüş - İnci Beyazı",
  "Gümüş - İncı Beyazı",
  "Gün Işığı",
  "Güneş Işığı",
  "Haki",
  "Haki - Füme",
  "Haki - Gri",
  "Haki - Gümüş",
  "Haki - Lacivert",
  "Haki - Mavi",
  "Haki - Sarı",
  "Haki - Siyah",
  "Haki - Turuncu",
  "Haki Yeşil",
  "Haki Yeşil - Beyaz",
  "Haki Yeşil - Füme",
  "Hardal",
  "Hardal - Gümüş",
  "Hardal - Kahve",
  "Hardal - Kahverengi",
  "Hibiscus",
  "Hiper Kırmızı",
  "Hiper Kırmızı - Neptün Yeşili",
  "Hiper Kırmızı - Yeşil",
  "Hyper Grape",
  "Indigo - Mavi",
  "Inverness Green",
  "Inverness Gri",
  "Jasper",
  "Jean Mavi",
  "Kahve",
  "Kahve - Mor",
  "Kahverengi",
  "Kahverengi - Altın",
  "Kahverengi - Bej",
  "Kahverengi - Beyaz",
  "Kahverengi - Gold",
  "Kahverengi - Gri",
  "Kahverengi - Gümüş",
  "Kahverengi - Kayısı Rengi",
  "Kahverengi - Kırmızı",
  "Kahverengi - Lacivert",
  "Kahverengi - Rosegold",
  "Kahverengi - Sarı",
  "Kahverengi - Siyah",
  "Kahverengi - Turuncu",
  "Kahverengi - Yeşil",
  "Kahverengi Leopar",
  "Kaktüs Rengi",
  "Kaktüs Yeşil",
  "Kalipso Mavisi",
  "Kamuflaj",
  "Kamuflaj Gri",
  "Kamuflaj Mavi",
  "Kamuflaj Yeşil",
  "Kamuflaj Yeşili",
  "Kanvas Mavi",
  "Kapalı Gri",
  "Karbon",
  "Kardinal",
  "Kargo Haki",
  "Karmen Kırmızı",
  "Karpuz Kırmızısı",
  "Karışık Renkli",
  "Kavun İçi Rengi",
  "Kaya Grisi",
  "Kaya Mavisi",
  "Kaya Turuncu",
  "Kaya Yeşili",
  "Kayısı",
  "Kayısı Rengi",
  "Kayısı Rengi - Haki",
  "Kayısı Rengi - Portakal Rengi",
  "Kayısı Rengi - Turuncu",
  "Kiraz Yeşili",
  "Kiraz Çiçeği Pembesi",
  "Kiremit",
  "Kiremit - Bordo",
  "Kobalt Mavisi",
  "Kot Mavi",
  "Kot Mavisi",
  "Kot Siyahı",
  "Koyu  Yeşil",
  "Koyu - Yeşil",
  "Koyu Altın",
  "Koyu Bej",
  "Koyu Beyaz",
  "Koyu Bordo",
  "Koyu Cam Göbeği",
  "Koyu Fuşya",
  "Koyu Füme",
  "Koyu Gri",
  "Koyu Gri - Açık Gri",
  "Koyu Gri - Koyu Yeşil",
  "Koyu Gri - Siyah",
  "Koyu Gri - Turkuaz",
  "Koyu Gökkuşağı",
  "Koyu Haki",
  "Koyu Kahverengi",
  "Koyu Kahverengi - Beyaz",
  "Koyu Kahverengi - Kırmızı",
  "Koyu Kırmızı",
  "Koyu Kırmızı - Gri",
  "Koyu Lacivert",
  "Koyu Lacivert - Beyaz",
  "Koyu Lila",
  "Koyu Mavi",
  "Koyu Mavi - Açık Mavi",
  "Koyu Mavi - Açık Mavi - Siyah",
  "Koyu Mavi - Beyaz",
  "Koyu Mavi - Gümüş",
  "Koyu Mavi - Kırmızı",
  "Koyu Mavi - Mor",
  "Koyu Mavi - Pembe",
  "Koyu Mavi - Sarı",
  "Koyu Mavi - Siyah",
  "Koyu Mavi - Turuncu",
  "Koyu Mor",
  "Koyu Mor - Altın",
  "Koyu Mor - Turuncu",
  "Koyu Mor - Yeşil",
  "Koyu Pembe",
  "Koyu Pembe - Açık Pembe",
  "Koyu Royal Mavi",
  "Koyu Sarı",
  "Koyu Siyah",
  "Koyu Turkuaz",
  "Koyu Turuncu",
  "Koyu Yeşi - Turuncu",
  "Koyu Yeşil",
  "Koyu Yeşil - Füme",
  "Koyu Yeşil - Sarı",
  "Koyu Yeşil - Siyah",
  "Koyu Yeşil - Turuncu",
  "Koyu Zeytin Yeşili",
  "Kraliyet Mavisi",
  "Krem",
  "Krem - Açık Yeşil",
  "Krem - Gri",
  "Krem - Kahve",
  "Krem - Kırmızı",
  "Krem - Siyah",
  "Krem - Yeşil",
  "Krem Rengi",
  "Kremsi Beyaz",
  "Kristal Mavi",
  "Krizantem Mavisi",
  "Krom",
  "Kum Pembe",
  "Kum Pembe - Beyaz",
  "Kum Pembesi",
  "Kum Rengi",
  "Kumkuat",
  "Kömür Grisi",
  "Kömür Siyahı",
  "Kül Gri",
  "Kırmızı",
  "Kırmızı  - Beyaz",
  "Kırmızı - Altın",
  "Kırmızı - Açık Pembe",
  "Kırmızı - Bej",
  "Kırmızı - Beyaz",
  "Kırmızı - Beyaz - Pembe",
  "Kırmızı - Beyaz - Siyah",
  "Kırmızı - Beyaz - Yeşil",
  "Kırmızı - Bordo",
  "Kırmızı - Gri - Mavi",
  "Kırmızı - Gümüş",
  "Kırmızı - Kahverengi",
  "Kırmızı - Koyu Pembe",
  "Kırmızı - Lacivert",
  "Kırmızı - Lila",
  "Kırmızı - Mavi",
  "Kırmızı - Mavi - Asker Yeşili",
  "Kırmızı - Mavi - Asker Yeşili - Gri - Sarı",
  "Kırmızı - Mor",
  "Kırmızı - Mor - Pembe",
  "Kırmızı - Pembe",
  "Kırmızı - Red",
  "Kırmızı - Rose",
  "Kırmızı - Rose Gold",
  "Kırmızı - Sarı",
  "Kırmızı - Siyah",
  "Kırmızı - Siyah - Beyaz",
  "Kırmızı - Turkuaz",
  "Kırmızı - Turuncu",
  "Kırmızı - Turuncu - Sarı",
  "Kırmızı - Yeşil",
  "Kırmızı Çiçek",
  "Kırmızı Şarap",
  "Kırmızı – Siyah",
  "Kırmızımsı Mavi",
  "Kırçıllı Pembe",
  "Kırçıllı Siyah",
  "Kırık Beyaz",
  "Kızıl",
  "Kızıl Kiraz",
  "Lacivert",
  "Lacivert - Altın",
  "Lacivert - Açık Mavi",
  "Lacivert - Açık Yeşil",
  "Lacivert - Bej",
  "Lacivert - Beyaz",
  "Lacivert - Beyaz - Kırmızı",
  "Lacivert - Beyaz - Mavi",
  "Lacivert - Beyaz - Pembe",
  "Lacivert - Gold",
  "Lacivert - Gri",
  "Lacivert - Gümüş",
  "Lacivert - Haki",
  "Lacivert - Kahverengi",
  "Lacivert - Krem",
  "Lacivert - Kırmızı",
  "Lacivert - Mavi",
  "Lacivert - Mavi - Kahverengi",
  "Lacivert - Mor",
  "Lacivert - Mor - Beyaz",
  "Lacivert - Mor - Yeşil",
  "Lacivert - Pembe",
  "Lacivert - Sarı",
  "Lacivert - Siyah",
  "Lacivert - Siyah - Açık Mavi - Mavi - Koyu Mavi",
  "Lacivert - Turkuaz",
  "Lacivert - Turuncu",
  "Lacivert - Turuncu - Yeşil",
  "Lacivert - Yeşil",
  "Lacivert - Yeşil - Sarı",
  "Ladin Gri",
  "Lake Blue",
  "Lansman Yeşili",
  "Lavanta",
  "Lavanta Grisi",
  "Lavanta Moru",
  "Lavanta Rengi",
  "Lavanta Rengi - Gri",
  "Lavanta Rengi - Mor",
  "Lavender Gri",
  "Leopar",
  "Leylak",
  "Leylak - Siyah",
  "Leylak Moru",
  "Leylak Rengi",
  "Lila",
  "Lila - Bordo - Lacivert",
  "Lila - Gold - Beyaz",
  "Lila - Gri",
  "Lila - Gri - Beyaz - Mor - Bronz",
  "Lila - Kırmızı - Bordo",
  "Lila - Mor",
  "Lila - Mor - Pembe",
  "Lila - Rose Gold",
  "Lila - Rose Gold - Beyaz",
  "Lila - Rose Gold - Pembe",
  "Lila - Sarı",
  "Lila - Siyah",
  "Lila - Turuncu",
  "Lila - Turuncu - Asker Yeşili",
  "Lila - Turuncu - Açık Yeşil",
  "Lilac",
  "Lime",
  "Lime Green",
  "Limon - Siyah",
  "Limon Sarısı",
  "Limon Sarısı - Yeşil",
  "Limon Yeşili",
  "Limon Yeşili - Beyaz",
  "Limon Yeşili - Siyah",
  "Malahit Yeşili",
  "Marine Green",
  "Matcha Yeşili",
  "Maun Turuncu",
  "Mavi",
  "Mavi -  Beyaz",
  "Mavi - Altın",
  "Mavi - Açık Mavi",
  "Mavi - Açık Mavi - Beyaz",
  "Mavi - Açık Pembe",
  "Mavi - Bej",
  "Mavi - Beyaz",
  "Mavi - Beyaz - Kırmızı",
  "Mavi - Füme",
  "Mavi - Gold",
  "Mavi - Gri",
  "Mavi - Gri - Yeşil",
  "Mavi - Gümüş",
  "Mavi - Haki",
  "Mavi - Kahverengi",
  "Mavi - Krem",
  "Mavi - Kırmızı",
  "Mavi - Lacivert",
  "Mavi - Lila",
  "Mavi - Mavi",
  "Mavi - Mor",
  "Mavi - Mor - Beyaz",
  "Mavi - Mor - Lacivert",
  "Mavi - Mor - Yeşil",
  "Mavi - Pembe",
  "Mavi - Pembe - Lila",
  "Mavi - Sarı",
  "Mavi - Siyah",
  "Mavi - Siyah - Beyaz",
  "Mavi - Turkuaz",
  "Mavi - Turuncu",
  "Mavi - Turuncu - Lila",
  "Mavi - Yeşil",
  "Mavi - Beyaz",
  "Mavi Flash",
  "Mavi Gökkuşağı",
  "Mavi Kamuflaj",
  "Mavi Mürekkep",
  "Mavi Çiçek",
  "Mavi-Yeşil",
  "Mavi-Yeşil-Siyah",
  "Menekşe Rengi",
  "Mercan",
  "Mercan Kırmızı",
  "Metal",
  "Metalik Gold",
  "Midnight Blue",
  "Midnight Fog",
  "Mint",
  "Mint Yeşil",
  "Mint Yeşili",
  "Mint Yeşili - Mavi",
  "Mint Yeşili - Siyah",
  "Moon Stone",
  "Mor",
  "Mor - Altın",
  "Mor - Beyaz",
  "Mor - Bronz - Lacivert - Siyah - Koyu Mavi",
  "Mor - Gri",
  "Mor - Gümüş",
  "Mor - Kırmızı",
  "Mor - Kırmızı - Gold",
  "Mor - Lacivert",
  "Mor - Lila",
  "Mor - Mavi",
  "Mor - Pembe",
  "Mor - Pembe - Mavi",
  "Mor - Rose",
  "Mor - Rose Gold",
  "Mor - Sarı",
  "Mor - Siyah",
  "Mor - Turkuaz",
  "Mor - Turuncu",
  "Mor - Yeşil",
  "Mor - Şarap Kırmızısı",
  "Mor Erik",
  "Mor Işık",
  "Moss Green",
  "Mozaik Desenli",
  "Mürdüm",
  "Mürdüm - Pembe",
  "Mürekkep Mavisi",
  "Mısır Çiçeği Rengi",
  "Nane Yeşil - Mavi",
  "Nane Yeşil Pembe",
  "Nane Yeşili",
  "Nane Yeşili - Mavi",
  "Nar",
  "Nar Rengi - Siyah",
  "Nar Çiçeği",
  "Nektarin",
  "Neon Green",
  "Neon Kırmızı",
  "Neon Mavi",
  "Neon Pembe",
  "Neon Pembe - Neon Yeşil",
  "Neon Turuncu",
  "Neon Yeşil",
  "Neptün Yeşili",
  "Nil Yeşili",
  "Nil Yeşili - Beyaz",
  "Nil Yeşili - Pembe",
  "Nil Yeşili - Peri Mavi",
  "Obsidyen Gri",
  "Okyanus Mavi",
  "Okyanus Mavisi",
  "Olive",
  "Olive Flak",
  "Opsidian Mint",
  "Orange",
  "Ordu Yeşili",
  "Ordu Yeşili -  Siyah",
  "Ordu Yeşili - Beyaz",
  "Ordu Yeşili - Gümüş",
  "Ordu Yeşili - Siyah",
  "Orman Yeşili",
  "Papaya",
  "Parlak Beyaz",
  "Parlak Lacivert",
  "Parlak Mavi",
  "Parlak Mor",
  "Parlak Pembe",
  "Parlak Sarı",
  "Parlak Siyah",
  "Parlak Turuncu",
  "Parlak Yeşil",
  "Pastel Mavi",
  "Patlıcan Moru",
  "Pearl Pink",
  "Pelerin Mavisi",
  "Pembe",
  "Pembe - Altın",
  "Pembe - Bej",
  "Pembe - Beyaz",
  "Pembe - Bordo - Turuncu",
  "Pembe - Cam Göbeği",
  "Pembe - Gold",
  "Pembe - Gri",
  "Pembe - Gri - Beyaz",
  "Pembe - Gökkuşağı",
  "Pembe - Gümüş",
  "Pembe - Kahverengi",
  "Pembe - Koyu Pembe",
  "Pembe - Krem",
  "Pembe - Kum Rengi",
  "Pembe - Kırmızı",
  "Pembe - Lila",
  "Pembe - Mavi",
  "Pembe - Mavi - Beyaz",
  "Pembe - Mavi - Duman",
  "Pembe - Mor",
  "Pembe - Mor - Beyaz",
  "Pembe - Mürdüm",
  "Pembe - Peri Mavi",
  "Pembe - Pudra",
  "Pembe - Renkli",
  "Pembe - Rose",
  "Pembe - Sarı",
  "Pembe - Sarı - Lila",
  "Pembe - Siyah",
  "Pembe - Siyah Mavisi",
  "Pembe - Turkuaz",
  "Pembe - Turuncu",
  "Pembe - Turuncu - Sarı",
  "Pembe - Yeşil",
  "Pembe - Şeffaf",
  "Pembe Gökkuşağı",
  "Pembe Kamuflaj",
  "Peri Mavi",
  "Peri Mavi - Rose Gold",
  "Petrol",
  "Petrol - Gümüş",
  "Petrol Mavi",
  "Petrol Mavisi",
  "Petrol Mavisi - Beyaz",
  "Petrol Yeşili",
  "Pink Blast",
  "Pink Blast - True Berry",
  "Pink Sand",
  "Pink Wheat",
  "Pitaya",
  "Platin - Gri",
  "Plum",
  "Pomegranate",
  "Portakal",
  "Pride Edition",
  "Product Red",
  "Prusya Mavisi",
  "Pudra",
  "Pudra Pembe",
  "Pudra Pembe - Beyaz",
  "Pudra Pembe - Siyah",
  "Pudra Pembesi",
  "Puslu Mor",
  "Red Purple",
  "Reflector Black",
  "Renkli",
  "Renkli  - Gümüş",
  "Renkli - Gümüş",
  "Renkli - Kırmızı",
  "Renkli - Mavi",
  "Renkli - Siyah",
  "Renkli - Turuncu",
  "Renkli - Yeşil",
  "Renksiz",
  "Retro Gold",
  "Rock Blue",
  "Rose",
  "Rose - Altın",
  "Rose - Gold",
  "Rose - Kırmızı",
  "Rose - Lila - Fuşya - Beyaz - Nil - Pembe - Peri Mavi",
  "Rose - Mor",
  "Rose - Pembe - Kırmızı - Mor - Fuşya - Z.Yağı Yeşili - Nil",
  "Rose - Pembe - Lila - Sarı - Mor - Nil - Z.Yağı Yeşili",
  "Rose - Siyah",
  "Rose Gold",
  "Rose Gold - Beyaz",
  "Rose Gold - Bordo - Lacivert",
  "Rose Gold - Füme",
  "Rose Gold - Gold",
  "Rose Gold - Gümüş",
  "Rose Gold - Lacivert",
  "Rose Gold - Mavi",
  "Rose Gold - Mor",
  "Rose Gold - Pembe",
  "Rose Gold - Siyah",
  "Rose Gold - Turuncu - Lansman Yeşili",
  "Rose Gold - Turuncu - Yeşil",
  "Rose Gold - Yeşil",
  "Rose Pink",
  "Royal Blue",
  "Royal Mavi",
  "Royal Pulse",
  "Royal Pulse - Lava Glow",
  "Safir Mavi",
  "Safir Mavisi",
  "Saks",
  "Saks Mavi",
  "Saks Mavi - Kahverengi",
  "Sap Yeşili",
  "Sarı",
  "Sarı - Açık Kahverengi",
  "Sarı - Bej",
  "Sarı - Beyaz",
  "Sarı - Beyaz - Lacivert",
  "Sarı - Beyaz - Siyah",
  "Sarı - Gri",
  "Sarı - Kahverengi",
  "Sarı - Kiremit",
  "Sarı - Koyu Mavi",
  "Sarı - Krem",
  "Sarı - Kırmızı",
  "Sarı - Kırmızı - Lila",
  "Sarı - Lacivert",
  "Sarı - Lacivert - Beyaz",
  "Sarı - Lila",
  "Sarı - Lila - Yeşil",
  "Sarı - Mor",
  "Sarı - Pembe - Turuncu",
  "Sarı - Siyah",
  "Sarı - Siyah - Altın",
  "Sarı - Siyah - Lila",
  "Sarı - Turuncu",
  "Sarı - Turuncu - Asker Yeşili",
  "Sarı - Turuncu - Açık Yeşil",
  "Sarı - Turuncu - Lansman Yeşili",
  "Sarı - Turuncu - Yeşil",
  "Sarı - Yeşil",
  "Sarı - Yeşil - Beyaz",
  "Sarı - Yeşil - Mavi - Gri - Turuncu - Bordo - Beyaz",
  "Saydam",
  "Sea Salt",
  "Sea Shell",
  "Silver",
  "Siyah",
  "Siyah  - Gümüş",
  "Siyah  - Kırmızı",
  "Siyah -  Asker Yeşili",
  "Siyah -  Beyaz",
  "Siyah -  Koyu Gri",
  "Siyah -  Kırmızı",
  "Siyah -  Yeşil",
  "Siyah - Altın",
  "Siyah - Açık Gri",
  "Siyah - Açık Kahverengi",
  "Siyah - Açık Mavi",
  "Siyah - Açık Pembe",
  "Siyah - Bej",
  "Siyah - Beyaz",
  "Siyah - Beyaz - Gri",
  "Siyah - Beyaz - Kırmızı",
  "Siyah - Beyaz - Pudra",
  "Siyah - Beyaz - Sarı",
  "Siyah - Beyaz - Yeşil - Kırmızı - Gri",
  "Siyah - Bordo",
  "Siyah - Füme",
  "Siyah - Gold",
  "Siyah - Gri",
  "Siyah - Gri - Gece Mavisi",
  "Siyah - Gri - Kırmızı",
  "Siyah - Gri - Kırmızı - Lacivert - Bordo",
  "Siyah - Gümüş",
  "Siyah - Haki",
  "Siyah - Kahverengi",
  "Siyah - Kireç Yeşili",
  "Siyah - Koyu Gri",
  "Siyah - Koyu Mavi",
  "Siyah - Koyu Pembe",
  "Siyah - Kırmızı",
  "Siyah - Kırmızı - Lila",
  "Siyah - Kırmızı - Sarı",
  "Siyah - Lacivert",
  "Siyah - Lacivert - Sarı",
  "Siyah - Lila",
  "Siyah - Mavi",
  "Siyah - Mor",
  "Siyah - Mor - Lacivert",
  "Siyah - Mürdüm",
  "Siyah - Nane Yeşili",
  "Siyah - Neon Yeşil",
  "Siyah - Ordu Yeşili",
  "Siyah - Pembe",
  "Siyah - Pembe - Beyaz",
  "Siyah - Pembe - Lila",
  "Siyah - Renkli",
  "Siyah - Rose",
  "Siyah - Rose Gold",
  "Siyah - Sarı",
  "Siyah - Siyah",
  "Siyah - Turkuaz",
  "Siyah - Turuncu",
  "Siyah - Turuncu - Sarı",
  "Siyah - Yeşil",
  "Siyah - Çok Renkli",
  "Siyah - Şarap Kırmızısı",
  "Siyah - Şeffaf",
  "Siyah Leopar",
  "Siyah Mat",
  "Siyah Siyah - Gold",
  "Siyah Yeşil",
  "Siyah Çiçek",
  "Siyah-Gri",
  "Smokey Mauve",
  "Soft Sarı",
  "Soft Siyah",
  "Soft White",
  "Soluk Kırmızı",
  "Soluk Mavi",
  "Soluk Sarı",
  "Soluk Yeşil",
  "Somon",
  "Somon - Altın",
  "Soğuk Mavi",
  "Spearmint",
  "Spicy Orange",
  "Spruce Aura",
  "Spruce Fog",
  "Starlight",
  "Storm Blue",
  "Storm Gray",
  "Su Kırmızısı",
  "Su Mavisi",
  "Su Yeşili",
  "Su Yeşili - Beyaz",
  "Su Yeşili - Gri",
  "Su Yeşili - Sarı",
  "Su Yeşili - Siyah",
  "Su yeşili - Neon Yeşil",
  "Summit White",
  "Sun Flowwer",
  "Surf Blue",
  "Sörf Mavisi",
  "Süt Beyazı",
  "Sütlü Kahve",
  "Sıcak Pembe",
  "TURUNCU-ASKER YEŞİLİ-SİYAH-BEYAZ-LİLA-SARI-LACİVERT",
  "Taba",
  "Taba - Gold",
  "Taba - Gümüş",
  "Taba - Kahve",
  "Taba - Lacivert",
  "Taba - Rosegold",
  "Taba - Siyah",
  "Tahoe Blue",
  "Taş",
  "Teal Tint",
  "Ten - Pembe",
  "Ten Rengi",
  "Titanyum",
  "Toz Pembe",
  "Toz Pembe - Pembe",
  "Tricolor Red",
  "True Berry",
  "Turkaz - Yeşil",
  "Turkuaz",
  "Turkuaz - Altın",
  "Turkuaz - Beyaz",
  "Turkuaz - Kahverengi",
  "Turkuaz - Koyu Gri",
  "Turkuaz - Krem",
  "Turkuaz - Lacivert",
  "Turkuaz - Mavi",
  "Turkuaz - Pembe",
  "Turkuaz - Sarı",
  "Turkuaz - Sarı - Bej",
  "Turkuaz - Siyah",
  "Turkuaz - Yeşil",
  "Turuncu",
  "Turuncu - Altın",
  "Turuncu - Bej",
  "Turuncu - Beyaz",
  "Turuncu - Beyaz - Yeşil",
  "Turuncu - Bordo",
  "Turuncu - Bordo - Rose - Lacivert - Siyah",
  "Turuncu - Füme",
  "Turuncu - Gece Mavisi",
  "Turuncu - Gri",
  "Turuncu - Gümüş",
  "Turuncu - Haki",
  "Turuncu - Koyu Gri",
  "Turuncu - Koyu Yeşil",
  "Turuncu - Krem",
  "Turuncu - Kırmızı",
  "Turuncu - Kırmızı - Yeşil",
  "Turuncu - Lacivert",
  "Turuncu - Lila",
  "Turuncu - Lila - Bordo - Lacivert - Sarı",
  "Turuncu - Mavi",
  "Turuncu - Mor",
  "Turuncu - Pembe",
  "Turuncu - Sarı",
  "Turuncu - Siyah",
  "Turuncu - Siyah - Beyaz",
  "Turuncu - Turkuaz",
  "Turuncu - Yeşil",
  "Turuncu - Yeşil - Lacivert - Peri Mavi - Beyaz - Sarı - Krem Bej",
  "Turuncu - Yeşil - Lcvrt - Peri Mavi - Beyaz - Sarı - Krem Bej",
  "Turuncu Siyah",
  "Ufuk Mavi - Açık Mavi",
  "Ufuk Mavisi",
  "Uzay Gri",
  "Uçuk Haki",
  "Uçuk Mavi",
  "Uçuk Sarı",
  "Vintage",
  "Vintage Gold",
  "Vitamin C",
  "Vizon - Çöl Kumu",
  "Vişne",
  "Vişne Yeşili",
  "Wine Red",
  "Yanık Metal",
  "Yavruağzı",
  "Yağ Yeşili",
  "Yeni Mor",
  "Yeni Parlak Mor",
  "Yeşil",
  "Yeşil  - Siyah",
  "Yeşil - Altın",
  "Yeşil - Beyaz",
  "Yeşil - Beyaz - Kırmızı",
  "Yeşil - Bordo - Lacivert",
  "Yeşil - Gold",
  "Yeşil - Gri",
  "Yeşil - Gümüş",
  "Yeşil - Haki",
  "Yeşil - Kahve",
  "Yeşil - Kahverengi",
  "Yeşil - Kırmızı",
  "Yeşil - Kırmızı - Siyah",
  "Yeşil - Lacivert",
  "Yeşil - Lacivert - Açık Pembe - Pembe - Sarı",
  "Yeşil - Lila",
  "Yeşil - Mavi",
  "Yeşil - Mint",
  "Yeşil - Mor",
  "Yeşil - Mor - Pembe",
  "Yeşil - Mürdüm",
  "Yeşil - Pembe",
  "Yeşil - Sarı",
  "Yeşil - Siyah",
  "Yeşil - Siyah - Kırmızı",
  "Yeşil - Somon",
  "Yeşil - Turkuaz",
  "Yeşil - Turuncu",
  "Yeşil - Yeşil",
  "Yeşil Kamuflaj",
  "Yeşil Koyu - Mor",
  "Yeşil Mango",
  "Yeşil Siyah",
  "Yosun Yeşili",
  "Yıldız",
  "Yıldız Siyahı",
  "Zeytin",
  "Zeytin Yeşili",
  "Zeytin Yeşili - Siyah",
  "Zeytuni",
  "Zümrüt Yeşili",
  "Zümrüt Yeşili - Siyah",
  "Çam Mavi",
  "Çam Yeşili",
  "Çam Yeşilii",
  "Çam Çiçeği Yeşil",
  "Çam Çiçeği Yeşili",
  "Çam İğnesi Yeşili",
  "Çelik Mavisi",
  "Çilek",
  "Çimen Yeşili",
  "Çivit Mavisi",
  "Çok Renkli",
  "Çöl Kumu - Kahve",
  "Ördek Yeşili",
  "Üzüm Moru",
  "İnci Beyazı",
  "İndigo",
  "İndigo Mavi - Limon Yeşili",
  "İpek Beyazı",
  "Şampanya",
  "Şampanya - Altın",
  "Şampanya Rengi",
  "Şampanya Rengi - Altın",
  "Şarap Kırmızı - Siyah",
  "Şarap Kırmızısı",
  "Şarap Kırmızısı - Altın",
  "Şarap Kırmızısı - Rose",
  "Şeffaf",
  "Şeffaf - Beyaz",
  "Şeffaf - Gold",
  "Şeffaf - Gri",
  "Şeffaf - Kırmızı",
  "Şeffaf - Mavi",
  "Şeffaf - Mor",
  "Şeffaf - Rose",
  "Şeffaf - Siyah",
  "Şeffaf - Turuncu",
  "Şeffaf - Yeşil",
  "Şeffaf Beyaz",
  "Şeffaf Gri",
  "Şeffaf Kırmızı",
  "Şeffaf Mavi",
  "Şeffaf Mor",
  "Şeffaf Pembe",
  "Şeffaf Sarı",
  "Şeffaf Siyah",
  "Şeffaf Turuncu",
  "Şeffaf Yeşil",
  "Şeftali",
  "Şeker Pembe",
] as const;

/**
 * @CategoryName Telefon > Cep Telefonu Aksesuarları > Akıllı Saat ve Bileklik Aksesuarları
 * @Field Uyumlu Marka
 */
export const WatchBand_Brands = [
  "Apple",
  "Amazfit",
  "Samsung",
  "Xiaomi",
  "Huawei",
  "3Plus",
  "APPScomm",
  "Abardeen",
  "Adidas",
  "Alcatel",
  "Ally Gear",
  "Armani",
  "Asus",
  "Bilicra",
  "Bix",
  "Black Dice",
  "Blitzwolf",
  "Blocks",
  "Bryton",
  "Carmenta",
  "Case 4U",
  "Casio",
  "Colmi",
  "Coros",
  "Corsair",
  "Cwatch",
  "Daniel Klein",
  "Dark",
  "Diesel",
  "Everest",
  "Ezcool",
  "Ferro",
  "Ferrucci",
  "Fitbit",
  "Fossil",
  "Garmin",
  "General Mobile",
  "Google",
  "Gs 7",
  "Hattrick",
  "Havit",
  "Haylou",
  "Hiking",
  "Honor",
  "Huami",
  "Inteya",
  "Ixtech",
  "JBL",
  "Jawbone",
  "Jiaming",
  "Joyroom",
  "Kallow",
  "Kieslect",
  "Kingwear",
  "Kospet",
  "LG",
  "Leery bee",
  "Lemfo",
  "Lenfo",
  "Lenovo",
  "Little Genius",
  "Lokmat",
  "Marc Jacobs",
  "Megafox",
  "Mibro",
  "Michael Kors",
  "Microsoft",
  "Mini Focus",
  "Misfit",
  "Montblanc",
  "Motorola",
  "Mykronoz",
  "Nixon",
  "Noerden",
  "Nokia",
  "Nubia",
  "One Plus",
  "Onkatech",
  "Onurlu",
  "Oppo",
  "Orbo",
  "Patric",
  "Pebble",
  "Peeble",
  "Polar",
  "Polar M600",
  "Powehi",
  "Preo",
  "QCY",
  "Quark",
  "Realme",
  "Reeder",
  "Robar",
  "Robor",
  "Rolex",
  "Scinex",
  "Senbono",
  "Sentar",
  "Sequent",
  "Skagen",
  "Slazenger Kids Tiger",
  "Sony",
  "Spovan",
  "Suunto",
  "Tag Heuer",
  "Tecno",
  "Teknoşık",
  "TicWatch",
  "TicWatch C2",
  "TomTom Runner",
  "Tomtom",
  "Torima",
  "Trident",
  "Universal",
  "Vector",
  "Vestel",
  "Victor",
  "Vivo",
  "Wesse",
  "Wiky",
  "Winex",
  "Withings",
  "ZTE",
  "Zcwatch",
  "Zebiaze",
  "Zeblaze",
  "Zepp",
  "Zepp Z",
  "Şıktek",
] as const;

/**
 * @CategoryName Telefon > Cep Telefonu Aksesuarları > Akıllı Saat ve Bileklik Aksesuarları
 * @SelfMade
 */
export const WatchBand_CustomSizes = ["38-40-41", "42-44-45-49"] as const;
