import { EMPTY_OPTION } from "../../../lib/variables";

/**
 * @CategoryName Telefon > Cep Telefonu Aksesuarları > Kılıflar
 * @Field Uyumlu Model
 * @Optional
 */
export const PhoneCase_PhoneModelsList = [
  EMPTY_OPTION,
  "10",
  "10 4G",
  "10 Pro",
  "10 Pro+ Plus",
  "10 SE",
  "10A",
  "10C",
  "10T",
  "10T 5G",
  "11",
  "11 Lite",
  "11 Lite 5G NE",
  "11 Pro 5G",
  "11 Pro Max",
  "11T / 11T Pro",
  "11T Pro",
  "12",
  "12 / 12X",
  "12 Lite",
  "12 Mini",
  "12 Pro",
  "12 Pro Max",
  "12S Pro",
  "12S Ultra",
  "12T / 12T Pro",
  "12X",
  "13",
  "13 Pro",
  "13 Pro Max",
  "13 mini",
  "16Xs",
  "18 Premier",
  "1S",
  "1S 2020",
  "20 XE",
  "20R 5G",
  "20S",
  "2G",
  "3 Pro",
  "30 XE 5G",
  "303",
  "30SE",
  "3G",
  "3GS",
  "3X 2019",
  "3X 2020",
  "408",
  "4G Android One",
  "5V",
  "5i",
  "5s",
  "5x",
  "6 Plus",
  "6 S",
  "60 Pro",
  "6070",
  "6i",
  "6s",
  "7",
  "7 Plus",
  "7 Pro",
  "8",
  "8 Plus",
  "8A",
  "8C",
  "9C",
  "9i 4G",
  "9i 5G",
  "A03",
  "A03s",
  "A04s",
  "A1",
  "A1 Pro 5G",
  "A11",
  "A11S",
  "A12",
  "A12s",
  "A13 Pro 5G",
  "A13/A13S/A13 Pro",
  "A15",
  "A15S",
  "A16",
  "A16K",
  "A1X 5G/A58X 5G",
  "A20e",
  "A20s",
  "A21s",
  "A22",
  "A27",
  "A28",
  "A29",
  "A3",
  "A3 2016",
  "A3 2017",
  "A30",
  "A31",
  "A32",
  "A36",
  "A37",
  "A41",
  "A42",
  "A5",
  "A5 2016",
  "A5 2018",
  "A50",
  "A5000",
  "A509DL / A3",
  "A50s / A30s / A50",
  "A52",
  "A52s",
  "A53",
  "A54",
  "A54 4G",
  "A55",
  "A55 4G",
  "A55 Pro",
  "A57 4G 2022",
  "A58",
  "A58 5G/A58X/A78 5G",
  "A58 5G/A78 5G",
  "A59",
  "A5s",
  "A6 Plus",
  "A60",
  "A6000",
  "A7000",
  "A7010",
  "A72",
  "A73",
  "A74",
  "A74 4G",
  "A76",
  "A77 4G 2022",
  "A77 5G",
  "A77 5G 2022",
  "A7X",
  "A8",
  "A8 2018",
  "A80",
  "A85",
  "A9",
  "A9 2018",
  "A91",
  "A92",
  "A96",
  "A96 4G",
  "A96 5G",
  "A98 5G",
  "AX7",
  "Ace 2",
  "Ace Racing",
  "Ada Çayı",
  "AirTag",
  "Alcatel 1",
  "Alcatel 1S",
  "Alcatel 1S 2021",
  "Alcatel 3",
  "Alcatel 3 2019",
  "Alcatel 3 5.5",
  "Alcatel 3V",
  "Alcatel 3X",
  "Alcatel 3X 2019",
  "Alcatel 5",
  "Alcatel 5V",
  "Alcatel A3",
  "Alcatel A3 XL",
  "Alcatel A5 XL",
  "Alcatel A7",
  "Alcatel A7 XL",
  "Alcatel Idol 4",
  "Alcatel Idol 5",
  "Alcatel Idol 6",
  "Alcatel Pop 4",
  "Alcatel U5",
  "Android One 4G",
  "Aquos R8",
  "Asus ROG Phone 3 ZS661KS",
  "Asus ROG Phone II",
  "Asus Zenfone 2",
  "Asus Zenfone 2 Laser ZE601KL",
  "Asus Zenfone 2 ZE551ML",
  "Asus Zenfone 3 Deluxe 570KL",
  "Asus Zenfone 3 Delüxe ZS570KL",
  "Asus Zenfone 3 Laser ZC551KL",
  "Asus Zenfone 3 Max 520TL",
  "Asus Zenfone 3 Max ZC520TL",
  "Asus Zenfone 3 Max ZC553KL",
  "Asus Zenfone 3 ZE552KL",
  "Asus Zenfone 3 Zoom ZE553KL",
  "Asus Zenfone 4 Max ZC520KL",
  "Asus Zenfone 4 Max ZC554KL",
  "Asus Zenfone 4 Selfie ZB553KL",
  "Asus Zenfone 4 Selfie ZD553KL",
  "Asus Zenfone 4 ZE554KL",
  "Asus Zenfone 5 Lite",
  "Asus Zenfone 5 ZE620KL",
  "Asus Zenfone 5z ZS620KL",
  "Asus Zenfone 6",
  "Asus Zenfone Go ZB551KL",
  "Asus Zenfone Go ZB552KL",
  "Asus Zenfone Live ZB501KL",
  "Asus Zenfone Max (M1) ZB555KL",
  "Asus Zenfone Max Plus (M1) ZB570TL",
  "Asus Zenfone Max ZC550KL",
  "Axon 30Ultra 5G",
  "Axon 40 Pro",
  "Açık Gül",
  "BLU Bold N2",
  "BLU G71 Plus",
  "Bison GT2/GT2 Pro",
  "Black Shark 3",
  "Black Shark 4",
  "Black Shark 4 Pro/4S Pro",
  "Black Shark 4/4S",
  "Black Shark 5",
  "Black Shark 5 Pro",
  "BlackBerry PlayBook",
  "BlackBerryKEY2",
  "BlackBerryKeyone",
  "Blackview A95",
  "Blade A52 Lite",
  "Blade A610",
  "Bold 9000",
  "C1",
  "C11",
  "C11 2021",
  "C110 4G",
  "C12",
  "C12 Plus",
  "C15",
  "C2",
  "C20",
  "C21",
  "C21 Plus",
  "C21Y",
  "C22",
  "C25",
  "C25S",
  "C25Y",
  "C3",
  "C30",
  "C30s",
  "C31",
  "C32",
  "C33",
  "C35",
  "C40",
  "C5 Pro",
  "C53 4G",
  "C55",
  "C55 4G",
  "C7",
  "C8",
  "Camon 16 Premier",
  "Camon 18",
  "Camon 18P",
  "Camon 18T",
  "Camon 19",
  "Camon 19 Neo",
  "Camon 19 Pro",
  "Camon 20 4G",
  "Camon 20 Pro 4G",
  "Casper Via A1",
  "Casper Via A1 Plus",
  "Casper Via A3 Plus",
  "Casper Via A4",
  "Casper Via E1",
  "Casper Via E1C",
  "Casper Via E3",
  "Casper Via E30",
  "Casper Via F20",
  "Casper Via G1 Plus",
  "Casper Via G3",
  "Casper Via G4",
  "Casper Via M3",
  "Casper Via M4",
  "Casper Via P3",
  "Casper Via S",
  "Casper Via V10",
  "Casper Via V3",
  "Casper Via V4",
  "Casper Via V5",
  "Casper Via V6",
  "Casper Via X20",
  "Civi 2",
  "Civi 5G",
  "Curve 8320",
  "D900 ile uyumlu",
  "Desire 12",
  "Desire 12 Leather Case",
  "Desire 12 Plus",
  "Desire 12+",
  "Desire 19 Plus",
  "Desire 19+",
  "Desire 20",
  "Desire 20 / Desire 20+",
  "Desire 20 Plus",
  "Desire 20 Pro",
  "Desire 20+",
  "Desire 21 Pro",
  "Desire 22 Pro",
  "Desire 300",
  "Desire 628",
  "Desire 630",
  "Desire 728",
  "Desire 728G",
  "Desire 816",
  "Desire 820",
  "Desire 826",
  "Desire 828",
  "Desire Eye",
  "Discovery",
  "Discovery Elite",
  "Discovery Quadro 4",
  "E10",
  "E22/E22i",
  "E22S/E32",
  "E250 ile uyumlu",
  "E4",
  "E4 Plus",
  "E7",
  "Edge 2022",
  "Edge 30",
  "Edge 30 Lite",
  "Edge 30 Neo",
  "Edge 30 Neo/Edge 30 Lite",
  "Edge 30 Ultra X30 Pro",
  "Edge Plus 2023",
  "Enjoy 50 Pro",
  "F1",
  "F1 Plus",
  "F15",
  "F19",
  "F19 Pro",
  "F2",
  "F22",
  "F3",
  "F3 /F3 SE/F3S",
  "Find X6 Pro 5G",
  "Fujitsu",
  "Fujitsu Arrows 5G F-51A",
  "G 5G",
  "G 5G 2022",
  "G Power 5G",
  "G Power 5G 2023",
  "G Stylus 5G",
  "G Stylus 5G 2022",
  "G100",
  "G11 Plus",
  "G2",
  "G21 / G11",
  "G22",
  "G3",
  "G3 Beat (Mini)",
  "G32",
  "G4",
  "G400",
  "G42 5G",
  "G4C",
  "G5",
  "G5 Plus",
  "G52",
  "G5S Plus",
  "G60",
  "G62",
  "G7",
  "G7 ThinQ",
  "G72",
  "G8",
  "G8S ThinQ",
  "G91",
  "GM 10",
  "GM 20",
  "GM 20 Pro",
  "GM 21",
  "GM 21 New Edition",
  "GM 21 Plus",
  "GM 21 Plus New Edition",
  "GM 21 Pro",
  "GM 21 Pro New Edition",
  "GM 21 Pro d",
  "GM 22",
  "GM 22 Plus",
  "GM 22 Pro",
  "GM 23",
  "GM 4",
  "GM 5",
  "GM 5 Plus",
  "GM 8",
  "GM 8 Go",
  "GM 9",
  "GM 9 Go",
  "GM 9 Pro",
  "GM21",
  "GM21 Plus",
  "GM21 Pro",
  "GM8",
  "GM8 Go",
  "GM9 Pro",
  "GR3",
  "GR5",
  "GT Master Edition",
  "GT Neo 5 SE",
  "GT Neo5 SE",
  "GT2",
  "Galaxy A01",
  "Galaxy A01 Core",
  "Galaxy A02",
  "Galaxy A02s",
  "Galaxy A03",
  "Galaxy A03 Core",
  "Galaxy A03 Pro",
  "Galaxy A03S",
  "Galaxy A04",
  "Galaxy A04S/M13 5G",
  "Galaxy A04e",
  "Galaxy A04s",
  "Galaxy A10",
  "Galaxy A10e",
  "Galaxy A10s",
  "Galaxy A11",
  "Galaxy A12",
  "Galaxy A13",
  "Galaxy A13 4G",
  "Galaxy A13 5G",
  "Galaxy A14",
  "Galaxy A14 4G",
  "Galaxy A14 5G",
  "Galaxy A2 Core",
  "Galaxy A20",
  "Galaxy A20 - A30",
  "Galaxy A20 Pro",
  "Galaxy A20e",
  "Galaxy A20s",
  "Galaxy A21",
  "Galaxy A21s",
  "Galaxy A22",
  "Galaxy A22 4G",
  "Galaxy A22 5G",
  "Galaxy A22e",
  "Galaxy A23",
  "Galaxy A23 4G",
  "Galaxy A23 5G",
  "Galaxy A23 5G / 4G",
  "Galaxy A23e",
  "Galaxy A24",
  "Galaxy A24 4G",
  "Galaxy A25",
  "Galaxy A27",
  "Galaxy A3",
  "Galaxy A3 (2016)",
  "Galaxy A3 2016",
  "Galaxy A3 2017",
  "Galaxy A30",
  "Galaxy A30s",
  "Galaxy A31",
  "Galaxy A32",
  "Galaxy A32 4G",
  "Galaxy A32 5G",
  "Galaxy A33",
  "Galaxy A33 5G",
  "Galaxy A34",
  "Galaxy A34 5G",
  "Galaxy A40",
  "Galaxy A41",
  "Galaxy A42",
  "Galaxy A42 5G",
  "Galaxy A5",
  "Galaxy A5 (2016)",
  "Galaxy A5 2016",
  "Galaxy A5 2017",
  "Galaxy A50",
  "Galaxy A50S",
  "Galaxy A50S Galaxy A30S",
  "Galaxy A50s / A30s / A50",
  "Galaxy A51",
  "Galaxy A52",
  "Galaxy A52 5G",
  "Galaxy A52s",
  "Galaxy A52s 5G",
  "Galaxy A53",
  "Galaxy A53 5G",
  "Galaxy A54",
  "Galaxy A54 5G",
  "Galaxy A6",
  "Galaxy A6 2018",
  "Galaxy A6 Plus",
  "Galaxy A6 Plus 2018",
  "Galaxy A60",
  "Galaxy A6S",
  "Galaxy A7",
  "Galaxy A7 (2016)",
  "Galaxy A7 2016",
  "Galaxy A7 2017",
  "Galaxy A7 2018",
  "Galaxy A70",
  "Galaxy A70s",
  "Galaxy A71",
  "Galaxy A72",
  "Galaxy A72 5G",
  "Galaxy A73",
  "Galaxy A73 5G",
  "Galaxy A74",
  "Galaxy A8",
  "Galaxy A8 (2018)",
  "Galaxy A8 2016",
  "Galaxy A8 2018",
  "Galaxy A8 Plus",
  "Galaxy A8 Plus (2018)",
  "Galaxy A8 Plus 2018",
  "Galaxy A80",
  "Galaxy A81",
  "Galaxy A81 (Note 10 Lite)",
  "Galaxy A82",
  "Galaxy A9",
  "Galaxy A9 (2016)",
  "Galaxy A9 2018",
  "Galaxy A90",
  "Galaxy A91",
  "Galaxy Ace 3",
  "Galaxy Ace 4",
  "Galaxy Alpha",
  "Galaxy C5",
  "Galaxy C5 Pro",
  "Galaxy C7",
  "Galaxy C7 Pro",
  "Galaxy C7010 C7 Pro",
  "Galaxy C8",
  "Galaxy C9 Pro",
  "Galaxy Core",
  "Galaxy Core 2",
  "Galaxy Core Prime",
  "Galaxy E5",
  "Galaxy E7",
  "Galaxy F02S",
  "Galaxy F04/M04",
  "Galaxy F12",
  "Galaxy F14",
  "Galaxy F14 5G",
  "Galaxy F41",
  "Galaxy F52",
  "Galaxy F52 5G",
  "Galaxy F62",
  "Galaxy G530",
  "Galaxy Grand 9082",
  "Galaxy Grand Duos",
  "Galaxy Grand Prime",
  "Galaxy Grand Prime Pro",
  "Galaxy J1",
  "Galaxy J1 Ace",
  "Galaxy J1 Mini Prime",
  "Galaxy J2",
  "Galaxy J2 Core",
  "Galaxy J2 Prime",
  "Galaxy J2 Pro",
  "Galaxy J2 Pro 2018",
  "Galaxy J3",
  "Galaxy J3 Pro",
  "Galaxy J4",
  "Galaxy J4 Plus",
  "Galaxy J5",
  "Galaxy J5 2016",
  "Galaxy J5 Prime",
  "Galaxy J5 Pro",
  "Galaxy J6",
  "Galaxy J6 Plus",
  "Galaxy J7",
  "Galaxy J7 2015",
  "Galaxy J7 2016",
  "Galaxy J7 Core",
  "Galaxy J7 Duo",
  "Galaxy J7 Max",
  "Galaxy J7 Prime",
  "Galaxy J7 Prime 2",
  "Galaxy J7 Pro",
  "Galaxy J730 Pro",
  "Galaxy J8",
  "Galaxy M01",
  "Galaxy M01 Core",
  "Galaxy M02",
  "Galaxy M04",
  "Galaxy M10",
  "Galaxy M10s",
  "Galaxy M11",
  "Galaxy M12",
  "Galaxy M13",
  "Galaxy M13 5G",
  "Galaxy M14",
  "Galaxy M14 5G",
  "Galaxy M20",
  "Galaxy M21",
  "Galaxy M21S",
  "Galaxy M22",
  "Galaxy M23",
  "Galaxy M23 5G",
  "Galaxy M24",
  "Galaxy M30",
  "Galaxy M30s",
  "Galaxy M31",
  "Galaxy M31s",
  "Galaxy M32",
  "Galaxy M33",
  "Galaxy M33 5G",
  "Galaxy M34",
  "Galaxy M40",
  "Galaxy M51",
  "Galaxy M52",
  "Galaxy M52 5G",
  "Galaxy M53",
  "Galaxy M53 5G",
  "Galaxy M54",
  "Galaxy M54 5G",
  "Galaxy M62",
  "Galaxy Note 10",
  "Galaxy Note 10 Lite",
  "Galaxy Note 10 Plus",
  "Galaxy Note 2",
  "Galaxy Note 20",
  "Galaxy Note 20 5G",
  "Galaxy Note 20 Ultra",
  "Galaxy Note 20 Ultra 5G",
  "Galaxy Note 22 Plus",
  "Galaxy Note 22 Ultra",
  "Galaxy Note 3",
  "Galaxy Note 3 Neo",
  "Galaxy Note 4",
  "Galaxy Note 4 Edge",
  "Galaxy Note 5",
  "Galaxy Note 7",
  "Galaxy Note 8",
  "Galaxy Note 9",
  "Galaxy Note FE",
  "Galaxy On 5",
  "Galaxy On 7",
  "Galaxy On5",
  "Galaxy On7",
  "Galaxy Quantum 2",
  "Galaxy S10",
  "Galaxy S10 Lite",
  "Galaxy S10 Plus",
  "Galaxy S10 Pro",
  "Galaxy S10e",
  "Galaxy S20",
  "Galaxy S20 FE",
  "Galaxy S20 Lite",
  "Galaxy S20 Plus",
  "Galaxy S20 Ultra",
  "Galaxy S21",
  "Galaxy S21 5G",
  "Galaxy S21 FE",
  "Galaxy S21 FE 5G",
  "Galaxy S21 Plus",
  "Galaxy S21 Ultra",
  "Galaxy S21 Ultra 5G",
  "Galaxy S21+",
  "Galaxy S22",
  "Galaxy S22 5G",
  "Galaxy S22 FE",
  "Galaxy S22 Plus",
  "Galaxy S22 Plus 5G",
  "Galaxy S22 Pro",
  "Galaxy S22 Ultra",
  "Galaxy S22 Ultra 5G",
  "Galaxy S22+ 5G",
  "Galaxy S23",
  "Galaxy S23 5G",
  "Galaxy S23 FE",
  "Galaxy S23 Plus",
  "Galaxy S23 Plus 5G",
  "Galaxy S23 Ultra",
  "Galaxy S23 Ultra 5G",
  "Galaxy S23+",
  "Galaxy S3",
  "Galaxy S3 Mini",
  "Galaxy S30",
  "Galaxy S30 Plus",
  "Galaxy S30 Ultra",
  "Galaxy S4",
  "Galaxy S4 Mini",
  "Galaxy S5",
  "Galaxy S5 Mini",
  "Galaxy S6",
  "Galaxy S6 Edge",
  "Galaxy S6 Edge Plus",
  "Galaxy S7",
  "Galaxy S7 Edge",
  "Galaxy S72",
  "Galaxy S8",
  "Galaxy S8 Plus",
  "Galaxy S9",
  "Galaxy S9 Plus",
  "Galaxy S9 Pro",
  "Galaxy W21",
  "Galaxy Win",
  "Galaxy Xcover 4s",
  "Galaxy Xcover 5",
  "Galaxy Xcover 6 Pro",
  "Galaxy Xcover Pro",
  "Galaxy Xcover Pro 2",
  "Galaxy Z Filp 3 5G",
  "Galaxy Z Flip",
  "Galaxy Z Flip 3",
  "Galaxy Z Flip 4",
  "Galaxy Z Flip 4 5G",
  "Galaxy Z Flip 5",
  "Galaxy Z Flip 5 5G",
  "Galaxy Z Flip3 5g",
  "Galaxy Z Flip5",
  "Galaxy Z Fold 2",
  "Galaxy Z Fold 3",
  "Galaxy Z Fold 3 5G",
  "Galaxy Z Fold 4",
  "Galaxy Z Fold 4 5G",
  "Galaxy Z Fold 5",
  "Galaxy Z Fold 5 5G",
  "Galaxy i8190",
  "GalaxyA23 5G /  4G",
  "General Mobile Discovery 2",
  "General Mobile Discovery 2 Mini",
  "General Mobile Discovery Air",
  "General Mobile Discovery E3",
  "General Mobile Discovery Elite E7",
  "General Mobile Discovery Elite Plus",
  "General Mobile GM 10",
  "General Mobile GM 20 Pro",
  "General Mobile GM 21 New Edition",
  "General Mobile GM 21 Plus New Edition",
  "General Mobile GM 21 Pro New Edition",
  "General Mobile GM 23 SE",
  "General Mobile GM 6",
  "Gionee S6 Pro",
  "Gm 21 D",
  "Gm5 Plus",
  "Google Pixel 6",
  "Google Pixel 6 Pro",
  "Google Pixel 7 5G",
  "Google Pixel 7A",
  "Grand Prime",
  "Grand Prime Plus",
  "Grand X",
  "HTC Bolt",
  "HTC Cha Cha G16",
  "HTC Desire 10",
  "HTC Desire 10 Pro",
  "HTC Desire 12",
  "HTC Desire 12 Plus",
  "HTC Desire 320",
  "HTC Desire 500",
  "HTC Desire 510",
  "HTC Desire 516",
  "HTC Desire 526",
  "HTC Desire 530",
  "HTC Desire 610",
  "HTC Desire 616",
  "HTC Desire 620",
  "HTC Desire 626",
  "HTC Desire 820",
  "HTC Desire 825",
  "HTC Desire 830",
  "HTC Nova",
  "HTC One A9",
  "HTC One E9",
  "HTC One M7",
  "HTC One M8 Mini",
  "HTC U Play",
  "HTC U Ultra",
  "HTC U11",
  "HTC U11 Life",
  "HTC U11 Lite",
  "Harmony 4",
  "Honor 10",
  "Honor 10 Lite",
  "Honor 20",
  "Honor 20 Lite",
  "Honor 50",
  "Honor 50 SE",
  "Honor 6X",
  "Honor 70",
  "Honor 70 Pro",
  "Honor 7A",
  "Honor 7S",
  "Honor 8",
  "Honor 80",
  "Honor 80 5G",
  "Honor 80 Pro",
  "Honor 80 Pro 5G",
  "Honor 80 SE",
  "Honor 80 SE 5G",
  "Honor 8A",
  "Honor 8X",
  "Honor 9",
  "Honor 90 5G",
  "Honor 90 Lite 5G",
  "Honor 90 Pro 5G",
  "Honor 9X",
  "Honor 9X Lite / 8X",
  "Honor Magic 4 Pro",
  "Honor Magic4 Lite",
  "Honor Magic5",
  "Honor Magic5 Pro",
  "Honor Play",
  "Honor Play 4 Pro",
  "Honor Play 40 Plus",
  "Honor Play 6C",
  "Honor View 20",
  "Honor X40",
  "Honor X5",
  "Honor X5 4G",
  "Honor X50i",
  "Honor X6 / X8 5G",
  "Honor X7",
  "Honor X7A",
  "Honor X8",
  "Honor X8 4G",
  "Honor X8 5G",
  "Honor X8A",
  "Honor X9a",
  "Honor X9a 5G",
  "Hot 10",
  "Hot 10T",
  "Hot 11 2022",
  "Hot 11 Play",
  "Hot 11S",
  "Hot 12",
  "Hot 12 Play",
  "Hot 20 4G",
  "Hot 20 Play",
  "Hot 20S",
  "Hot 20i",
  "Hot 30 4G",
  "Hot 30 Play",
  "Hot 30i",
  "Hot 8",
  "Hot 9",
  "Huawei Ascend G610",
  "Huawei Ascend G7",
  "Huawei Ascend G700",
  "Huawei Ascend Mate 7",
  "Huawei Ascend P1",
  "Huawei Ascend P6",
  "Huawei Ascend P7",
  "Huawei Ascend Y600",
  "Huawei G9",
  "Huawei GR3 2017",
  "Huawei GR5 2017",
  "Huawei Honor 10",
  "Huawei Honor 20 Lite",
  "Huawei Honor 7",
  "Huawei Honor 7C",
  "Huawei Honor 7X",
  "Huawei Honor 8",
  "Huawei Honor 8C",
  "Huawei Honor 8X",
  "Huawei Honor 9 Lite",
  "Huawei Honor GT3",
  "Huawei Honor Play",
  "Huawei Honor Y6 II",
  "Huawei Honro View 20",
  "Huawei Mate 10",
  "Huawei Mate 10 Pro",
  "Huawei Mate 20",
  "Huawei Mate 30 Lite",
  "Huawei Mate 30 Pro",
  "Huawei Mate 40 Pro",
  "Huawei Mate 9",
  "Huawei Nova",
  "Huawei Nova 10 Pro",
  "Huawei Nova 10 SE",
  "Huawei Nova 10z",
  "Huawei Nova 11i",
  "Huawei Nova 6 5G",
  "Huawei Nova 9",
  "Huawei Nova Y61",
  "Huawei P Smart Z",
  "Huawei P10 Lite",
  "Huawei P20",
  "Huawei P20 Lite 2019",
  "Huawei P20 Pro",
  "Huawei P40",
  "Huawei P40 Lite 5G",
  "Huawei P50",
  "Huawei P60",
  "Huawei P60 Pro",
  "Huawei P8 Max",
  "Huawei P9",
  "Huawei P9 Lite",
  "Huawei P9 Lite 2017",
  "Huawei P9 Lite Mini",
  "Huawei Y6 2019",
  "Huawei Y6 Pro",
  "Huawei Y7",
  "Huawei Y7 Prime",
  "Huawei Y9 2019",
  "IQOO Z7i",
  "Infinix Hot 12i",
  "Infinix Hot 20",
  "Infinix Note 30 5g",
  "Infinix Note 7",
  "Infinix Note10",
  "Infinix Oppo Reno 5 Lite",
  "Infinix Zero 8",
  "Inifinix Hot 10 Play",
  "Intouch 3",
  "Intouch 4",
  "J1",
  "J2",
  "J2 Pro 2018",
  "J6",
  "J6 Plus",
  "J7 2016",
  "J7 Core",
  "J7 Max",
  "J7 Prime",
  "K10 5G",
  "K13 Pro",
  "K20",
  "K31",
  "K40S",
  "K41S / K51S",
  "K5",
  "K50 Pro",
  "K50S",
  "K51",
  "K51 / Q51",
  "K61",
  "K61 / Q61",
  "K8",
  "K9S",
  "Kaan",
  "L Bello",
  "L40",
  "L760 İle uyumlu",
  "L80",
  "L90",
  "LG AKA",
  "LG G Flex",
  "LG G Flex 2",
  "LG G Pro Lite",
  "LG G2 Mini",
  "LG G3 Stylus",
  "LG G4 Beat",
  "LG G4 Stylus",
  "LG G5",
  "LG G6",
  "LG G7 ThinQ",
  "LG K10 2017",
  "LG K11",
  "LG K20 2019",
  "LG K40",
  "LG K41S",
  "LG K51S",
  "LG K61",
  "LG K7",
  "LG K8",
  "LG K8 2017",
  "LG K9",
  "LG L Fino",
  "LG L7 II P710",
  "LG L70",
  "LG L80",
  "LG L9 P880",
  "LG Leon",
  "LG Optimus L5",
  "LG Optimus L5 2",
  "LG Q Stylus",
  "LG Q60",
  "LG Q7",
  "LG Stylus 2",
  "LG Stylus 3",
  "LG V20",
  "LG V30",
  "LG X Cam",
  "LG X Power",
  "LG X Screen",
  "LG X Style",
  "LG Zero",
  "Lenovo A1000",
  "Lenovo A2010",
  "Lenovo A2020",
  "Lenovo A536",
  "Lenovo A6010",
  "Lenovo A7010",
  "Lenovo K3",
  "Lenovo K3 Note",
  "Lenovo K5 Note",
  "Lenovo K6",
  "Lenovo K6 Note",
  "Lenovo Moto E4",
  "Lenovo Moto E4 Plus",
  "Lenovo Moto G4",
  "Lenovo Moto G4 Plus",
  "Lenovo Moto G5",
  "Lenovo Moto G5 Plus",
  "Lenovo Moto G5S Plus",
  "Lenovo Moto Z",
  "Lenovo Moto Z Play",
  "Lenovo Moto Z2 Play",
  "Lenovo P11",
  "Lenovo P11 Pro",
  "Lenovo P2",
  "Lenovo Vibe K5",
  "Lenovo Vibe S1 Lite",
  "Lg K10",
  "Lg K4",
  "Lg Q6",
  "Lumia 540",
  "Lumia 950",
  "M10",
  "M11",
  "M12",
  "M21",
  "M24 5G",
  "M3",
  "M30S",
  "M32",
  "M34 5G",
  "M4 Pro 4G",
  "M5",
  "M51",
  "M52",
  "M53",
  "M54 5G",
  "M7",
  "M8",
  "M8 Mini",
  "M9",
  "MX4 Pro",
  "MX5",
  "Mate 10 Lite",
  "Mate 10 Pro",
  "Mate 20 Lite",
  "Mate 20 Pro",
  "Mate 20 X",
  "Mate 20X",
  "Mate 30",
  "Mate 30 Lite",
  "Mate 30 Pro",
  "Mate 40 Pro",
  "Mate 40 Pro Plus",
  "Mate 50 Pro",
  "Mate 8",
  "Mate S",
  "Mate X2",
  "Mate XS 2",
  "MatePad T8",
  "Meizu 15",
  "Meizu 16",
  "Meizu 16T",
  "Meizu 16X",
  "Meizu 16XS",
  "Meizu M10",
  "Meizu M3 Note",
  "Meizu M5",
  "Meizu M5S",
  "Meizu M6",
  "Meizu M6S",
  "Meizu M6T",
  "Meizu Mx5",
  "Meizu Note 8",
  "Meizu Note 9",
  "Meizu Pro 6",
  "Meizu U10",
  "Meizu U20",
  "Meizu X8",
  "Mi 10",
  "Mi 10 Lite",
  "Mi 10 Pro",
  "Mi 10T",
  "Mi 10T - Mi 10T Pro",
  "Mi 10T 5G",
  "Mi 10T Lite 5G",
  "Mi 10T Pro",
  "Mi 10T Pro 5G",
  "Mi 11",
  "Mi 11 Lite",
  "Mi 11 Lite 5G",
  "Mi 11 Pro",
  "Mi 11 Ultra",
  "Mi 11T",
  "Mi 11T Pro",
  "Mi 11i",
  "Mi 12",
  "Mi 12 Lite",
  "Mi 12 Pro",
  "Mi 12T",
  "Mi 12T Pro",
  "Mi 13",
  "Mi 13 Lite",
  "Mi 13 Pro",
  "Mi 4",
  "Mi 5",
  "Mi 6",
  "Mi 6X",
  "Mi 8",
  "Mi 8 Lite",
  "Mi 8 SE",
  "Mi 9",
  "Mi 9 Lite",
  "Mi 9 SE",
  "Mi 9T",
  "Mi 9T Pro",
  "Mi A1",
  "Mi A2",
  "Mi A2 Lite",
  "Mi A3",
  "Mi Max 3",
  "Mi Mix 3",
  "Mi Note 10",
  "Mi Note 10 Lite",
  "Mi Note 3",
  "Mi Play",
  "Mi5 Pro",
  "Mi6",
  "Mix 4",
  "Mobile GM 21",
  "Mobile GM 21 d",
  "Moto E20 / E30 / E40",
  "Moto E7 Power / E7i Power",
  "Moto Edge 40 5G",
  "Moto Edge 40 Pro",
  "Moto Edge Plus",
  "Moto Edge Plus 2023",
  "Moto G 5G 2022",
  "Moto G 5G 2023",
  "Moto G 5G/One 5G Ace",
  "Moto G10",
  "Moto G20",
  "Moto G30",
  "Moto G5S",
  "Moto X40",
  "Moto X40 Pro",
  "Moto Z",
  "Motorola Moto Edge S / G100",
  "Motorola Moto G22",
  "Motorola Moto G50 4G",
  "Motorola Moto G52",
  "Mİ 10T Lite",
  "Nexus 5",
  "Nexus 6",
  "Nokia 2",
  "Nokia 2.2",
  "Nokia 3",
  "Nokia 3.1 C",
  "Nokia 3.2",
  "Nokia 3310",
  "Nokia 5",
  "Nokia 5.1 Plus",
  "Nokia 6",
  "Nokia 7 Plus",
  "Nokia 7.1",
  "Nokia 7210",
  "Nokia 8",
  "Nokia G20",
  "Nokia Lumia 535",
  "Nokia Lumia 540",
  "Nokia Lumia 630",
  "Nokia Lumia 640",
  "Nokia Lumia 650",
  "Nokia Lumia 735",
  "Nokia Lumia 950",
  "Nokia Lumia 950 XL",
  "Nokia Lumia XL",
  "Nokia X6",
  "Nord 10",
  "Nord CE 2 Lite",
  "Nord CE 2 Lite 5G",
  "Nord CE 3",
  "Nord CE 3 5G / CE 3 Lite 5G",
  "Nord CE3 Lite",
  "Nord Ce 2",
  "Nord N100",
  "Nord N20 SE",
  "Nord N20 SE 4G",
  "Nord N300",
  "Not 7P",
  "Note 1",
  "Note 10",
  "Note 10 Pro",
  "Note 11",
  "Note 11 Global",
  "Note 11 Pro",
  "Note 11E",
  "Note 11S",
  "Note 12 G88",
  "Note 12 Pro",
  "Note 12 VIP",
  "Note 12i",
  "Note 3",
  "Note 4",
  "Note 5",
  "Note 5 A",
  "Note 7",
  "Note 7 Lite",
  "Note 8",
  "Note 8i",
  "Note 9S/9 Pro",
  "Nothing Phone 1",
  "Nothing Phone 2",
  "Nova 10",
  "Nova 10 Pro",
  "Nova 10 SE",
  "Nova 11",
  "Nova 11 4G",
  "Nova 11 Pro",
  "Nova 11 Pro 4G",
  "Nova 11 Ultra",
  "Nova 11 Ultra 4G",
  "Nova 2i",
  "Nova 3i",
  "Nova 5T",
  "Nova 8i",
  "Nova 9",
  "Nova 9 SE",
  "Nova Plus",
  "Nova Y70",
  "Nova Y90",
  "Nubia Red Magic 7",
  "Nubia Red Magic 7 Pro",
  "Nubia Red Magic 7S",
  "Nubia Red Magic 7s Pro",
  "Nubia Red Magic 8 Pro",
  "Nubia Z50 Ultra",
  "OPPO A15",
  "OPPO A15S",
  "OPPO A31",
  "OPPO A5 2020",
  "OPPO A52",
  "OPPO A5S",
  "OPPO A73",
  "OPPO A9",
  "OPPO A9 2020",
  "Omix",
  "Omix X300",
  "Omix X500",
  "Omix X600 Nfc",
  "On7",
  "One",
  "One M8",
  "One M8s",
  "One M9",
  "One M9 Plus",
  "One Max",
  "One Plus 10 Pro",
  "One Plus 5",
  "One Plus 8T",
  "One Plus 9",
  "One Plus 9 Pro",
  "One Plus Nord N10",
  "One S",
  "One X",
  "One X10",
  "One X9",
  "OnePlus 10T",
  "OnePlus 10T 5G",
  "OnePlus 11",
  "OnePlus 5",
  "OnePlus 5T",
  "OnePlus 7T",
  "OnePlus 8 Pro",
  "OnePlus 9",
  "OnePlus 9 Pro",
  "OnePlus 9R",
  "OnePlus Ace 2V",
  "OnePlus Ace Pro",
  "OnePlus Nord 2T 5G",
  "OnePlus Nord 3",
  "OnePlus Nord N10",
  "OnePlus Nord N10 5G",
  "OnePlus Nord N100",
  "OnePlus Nord N200 5G",
  "Oppo A1 Pro",
  "Oppo A12",
  "Oppo A16",
  "Oppo A17",
  "Oppo A36",
  "Oppo A5",
  "Oppo A53",
  "Oppo A53 2020",
  "Oppo A53S",
  "Oppo A54",
  "Oppo A54 4G",
  "Oppo A55",
  "Oppo A55 4G",
  "Oppo A55 5G",
  "Oppo A57",
  "Oppo A72",
  "Oppo A74",
  "Oppo A74 4G",
  "Oppo A7X",
  "Oppo A91",
  "Oppo A92",
  "Oppo A94",
  "Oppo A95",
  "Oppo Find X2",
  "Oppo Find X6",
  "Oppo Find X6 Pro",
  "Oppo R15X",
  "Oppo RX17 Neo",
  "Oppo RX17 Pro",
  "Oppo Reno",
  "Oppo Reno 10X Zoom",
  "Oppo Reno 2",
  "Oppo Reno 2Z",
  "Oppo Reno 3",
  "Oppo Reno 4",
  "Oppo Reno 4 Lite",
  "Oppo Reno 4 Pro",
  "Oppo Reno 4 Pro 4G",
  "Oppo Reno 4 Pro 5G",
  "Oppo Reno 5",
  "Oppo Reno 5 5G",
  "Oppo Reno 5 Lite",
  "Oppo Reno 5 Pro",
  "Oppo Reno 5 Pro 5G",
  "Oppo Reno 6",
  "Oppo Reno 6 4G",
  "Oppo Reno Z",
  "Oppo Reno8 5G",
  "Oppo Reno8 Lite",
  "Oppo Reno8 T 4G",
  "Oppo Reno8 T 5G",
  "Oppo Reno9",
  "Oscal C30",
  "Oscal C30 Pro",
  "Oscal C80",
  "Oukitel C32",
  "P Smart",
  "P Smart 2017",
  "P Smart 2018",
  "P Smart 2019",
  "P Smart 2020",
  "P Smart 2021",
  "P Smart Plus",
  "P Smart Pro",
  "P Smart Pro 2019",
  "P Smart S",
  "P-Smart",
  "P1",
  "P10",
  "P10 Lite",
  "P10 Plus",
  "P10 Ultra",
  "P10S",
  "P11",
  "P11S",
  "P13 Blue",
  "P13 Blue 2021",
  "P13 Blue 2022",
  "P13 Blue Max",
  "P13 Blue Max 2020",
  "P13 Blue Max 2021",
  "P13 Blue Max 2022",
  "P13 Blue Max L 2021",
  "P13 Blue Max L 2022",
  "P13 Blue Max Lite",
  "P13 Blue Max Pro",
  "P13 Blue Max Pro 2021",
  "P13 Blue Max Pro Lite",
  "P13 Blue Plus",
  "P13 Blue Plus 2022",
  "P13 Max Lite",
  "P13 Max Pro",
  "P1M",
  "P20",
  "P20 Lite",
  "P20 Pro",
  "P30",
  "P30 Lite",
  "P30 Pro",
  "P40",
  "P40 Lite",
  "P40 Lite E",
  "P40 Pro",
  "P50 Pro",
  "P60 / P60 Pro",
  "P60 Art",
  "P8",
  "P8 Lite",
  "POCO F1",
  "POP 7 Pro",
  "Pearl 8100",
  "Pearl Flip 8230",
  "Phone1",
  "Pixel 4 XL",
  "Pixel 4A",
  "Pixel 5A",
  "Pixel 6",
  "Pixel 6 Pro",
  "Pixel 8",
  "Pixel 8 Pro",
  "Play",
  "Play 30 Plus",
  "Poco C3",
  "Poco C31",
  "Poco C40",
  "Poco C50",
  "Poco C51",
  "Poco F2",
  "Poco F2 Pro",
  "Poco F3",
  "Poco F4",
  "Poco F4 GT",
  "Poco F5",
  "Poco F5 5G",
  "Poco F5 Pro 5G",
  "Poco M3",
  "Poco M3 Pro",
  "Poco M3 Pro 5G",
  "Poco M4",
  "Poco M4 5G",
  "Poco M4 Pro",
  "Poco M4 Pro 4G",
  "Poco M4 Pro 5G",
  "Poco M5",
  "Poco M5 4G",
  "Poco M5S",
  "Poco M6 Pro",
  "Poco X2",
  "Poco X3",
  "Poco X3 GT",
  "Poco X3 NFC",
  "Poco X3 Pro",
  "Poco X4 GT",
  "Poco X4 NFC",
  "Poco X4 Pro",
  "Poco X4 Pro 5G",
  "Poco X5",
  "Poco X5 5G",
  "Poco X5 Pro",
  "Pocophone F1",
  "Pop 4S",
  "Pova",
  "Pova 3",
  "Pova Neo 2",
  "Pova Neo 3",
  "Pova Neo 4",
  "Power 7/7S",
  "Q60",
  "Q7",
  "Q70",
  "R17",
  "R9 Plus",
  "R9 Ultra",
  "R9S Ultra",
  "ROG Phone 3",
  "ROG Phone 5 Ultimate",
  "ROG Phone 5/Phone 5s",
  "ROG Phone 6",
  "ROG Phone 6 Pro",
  "ROG Phone 7",
  "RX17 Neo",
  "RX17 Pro",
  "Realme 10",
  "Realme 11 Pro",
  "Realme 11 Pro Plus",
  "Realme 5",
  "Realme 5 Pro",
  "Realme 5S",
  "Realme 5i",
  "Realme 6",
  "Realme 6 Pro",
  "Realme 6i",
  "Realme 7",
  "Realme 7 Pro",
  "Realme 8",
  "Realme 8 Pro",
  "Realme 9 Pro",
  "Realme C11",
  "Realme C11 2021",
  "Realme C15",
  "Realme C2",
  "Realme C2 2020",
  "Realme C21",
  "Realme C21Y",
  "Realme C25",
  "Realme C25S",
  "Realme C3",
  "Realme C31",
  "Realme C3i",
  "Realme C55",
  "Realme GT",
  "Realme GT Master Edition",
  "Realme GT Neo 5",
  "Realme GT2 Explorer Master",
  "Realme XT",
  "Reame 6i",
  "Red Mi Note 6 / Note 6 Pro",
  "Redmi 10",
  "Redmi 10 2022",
  "Redmi 10 5G",
  "Redmi 10A",
  "Redmi 10C",
  "Redmi 11 Prime",
  "Redmi 12",
  "Redmi 12C",
  "Redmi 3 Pro",
  "Redmi 4",
  "Redmi 4A",
  "Redmi 4X",
  "Redmi 5",
  "Redmi 5 Plus",
  "Redmi 5A",
  "Redmi 6",
  "Redmi 6 Pro",
  "Redmi 6A",
  "Redmi 7",
  "Redmi 7A",
  "Redmi 8",
  "Redmi 8A",
  "Redmi 8t",
  "Redmi 9",
  "Redmi 9 Prime",
  "Redmi 9 Pro",
  "Redmi 9A",
  "Redmi 9C",
  "Redmi 9T",
  "Redmi 9i Sport",
  "Redmi 9s",
  "Redmi A1",
  "Redmi A1 4G",
  "Redmi A1 Plus",
  "Redmi A1+ Plus",
  "Redmi A2",
  "Redmi A2 Plus",
  "Redmi Go",
  "Redmi K30",
  "Redmi K30 Pro",
  "Redmi K30S",
  "Redmi K40",
  "Redmi K40 Gaming",
  "Redmi K40 Pro",
  "Redmi K40S",
  "Redmi K50",
  "Redmi K50 Pro",
  "Redmi K60",
  "Redmi K60/K60 Pro",
  "Redmi K60E",
  "Redmi Note 10",
  "Redmi Note 10 5G",
  "Redmi Note 10 Pro",
  "Redmi Note 10 Pro Max",
  "Redmi Note 10T",
  "Redmi Note 10s",
  "Redmi Note 11",
  "Redmi Note 11 5G",
  "Redmi Note 11 Pro",
  "Redmi Note 11 Pro 4G",
  "Redmi Note 11 Pro 5G",
  "Redmi Note 11 Pro Plus",
  "Redmi Note 11E",
  "Redmi Note 11R",
  "Redmi Note 11S",
  "Redmi Note 11T",
  "Redmi Note 11T 5G",
  "Redmi Note 11T Pro 5G",
  "Redmi Note 11T Pro+ Plus",
  "Redmi Note 12",
  "Redmi Note 12 5G",
  "Redmi Note 12 Pro",
  "Redmi Note 12 Plus",
  "Redmi Note 12 Pro 4G",
  "Redmi Note 12 Pro 5G",
  "Redmi Note 12 Pro Plus",
  "Redmi Note 12 Pro+",
  "Redmi Note 12 Pro+ 5G",
  "Redmi Note 12 Turbo",
  "Redmi Note 12S",
  "Redmi Note 12S 4G",
  "Redmi Note 12T Pro",
  "Redmi Note 3",
  "Redmi Note 4",
  "Redmi Note 4X",
  "Redmi Note 5",
  "Redmi Note 5 Pro",
  "Redmi Note 5A",
  "Redmi Note 6 Pro",
  "Redmi Note 7",
  "Redmi Note 7 Pro",
  "Redmi Note 8",
  "Redmi Note 8 Pro",
  "Redmi Note 8T",
  "Redmi Note 9",
  "Redmi Note 9 4G",
  "Redmi Note 9 5G",
  "Redmi Note 9 Pro",
  "Redmi Note 9 Pro 5G",
  "Redmi Note 9 Pro Max",
  "Redmi Note 9S",
  "Redmi Note 9S; Note 9 Pro",
  "Redmi Note 9T",
  "Redmi S2",
  "Reeder P10",
  "Reeder P13",
  "Reeder P13 Blue Max 128 Gb",
  "Reeder P13 Blue Max Pro Lite",
  "Reeder P13 Blue Max Pro Lite 2022",
  "Reno 10 5G",
  "Reno 10 Pro 5G",
  "Reno 10 Pro Plus 5G",
  "Reno 10X",
  "Reno 2",
  "Reno 2Z",
  "Reno 3",
  "Reno 3 Pro",
  "Reno 3 Pro 5G",
  "Reno 4",
  "Reno 4 Lite",
  "Reno 4 Pro",
  "Reno 4 Pro 5G",
  "Reno 5",
  "Reno 5 5G",
  "Reno 5 Lite",
  "Reno 5 Pro",
  "Reno 6",
  "Reno 6 Pro",
  "Reno 7",
  "Reno 7 4G",
  "Reno 7 4G/F21 Pro 4G",
  "Reno 7 Lite",
  "Reno 7 Lite 5G",
  "Reno 7Z 5G",
  "Reno 8 4G",
  "Reno 8Z 5G",
  "Reno2 Z",
  "Reno3 Pro",
  "Reno4 Lite",
  "Reno4 Pro",
  "Reno8 Pro 5G",
  "Reno9 5G",
  "Reno9 Pro 5G",
  "Reno9 Pro+ Plus",
  "S1",
  "S10",
  "S10 Plus",
  "S10E",
  "S12 Pro",
  "S15 5G",
  "S15 Pro 5G/V25 Pro 5G",
  "S16/S16 Pro",
  "S16E/V27E",
  "S16e",
  "S17",
  "S17E 5G",
  "S19 Max",
  "S19 Max Pro",
  "S20",
  "S20 Lite",
  "S20 Plus",
  "S21",
  "S21 FE",
  "S21 Fan",
  "S21 Ultra",
  "S22",
  "S22 Ultra",
  "S23 Pro Max",
  "S3 Mini",
  "S5",
  "S5 Mini",
  "S60",
  "S60T",
  "S7",
  "S9",
  "S90",
  "SE",
  "Samsung Galaxy A03S",
  "Samsung Galaxy A04E",
  "Samsung Galaxy A13",
  "Samsung Galaxy A13 4G",
  "Samsung Galaxy A20E",
  "Samsung Galaxy A23",
  "Samsung Galaxy A23/F23",
  "Samsung Galaxy A30 JP",
  "Samsung Galaxy A32 5G",
  "Samsung Galaxy A33 5G",
  "Samsung Galaxy A42",
  "Samsung Galaxy A5 2017",
  "Samsung Galaxy A60",
  "Samsung Galaxy A70S",
  "Samsung Galaxy A8 2016",
  "Samsung Galaxy A80",
  "Samsung Galaxy Ace Plus S7500",
  "Samsung Galaxy Ace S5830",
  "Samsung Galaxy C5",
  "Samsung Galaxy C7 Pro",
  "Samsung Galaxy C9 Pro",
  "Samsung Galaxy Corby 2 S3850",
  "Samsung Galaxy Core 2",
  "Samsung Galaxy Core Prime G360",
  "Samsung Galaxy Core i8260",
  "Samsung Galaxy E250",
  "Samsung Galaxy Gio S5660",
  "Samsung Galaxy Grand 2",
  "Samsung Galaxy Grand Max",
  "Samsung Galaxy J1 2016",
  "Samsung Galaxy J1 Mini",
  "Samsung Galaxy J1 Mini Prime",
  "Samsung Galaxy J3 2017",
  "Samsung Galaxy J330 Pro",
  "Samsung Galaxy J4 Core",
  "Samsung Galaxy J5 2016",
  "Samsung Galaxy J5 2017",
  "Samsung Galaxy J5 Pro",
  "Samsung Galaxy J7 2017",
  "Samsung Galaxy J7 Pro",
  "Samsung Galaxy M10S",
  "Samsung Galaxy M13",
  "Samsung Galaxy M22",
  "Samsung Galaxy M32",
  "Samsung Galaxy M40",
  "Samsung Galaxy M53 5G",
  "Samsung Galaxy Mega",
  "Samsung Galaxy Mini S5570",
  "Samsung Galaxy Note",
  "Samsung Galaxy Note 7",
  "Samsung Galaxy Note Edge",
  "Samsung Galaxy S Advance İ9070",
  "Samsung Galaxy S Duos S7562",
  "Samsung Galaxy S İ9000",
  "Samsung Galaxy S2",
  "Samsung Galaxy S21 FE 5G",
  "Samsung Galaxy S22",
  "Samsung Galaxy S22 Plus",
  "Samsung Galaxy S22 Ultra",
  "Samsung Galaxy S23 Plus",
  "Samsung Galaxy S23 Ultra",
  "Samsung Galaxy S3350",
  "Samsung Galaxy S3600",
  "Samsung Galaxy S4 Zoom",
  "Samsung Galaxy S5230 Star",
  "Samsung Galaxy S7 Edge",
  "Samsung Galaxy S7 Plus",
  "Samsung Galaxy S8",
  "Samsung Galaxy S8 Plus",
  "Samsung Galaxy Wave 2 S8530",
  "Samsung Galaxy Wave S5253",
  "Samsung Galaxy Wave S7233",
  "Samsung Galaxy Wave S8500",
  "Samsung Galaxy Win i8552",
  "Samsung Galaxy Wonder İ8150",
  "Samsung Galaxy Xcover 4",
  "Samsung Galaxy Xcover Pro",
  "Samsung Galaxy Y S5360",
  "Samsung Galaxy Z Flip",
  "Samsung Galaxy Z Fold 2",
  "Samsung Galaxy Z Fold 3",
  "Samsung Galaxy Z Fold3 5G",
  "Se 3 2022",
  "Shine Lite",
  "Smart 6",
  "Smart 6 Plus",
  "Smart 7",
  "Smart 7 HD",
  "Smart 7 Plus",
  "Smart S",
  "Smart Style 7",
  "Sony Xperia 1 IV",
  "Sony Xperia 10 IV",
  "Sony Xperia 5 IV",
  "Sony Xperia Ace III",
  "Sony Xperia C5",
  "Sony Xperia C5 Ultra",
  "Sony Xperia E4",
  "Sony Xperia E4G",
  "Sony Xperia E5",
  "Sony Xperia Go",
  "Sony Xperia P",
  "Sony Xperia Sola",
  "Sony Xperia T2",
  "Sony Xperia T3",
  "Sony Xperia X",
  "Sony Xperia X Compact",
  "Sony Xperia X1",
  "Sony Xperia XA",
  "Sony Xperia XA Ultra",
  "Sony Xperia XA1",
  "Sony Xperia XA1 Plus",
  "Sony Xperia XA1 Ultra",
  "Sony Xperia XZ Premium",
  "Sony Xperia XZ2",
  "Sony Xperia Z",
  "Sony Xperia Z1 Compact",
  "Sony Xperia Z3 Compact",
  "Spark 10 4G",
  "Spark 10 Pro",
  "Spark 10C",
  "Spark 16",
  "Spark 6 Go",
  "Spark 7 Pro",
  "Spark 7T",
  "Spark 8 Pro",
  "Spark 8C",
  "Spark 8T",
  "Spark 9 Pro",
  "Style 3 L-41",
  "Stylo 6",
  "Sunny3",
  "T 50",
  "T10",
  "T50",
  "T60",
  "T70",
  "TCL 10 Plus",
  "TCL 10 SE",
  "TCL 10L",
  "TCL 20 SE",
  "TCL 201",
  "TCL 20E",
  "TCL 20L Plus",
  "TCL 20Y",
  "TCL 30 Plus",
  "TCL 30 SE",
  "TCL 30 SE/306/305 / Sharp Aqous V6/V6 Plus",
  "TCL 304",
  "TCL 40 XE 5G/TCL 40X 5G",
  "TCL 403",
  "TCL Ion X",
  "TCL L7",
  "TT175",
  "Tecno Camon 16",
  "Tecno Camon 16 Premier",
  "Tecno Camon 17 Pro",
  "Tecno Camon 19 Pro 5g",
  "Tecno Oppo Reno 4 Pro",
  "Tecno Pova",
  "Tecno Pova 3",
  "Tecno Pova 4",
  "Tecno Pova 5",
  "Tecno Pova Neo",
  "Tecno Spark 10",
  "Tecno Spark 4 Lite",
  "Tecno Spark 6",
  "Tecno Spark 6 GO",
  "Tecno Spark 7",
  "Tecno Spark 7T",
  "Tecno Spark Go 2023",
  "Tecno Techo Camon 16",
  "Turkcell T20",
  "Turkcell T80",
  "Turkcell Turkcell T10",
  "Turkcell Turkcell T21",
  "U11",
  "U11 Life",
  "U12 Life",
  "U12+",
  "U19E",
  "U20 5G",
  "U600 ile uyumlu",
  "UMIDIGI A7S",
  "Ulefone Note 10",
  "Ulefone Note 9P",
  "Umi Touch",
  "V10",
  "V23 5G",
  "V25 5G/V25E",
  "V27/V27 Pro",
  "V3 5020",
  "V3 5040",
  "V3 5570",
  "V3 5580",
  "V30",
  "V30 5G/V30T",
  "V30S",
  "V50",
  "V60 ThinQ 5G",
  "Velvet",
  "Venüs 5000",
  "Venüs E2",
  "Venüs E5",
  "Venüs GO",
  "Venüs V3 5000",
  "Venüs V3 5020",
  "Venüs V3 5040",
  "Venüs V5",
  "Venüs Z10",
  "Venüs Z20",
  "Venüs Z40",
  "Vestel E3",
  "Vestel Venüs 5.0V",
  "Vestel Venüs 5.0X",
  "Vestel Venüs 5.5V",
  "Vestel Venüs 5.5X",
  "Vestel Venüs 5530",
  "Vestel Venüs E2 Plus",
  "Vestel Venüs E4",
  "Vestel Venüs E5",
  "Vestel Venüs Go",
  "Vestel Venüs V3 5010",
  "Vestel Venüs V3 5070",
  "Vestel Venüs V3 5580",
  "Vestel Venüs V4",
  "Vestel Venüs V6",
  "Vestel Venüs V7",
  "Vestel Venüs Z20",
  "Vestel Venüs Z30",
  "Via A2",
  "Via A3",
  "Via E2",
  "Via E30",
  "Via E4",
  "Via F1",
  "Via F2",
  "Via F20",
  "Via F3",
  "Via G1",
  "Via G5",
  "Via M1",
  "Via M2",
  "Via P1",
  "Via P2",
  "Via V5",
  "Via V6X",
  "Via V8",
  "Via V8C",
  "Via V9",
  "Via X20",
  "Vibe K5 Plus",
  "Vibe K6 Power",
  "Vibe P1",
  "Vibe P1M",
  "Vibe X2 Pro",
  "Vivo",
  "Vivo V20E",
  "Vivo V21",
  "Vivo V21E",
  "Vivo V29",
  "Vivo V29 Lite",
  "Vivo X60 Pro",
  "Vivo Y100",
  "Vivo Y11s",
  "Vivo Y16",
  "Vivo Y20",
  "Vivo Y20s",
  "Vivo Y21S",
  "Vivo Y32",
  "Vivo Y33S",
  "Vivo Y35",
  "Vivo Y51",
  "Vivo Y70",
  "Vodafone N8",
  "Vodafone Smart 6 Prime",
  "Vodafone Smart 6 Ultra",
  "Vodafone Smart 7",
  "Vodafone Smart 7 Pro",
  "Vodafone Smart 7 Ultra",
  "Vodafone V8",
  "Vodofone 7",
  "Voix",
  "WP16",
  "WP19",
  "WP20",
  "X",
  "X100",
  "X2",
  "X3",
  "X3 GT",
  "X3 NFC",
  "X3 Pro",
  "X30",
  "X30 Pro/Edge 30 Ultra",
  "X300",
  "X40",
  "X40/X40 Pro",
  "X400",
  "X5",
  "X500",
  "X600",
  "X700",
  "X90 5G",
  "X9A",
  "X9A 5G",
  "XR",
  "XS",
  "XS Max",
  "Xiaomi 11T",
  "Xiaomi 12 Lite",
  "Xiaomi 12T/12T Pro",
  "Xiaomi 13",
  "Xiaomi 13 Lite",
  "Xiaomi 13 Pro",
  "Xiaomi 13 Ultra",
  "Xiaomi Mi 10",
  "Xiaomi Mi 10 5G",
  "Xiaomi Mi 10 Pro",
  "Xiaomi Mi 10 Ultra",
  "Xiaomi Mi 10C",
  "Xiaomi Mi 10T / 10T Pro",
  "Xiaomi Mi 11",
  "Xiaomi Mi 11 Ultra",
  "Xiaomi Mi 11T 5G",
  "Xiaomi Mi 11T Pro 5G",
  "Xiaomi Mi 5s",
  "Xiaomi Mi 5s Plus",
  "Xiaomi Mi 5x",
  "Xiaomi Mi 6X",
  "Xiaomi Mi 8 Pro",
  "Xiaomi Mi 9 Se",
  "Xiaomi Mi A3",
  "Xiaomi Mi Max",
  "Xiaomi Mi Max 2",
  "Xiaomi Mi Max 3",
  "Xiaomi Mi Mix",
  "Xiaomi Mi Mix 2",
  "Xiaomi Mi Mix 2S",
  "Xiaomi Mi Mix 4",
  "Xiaomi Mi Note 10 Pro",
  "Xiaomi Mi Note 11S",
  "Xiaomi Mi Note 2",
  "Xiaomi Mi Pad 5",
  "Xiaomi Mİ 4C",
  "Xiaomi Note 8 Pro",
  "Xiaomi Poco C40",
  "Xiaomi Poco M3",
  "Xiaomi Poco M3 Pro",
  "Xiaomi Poco M4 Pro 5G",
  "Xiaomi Poco X3 GT",
  "Xiaomi Red Mi 10 Prime+ 5G/Red Mi Note 11E",
  "Xiaomi Red Mi 10A",
  "Xiaomi Red Mi 10C 4G Global",
  "Xiaomi Red Mi K30",
  "Xiaomi Red Mi K40S",
  "Xiaomi Red Mi Note 11 4G / Note 11S",
  "Xiaomi Red Mi Note 8",
  "Xiaomi Red Mi Note 9 Pro",
  "Xiaomi Red Mi Note 9 Pro 5G",
  "Xiaomi Red Mi Note 9 Pro Max",
  "Xiaomi Redmi 10",
  "Xiaomi Redmi 12C",
  "Xiaomi Redmi 3 Pro",
  "Xiaomi Redmi 3s",
  "Xiaomi Redmi 4",
  "Xiaomi Redmi 4A",
  "Xiaomi Redmi 4x",
  "Xiaomi Redmi 5",
  "Xiaomi Redmi 5A",
  "Xiaomi Redmi Go",
  "Xiaomi Redmi K20",
  "Xiaomi Redmi Note 10 5G",
  "Xiaomi Redmi Note 11",
  "Xiaomi Redmi Note 11 Pro",
  "Xiaomi Redmi Note 11T Pro+ 5G",
  "Xiaomi Redmi Note 12",
  "Xiaomi Redmi Note 12 4G",
  "Xiaomi Redmi Note 4x",
  "Xiaomi Redmi Pro",
  "Xiaomi Redmi Y1 Lite",
  "Xperia 1 V 2023",
  "Xperia 10 V 2023",
  "Xperia C3",
  "Xperia C4",
  "Xperia L1",
  "Xperia L2",
  "Xperia M2",
  "Xperia M4",
  "Xperia M5",
  "Xperia T3",
  "Xperia XA2",
  "Xperia XA2 Ultra",
  "Xperia XZ",
  "Xperia XZ1",
  "Xperia Z1",
  "Xperia Z2",
  "Xperia Z3",
  "Xperia Z4",
  "Xperia Z5",
  "Xperia Z5 Mini (Compact)",
  "Xperia Z5 Premium",
  "Y01",
  "Y02 4G",
  "Y02 4G/Y02A/Y11 2023",
  "Y02S 4G",
  "Y10 4G",
  "Y11S",
  "Y11s/Y12s/Y20s",
  "Y15A/Y10/Y01/IQOO U5X",
  "Y15S",
  "Y16",
  "Y16 4G",
  "Y16 4G/Y02S 4G",
  "Y21",
  "Y21A",
  "Y21E",
  "Y22",
  "Y22/Y22S",
  "Y22s",
  "Y31",
  "Y31 2021",
  "Y32",
  "Y320",
  "Y33S",
  "Y35",
  "Y35 4G 2022",
  "Y35 5G/Y53T",
  "Y35S",
  "Y36",
  "Y36 4G",
  "Y36 5G",
  "Y5 2018",
  "Y5 2019",
  "Y51",
  "Y51A",
  "Y53S",
  "Y55s 5G",
  "Y5C",
  "Y5p",
  "Y6",
  "Y6 2018",
  "Y6 2019",
  "Y6 Prime",
  "Y6 Pro 2019",
  "Y6S 2019",
  "Y6p",
  "Y6s",
  "Y7 2018",
  "Y7 2019",
  "Y7 Prime 2019",
  "Y76 5G",
  "Y76s",
  "Y77 5G",
  "Y78 5G",
  "Y7p",
  "Y8p",
  "Y9 Prime 2019",
  "Y9 Prime 2020",
  "Z Flip",
  "Z Flip3",
  "Z Fold 5",
  "Z Fold3",
  "Z1",
  "Z10",
  "Z2",
  "Z2 Pro",
  "Z3",
  "Z4",
  "ZMax",
  "ZTE A610 Plus",
  "ZTE Axon 11 5G",
  "ZTE Axon 30 Pro 5G",
  "ZTE Axon 7",
  "ZTE Axon 7 Mini",
  "ZTE Blade A910",
  "ZTE Blade V7",
  "ZTE Blade V7 Lite",
  "ZTE Blade V9",
  "ZTE Libero 5G",
  "Zenfone 2",
  "Zenfone 2 Laser ZE500KL",
  "Zenfone 2 Laser ZE550KL",
  "Zenfone 3",
  "Zenfone 4",
  "Zenfone 4 (5.5'') ZE554KL",
  "Zenfone 4 Max (5.5'') ZC554KL",
  "Zenfone 5",
  "Zenfone 6",
  "Zenfone Go ZC500TG",
  "Zenfone Laser ZE500KL",
  "Zenfone Laser ZE550KL",
  "Zenfone Max Pro M1 ZB602KL 6.0",
  "Zenfone Max Pro ZB602KL",
  "Zenfone Selfie ZD551KL",
  "Zero 20",
  "Zero 8",
  "Zero X Pro",
  "Zte Blade V30 Vita",
  "htc 626",
  "iPhone",
  "iPhone 11",
  "iPhone 11 Pro",
  "iPhone 11 Pro Max",
  "iPhone 12",
  "iPhone 12 Max",
  "iPhone 12 Mini",
  "iPhone 12 Pro",
  "iPhone 12 Pro Max",
  "iPhone 12 Pro Mini",
  "iPhone 13",
  "iPhone 13 Mini",
  "iPhone 13 Pro",
  "iPhone 13 Pro Max",
  "iPhone 14",
  "iPhone 14 Max",
  "iPhone 14 Plus",
  "iPhone 14 Pro",
  "iPhone 14 Pro Max",
  "iPhone 15",
  "iPhone 15 Plus",
  "iPhone 15 Pro",
  "iPhone 15 Pro Max",
  "iPhone 15 Ultra",
  "iPhone 4",
  "iPhone 4S",
  "iPhone 5",
  "iPhone 5 / 5s",
  "iPhone 5 5S",
  "iPhone 5S",
  "iPhone 6",
  "iPhone 6 / 6S",
  "iPhone 6 Plus",
  "iPhone 6 Plus - 6S Plus",
  "iPhone 6 Plus / 6S Plus",
  "iPhone 6/ 6S",
  "iPhone 6/6S",
  "iPhone 6Plus/ 7Plus/ 8Plus",
  "iPhone 6S",
  "iPhone 6S Plus",
  "iPhone 7",
  "iPhone 7 / 8",
  "iPhone 7 Plus",
  "iPhone 7/8",
  "iPhone 7/8 Plus",
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone Max",
  "iPhone SE",
  "iPhone SE 2",
  "iPhone SE 2020",
  "iPhone SE 2022",
  "iPhone SE 3 2022",
  "iPhone X",
  "iPhone X / XS",
  "iPhone X/XS",
  "iPhone XR",
  "iPhone XR 6.1",
  "iPhone XS",
  "iPhone XS MaiPhone X",
  "iPhone XS Max",
  "iPhone XS Max 6.5",
  "vivo S16e",
  "İdol 3",
  "İnfinix Hot 10",
  "İnfinix Hot 8",
  "İnfinix Hot 9",
  "İnfinix Note 10",
  "İnfinix Note 11 Pro",
  "İnfinix Smart 5",
  "İphone 6 - 6S",
] as const;

/**
 * @CategoryName Telefon > Cep Telefonu Aksesuarları > Kılıflar
 * @Field Renk
 * @Optional
 */
export const PhoneCase_Colors = [
  "Siyah",
  "Beyaz",
  "Pembe",
  "Pudra",
  "Pudra Pembe",
  "Mor",
  "Lila",
  "Mavi",
  "Su Yeşili",
  "Turkuaz",

  "Gold",
  "Gümüş",
  "Rose",

  "Simli",
  "Renkli",
  "Renksiz",

  // ---
  "Altın",
  "--",
  "41S-Sarı",
  "50P-Pembe",
  "Abanoz",
  "Ahşap",
  "Ahşap Rengi",
  "Alp Yeşili",
  "Altın",
  "Altın - Beyaz",
  "Altın - Gri",
  "Altın - Gül",
  "Altın - Gümüş",
  "Altın - Koyu Pembe",
  "Altın - Kırmızı",
  "Altın - Lila",
  "Altın - Mavi",
  "Altın - Pembe",
  "Altın - Sarı",
  "Altın - Siyah",
  "Altın - Yeşil",
  "Altın Dore",
  "Altın Pembe",
  "Antik Beyaz",
  "Antrasit",
  "Antrasit - Gri",
  "Asker Yeşili",
  "Askeri Kamuflaj",
  "Azure",
  "Açık Bej",
  "Açık Bordo",
  "Açık Cam Göbeği",
  "Açık Gri",
  "Açık Gümüş",
  "Açık Kahverengi",
  "Açık Kahverengi - Siyah",
  "Açık Kahverengi - Yeşil",
  "Açık Kırmızı",
  "Açık Lacivert",
  "Açık Lila",
  "Açık Mavi",
  "Açık Mavi - Kırmızı",
  "Açık Mavi - Lacivert",
  "Açık Mavi - Mavi",
  "Açık Mavi - Mor",
  "Açık Mavi - Rose",
  "Açık Mor",
  "Açık Mor - Mor",
  "Açık Mor - Pembe",
  "Açık Mor - Siyah",
  "Açık Mor - Yeşil",
  "Açık Mürdüm",
  "Açık Pembe",
  "Açık Pembe - Beyaz",
  "Açık Pembe - Koyu Yeşil",
  "Açık Pembe - Yeşil",
  "Açık Sarı",
  "Açık Siyah",
  "Açık Turkuaz",
  "Açık Turuncu",
  "Açık Vişne",
  "Açık Yeşil",
  "Açık Yeşil - Mor",
  "Açık Yeşil - Siyah",
  "Açık Yeşil - Turuncu",
  "Açık Yeşil - Yeşil",
  "Açık Yeşil Kamuflaj",
  "Bakır",
  "Bal Rengi",
  "Baltık Mavisi",
  "Bebek Mavisi",
  "Bej",
  "Bej - Gri",
  "Bej - Mavi",
  "Bej - Pembe",
  "Bej - Sarı",
  "Beril",
  "Berry",
  "Beyaz - Altın - Siyah",
  "Beyaz - Fuşya",
  "Beyaz - Gri",
  "Beyaz - Gümüş",
  "Beyaz - Kahverengi",
  "Beyaz - Kırmızı",
  "Beyaz - Kırmızı - Siyah",
  "Beyaz - Lacivert",
  "Beyaz - Mavi",
  "Beyaz - Mavi - Altın",
  "Beyaz - Mavi - Siyah",
  "Beyaz - Mor",
  "Beyaz - Mor - Siyah",
  "Beyaz - Pembe",
  "Beyaz - Sarı",
  "Beyaz - Siyah",
  "Beyaz - Taba",
  "Beyaz - Turkuaz - Fuşya",
  "Beyaz - Turuncu",
  "Beyaz - Yeşil",
  "Beyaz Ahşap",
  "Beyaz Karbon",
  "Beyaz-Turuncu",
  "Beyaz-Yeşil",
  "Black",
  "BlackBerry",
  "Blue",
  "Blue Cobalt",
  "Blush Gold",
  "Bodro",
  "Bordo",
  "Bordo - Siyah",
  "Bronz",
  "Bronz - Altın",
  "Bronz - Gümüş",
  "Brown",
  "Buz Mavisi",
  "Buzlu Beyaz",
  "Buzlu Mavi",
  "Buzlu Siyah",
  "Buzlu Şeffaf",
  "CS Siyah",
  "Calypso Blue",
  "Cam",
  "Cam Göbeği",
  "Camel",
  "Cat",
  "Champagne Gold",
  "Charcoal Black",
  "Ciassic Siyah",
  "Clear",
  "Cocoa",
  "Copper Gold",
  "Crystal Clear",
  "Dallar",
  "Dark Olive",
  "Dark Silver",
  "Dark yeşil",
  "Darling Pink",
  "Deep Blue",
  "Deniz Kabuğu",
  "Deniz Mavisi",
  "Deniz Mavisi - Gri",
  "Deniz Yıldızı",
  "Deri",
  "Derin Mavi",
  "Derin Mor",
  "Desenli",
  "Duman Gri",
  "Edge Glow Pink",
  "Eflatun",
  "Eflatun - Mavi",
  "Ekru",
  "Ekru - Mor",
  "Ekru - Pembe",
  "Elegant Yeşil",
  "Erik Çiçeği Rengi",
  "Eski Harita Eyfel",
  "Eyfel Kule",
  "Flamingo",
  "Fosfor Sarı",
  "Fosfor Yeşili",
  "Fosforlu Yeşil - Siyah",
  "Fuşya",
  "Füme",
  "Füme - Pembe",
  "Fıstık Yeşili",
  "Gece Mavisi",
  "Gece Siyahı",
  "Gece Yeşili",
  "Gerbera Pembesi",
  "Glossy Finish Blue",
  "Glossy Finish Clear",
  "Glossy Finish Purple",
  "Glossy Finish Red",
  "Gold - Koyu Pembe",
  "Gold - Kırmızı",
  "Gold-Siyah",
  "Gold1",
  "Gray",
  "Gri",
  "Gri - Altın",
  "Gri - Açık Mavi",
  "Gri - Beyaz",
  "Gri - Fuşya",
  "Gri - Gold",
  "Gri - Kahverengi",
  "Gri - Kırmızı",
  "Gri - Mavi",
  "Gri - Pembe",
  "Gri - Pembe sistemde tanımlı bir ürün tipi değeri değildir.",
  "Gri - Pudra",
  "Gri - Pudra sistemde tanımlı bir ürün tipi değeri değildir.",
  "Gri - Rose - Altın",
  "Gri - Rose Gold",
  "Gri - Siyah",
  "Gri - Turkuaz",
  "Gri - Yeşil",
  "Gri - Yeşil - Pembe",
  "Gri Kamuflaj",
  "Gri-Lacivert",
  "Gri-Siyah",
  "Gunmetal",
  "Gök Mavisi",
  "Gök Mavisi - Mor",
  "Gökkuşağı",
  "Gökyüzü Mavisi",
  "Gökyüzü Mavisi - Mor",
  "Göl Mavi",
  "Göl Mavisi",
  "Göl Yeşili",
  "Gül Kurusu",
  "Gül Pembesi",
  "Gül Rengi",
  "Gümüş - Altın",
  "Gümüş - Beyaz",
  "Gümüş - Gri",
  "Gümüş - Kırmızı",
  "Gümüş - Mavi",
  "Gümüş - Pembe",
  "Gümüş - Sarı",
  "Gümüş - Siyah",
  "Gümüş - Yeşil",
  "Gümüş Gri",
  "Gümüş Rose Gold",
  "Gümüş Rose Siyah",
  "Gümüş-Siyah",
  "Hafif Siyah",
  "Haki",
  "Haki - Sarı",
  "Haki - Siyah",
  "Haki Yeşil",
  "Hardal",
  "Hava Mavisi",
  "Hot Lips Pink",
  "Hot Pink",
  "Jean Blue",
  "Jean Mavi",
  "Jelly Beyaz",
  "Jelly Gri",
  "Jelly Kahverengi",
  "Jelly Mavi",
  "Jelly Pembe",
  "Jelly Siyah",
  "Jelly Turuncu",
  "Jelly Yeşil",
  "Kahve",
  "Kahverengi",
  "Kahverengi - Altın",
  "Kahverengi - Beyaz",
  "Kahverengi - Gri",
  "Kahverengi - Kırmızı",
  "Kahverengi - Sarı",
  "Kahverengi - Siyah",
  "Kahverengi - Turuncu",
  "Kahverengi - Yeşil",
  "Kalp",
  "Kamelya",
  "Kamuflaj",
  "Kavuniçi",
  "Kayısı Rengi",
  "Kemik",
  "Kiraz Çiçeği",
  "Kiremit",
  "Kiss Red",
  "Klasik Kahve",
  "Klasik Kahverengi",
  "Klop Black",
  "Klop Brown",
  "Koyu Bej",
  "Koyu Füme",
  "Koyu Gold",
  "Koyu Gri",
  "Koyu Gri - Sarı",
  "Koyu Gri - Siyah",
  "Koyu Gümüş",
  "Koyu Kahve",
  "Koyu Kahverengi",
  "Koyu Kahverengi - Altın",
  "Koyu Kahverengi - Sarı",
  "Koyu Kırmızı",
  "Koyu Kızıl",
  "Koyu Lacivert",
  "Koyu Lila",
  "Koyu Mavi",
  "Koyu Mavi - Gümüş",
  "Koyu Mavi - Koyu Pembe",
  "Koyu Mavi - Mor",
  "Koyu Mavi - Siyah",
  "Koyu Mor",
  "Koyu Pembe",
  "Koyu Pembe - Altın",
  "Koyu Pembe - Açık Mavi",
  "Koyu Pembe - Koyu Mavi",
  "Koyu Pembe - Mavi",
  "Koyu Pembe - Mor",
  "Koyu Pembe - Siyah",
  "Koyu Sarı",
  "Koyu Siyah",
  "Koyu Turkuaz",
  "Koyu Turuncu",
  "Koyu Yeşil",
  "Koyu Yeşil - Kırmızı",
  "Koyu Yeşil - Siyah",
  "Kraliyet Mavisi",
  "Krem",
  "Krem - Sarı",
  "Krem - Siyah",
  "Krem Ahşap",
  "Krem Rengi",
  "Kristal Mavi",
  "Krom",
  "Kulübe",
  "Kum Pembe",
  "Kumral",
  "Kuşlu",
  "Köknar Yeşili",
  "Kömür",
  "Kömür Grisi",
  "Kömür Rengi",
  "Körfez Mavisi",
  "Kül Gri",
  "Kül Rengi",
  "Kırmızı",
  "Kırmızı - Açık Gri",
  "Kırmızı - Bej",
  "Kırmızı - Beyaz",
  "Kırmızı - Gri",
  "Kırmızı - Gül Rengi",
  "Kırmızı - Gümüş",
  "Kırmızı - Haki",
  "Kırmızı - Kahverengi",
  "Kırmızı - Kırmızı",
  "Kırmızı - Lacivert",
  "Kırmızı - Mavi",
  "Kırmızı - Mor",
  "Kırmızı - Pembe",
  "Kırmızı - Rose Gold",
  "Kırmızı - Sarı",
  "Kırmızı - Siyah",
  "Kırmızı - Turkuaz",
  "Kırmızı - Turuncu",
  "Kırmızı - Yeşil",
  "Kırmızı - Şeffaf",
  "Kırmızı Kamuflaj",
  "Kırmızı1",
  "Kırık Beyaz",
  "Kızıl",
  "Lacivert",
  "Lacivert - Altın",
  "Lacivert - Bordo",
  "Lacivert - Gri",
  "Lacivert - Kahverengi",
  "Lacivert - Koyu Yeşil",
  "Lacivert - Krem",
  "Lacivert - Kırmızı",
  "Lacivert - Mavi",
  "Lacivert - Mavi sistemde tanımlı bir ürün tipi değeri değildir.",
  "Lacivert - Mor",
  "Lacivert - Pembe",
  "Lacivert - Pembe sistemde tanımlı bir ürün tipi değeri değildir.",
  "Lacivert - Pudra",
  "Lacivert - Pudra sistemde tanımlı bir ürün tipi değeri değildir.",
  "Lacivert - Sarı",
  "Lacivert - Siyah",
  "Lacivert - Yeşil",
  "Lacivert-Siyah",
  "Lavanta",
  "Lavanta Grisi",
  "Lavender Purple",
  "Leopar",
  "Leylak",
  "Leylak Moru",
  "Light Silver",
  "Lila - Açık Mavi",
  "Lila - Bej",
  "Lila - Beyaz",
  "Lila - Beyaz - Kırmızı",
  "Lila - Kırmızı",
  "Lila - Mavi",
  "Lila - Mavi - Beyaz",
  "Lila - Mavi - Kırmızı",
  "Lila - Mor",
  "Lila - Pembe",
  "Lila - Siyah",
  "Lila - Turuncu",
  "Limon Sarısı",
  "Limon Yeşili",
  "Marine Green",
  "Mat",
  "Mat Beyaz",
  "Mat Sarı",
  "Mat Siyah",
  "Mat Turuncu",
  "Mat Şeffaf",
  "Matcha Yeşili",
  "Matte Finish Black",
  "Mavi - Altın",
  "Mavi - Beyaz",
  "Mavi - Fuşya",
  "Mavi - Füme",
  "Mavi - Gold",
  "Mavi - Gri",
  "Mavi - Gök Mavisi",
  "Mavi - Gül",
  "Mavi - Gümüş",
  "Mavi - Haki",
  "Mavi - Kahverengi",
  "Mavi - Koyu Pembe",
  "Mavi - Krem",
  "Mavi - Kırmızı",
  "Mavi - Mavi",
  "Mavi - Mor",
  "Mavi - Pembe",
  "Mavi - Rose",
  "Mavi - Sarı",
  "Mavi - Siyah",
  "Mavi - Turuncu",
  "Mavi - Yeşil",
  "Mavi - Şeffaf",
  "Mavi Kamuflaj",
  "Mavi-Pembe",
  "Menekşe",
  "Mercan",
  "Metal",
  "Metalik Altın",
  "Metalik Gümüş",
  "Metalik Koyu Mavi",
  "Metalik Kırmızı",
  "Metalik Lacivert",
  "Metalik Mavi",
  "Metalik Mor",
  "Metalik Sarı",
  "Metalik Siyah",
  "Metalik Yeşil",
  "Midnight Blue",
  "Mint",
  "Mint Yeşili",
  "Mint Yeşili - Kırmızı",
  "Monaco Blue",
  "Mor - Altın",
  "Mor - Açık Pembe",
  "Mor - Açık Yeşil",
  "Mor - Bej",
  "Mor - Beyaz",
  "Mor - Gri",
  "Mor - Gül",
  "Mor - Gümüş",
  "Mor - Koyu Mavi",
  "Mor - Kırmızı",
  "Mor - Lacivert",
  "Mor - Mavi",
  "Mor - Mavi - Kırmızı",
  "Mor - Pembe",
  "Mor - Pembe - Beyaz",
  "Mor - Rose",
  "Mor - Sarı",
  "Mor - Siyah",
  "Mor - Turkuaz",
  "Mor - Turuncu",
  "Mor - Yeşil",
  "Mor - Yeşil - Turuncu",
  "Mor1",
  "Mykonos Blue",
  "Mürdüm",
  "Nane Yeşil - Beyaz",
  "Nane Yeşil - Mor",
  "Nane Yeşili",
  "Nar",
  "Nar Çiçeği",
  "Nefti Yeşil",
  "Neon Absinthe Green",
  "Neon Calypso Blue",
  "Neon Hot Lips Pink",
  "Neon Kırmızı",
  "Neon Lightning Yellow",
  "Neon Menekşe",
  "Neon Orchid Purple",
  "Neon Pembe",
  "Neon Sarı",
  "Neon Sunrise Pink",
  "Neon Turuncu",
  "Newyork Taksi",
  "Nickel Grey",
  "Nokia",
  "Ocean Blue",
  "Okyanus Mavisi",
  "Orchid Purple",
  "Ordu Yeşili",
  "Ordu Yeşili - Turuncu",
  "Orman Yeşili",
  "Papatya",
  "Paris",
  "Parlak Gümüş",
  "Parlak Sarı",
  "Parlak Siyah",
  "Parlak Şeffaf",
  "Parlament Mavi",
  "Pastel Kırmızı",
  "Pastel Pembe",
  "Pastel Sarı",
  "Pastel Yeşil",
  "Pebble",
  "Pembe - Altın",
  "Pembe - Açık Mavi",
  "Pembe - Açık Mor",
  "Pembe - Açık Yeşil",
  "Pembe - Bej",
  "Pembe - Beyaz",
  "Pembe - Beyaz - Mor",
  "Pembe - Fuşya",
  "Pembe - Gri",
  "Pembe - Gök Mavisi",
  "Pembe - Gökyüzü Mavisi",
  "Pembe - Gül",
  "Pembe - Gümüş",
  "Pembe - Kahverengi",
  "Pembe - Koyu Kırmızı",
  "Pembe - Kırmızı",
  "Pembe - Lacivert",
  "Pembe - Lila",
  "Pembe - Mavi",
  "Pembe - Mor",
  "Pembe - Mor - Altın",
  "Pembe - Sarı",
  "Pembe - Siyah",
  "Pembe - Turkuaz",
  "Pembe - Turuncu",
  "Pembe - Yeşil",
  "Pembe - Şarap Kırmızısı",
  "Pembe - Şeffaf",
  "Pembe Neon",
  "Pembe-Siyah",
  "Pembe-Yeşil",
  "Petrol",
  "Petrol Mavisi",
  "Petrol Yeşili",
  "Petrol Yeşili - Altın",
  "Pink Sand",
  "Platin Gri - Altın",
  "Platin Gri - Gümüş",
  "Portakal",
  "Red",
  "Retro Yeşil",
  "Rose - Açık Mavi",
  "Rose - Gold",
  "Rose - Kırmızı",
  "Rose - Mavi",
  "Rose - Mor",
  "Rose - Sarı",
  "Rose - Siyah",
  "Rose Crystal",
  "Rose Gold",
  "Rose Gold - Pembe",
  "Rose Gold-Siyah",
  "Rose Gri",
  "Rose Pembe",
  "Rose Red",
  "Rose Siyah",
  "Royal Mavi",
  "Rugged Armor",
  "S Şeffaf",
  "Sade",
  "Safir",
  "Safir Mavisi",
  "Safir Mavisi - Siyah",
  "Saks",
  "Saks Mavi",
  "Sap Yeşili",
  "Sapphire",
  "Sarı",
  "Sarı - Beyaz",
  "Sarı - Kahverengi",
  "Sarı - Kırmızı",
  "Sarı - Lacivert",
  "Sarı - Lila",
  "Sarı - Mavi",
  "Sarı - Mor",
  "Sarı - Mor - kırmızı",
  "Sarı - Pembe",
  "Sarı - Siyah",
  "Sarı - Turuncu",
  "Sarı - Yeşil",
  "Sarı 319850",
  "Saydam",
  "Sea Blue",
  "Seffaf Beyaz",
  "Shine Gold",
  "Sierra Mavisi",
  "Silver",
  "Simli Şeffaf",
  "Siyah - Altın",
  "Siyah - Açık Kırmızı",
  "Siyah - Açık Mavi",
  "Siyah - Beyaz",
  "Siyah - Beyaz - Gri",
  "Siyah - Bordo",
  "Siyah - Fuşya",
  "Siyah - Gold",
  "Siyah - Gri",
  "Siyah - Gül",
  "Siyah - Gümüş",
  "Siyah - Kahverengi",
  "Siyah - Koyu Kırmızı",
  "Siyah - Koyu Mavi",
  "Siyah - Koyu Yeşil",
  "Siyah - Kırmızı",
  "Siyah - Lacivert",
  "Siyah - Mavi",
  "Siyah - Mor",
  "Siyah - Pembe",
  "Siyah - Pembe - Altın",
  "Siyah - Rose",
  "Siyah - Rose - Altın",
  "Siyah - Rose Gold",
  "Siyah - Rosegold",
  "Siyah - Sarı",
  "Siyah - Silver",
  "Siyah - Siyah",
  "Siyah - Turkuaz",
  "Siyah - Turkuvaz",
  "Siyah - Turuncu",
  "Siyah - Yeşil",
  "Siyah - Şarap Kırmızısı",
  "Siyah - Şeffaf",
  "Siyah Büyük Pencere",
  "Siyah Gri",
  "Siyah Hası",
  "Siyah Kamuflaj",
  "Siyah Karbon",
  "Siyah Kömür",
  "Siyah Melanj",
  "Siyah Mermer",
  "Siyah-Pembe",
  "Somon",
  "Somon Rengi",
  "Stand Black",
  "Stand Gold",
  "Stand Rose",
  "Stand White",
  "Steel Silver",
  "Stone",
  "Sıcak Pembe",
  "TAN",
  "Taba",
  "Taba - Siyah",
  "Taksim Tramvay",
  "Taupe",
  "Taş",
  "Taş - Beyaz",
  "Tekne",
  "Telefon Kulübesi",
  "Tennis Ball Green",
  "Ticket",
  "Titanium",
  "Titanyum",
  "Titanyum Gri",
  "Totem",
  "Toz Pembe",
  "Transparan",
  "Turkuaz - Beyaz",
  "Turkuaz - Beyaz - Açık Pembe",
  "Turkuaz - Beyaz - Yeşil",
  "Turkuaz - Fuşya",
  "Turkuaz - Gri",
  "Turkuaz - Kırmızı",
  "Turkuaz - Pembe",
  "Turkuaz - Turuncu",
  "Turkuvaz",
  "Turkuvaz - Mavi",
  "Turuncu",
  "Turuncu - Bej",
  "Turuncu - Beyaz",
  "Turuncu - Beyaz - Yeşil",
  "Turuncu - Gri",
  "Turuncu - Kırmızı",
  "Turuncu - Lacivert",
  "Turuncu - Mavi",
  "Turuncu - Mor",
  "Turuncu - Sarı",
  "Turuncu - Siyah",
  "Turuncu - Turkuaz - Mavi",
  "Turuncu - Yeşil",
  "Turuncu Kamuflaj",
  "Ultra Crystal",
  "Ultra Violet",
  "Uzay Grisi",
  "Violet",
  "Vizon",
  "Vişne Çürüğü",
  "White",
  "Wild Salmon Pink",
  "Wine",
  "Yavruağzı",
  "Yelkenli",
  "Yeşil",
  "Yeşil - Altın",
  "Yeşil - Bej",
  "Yeşil - Beyaz",
  "Yeşil - Gri",
  "Yeşil - Gümüş",
  "Yeşil - Haki",
  "Yeşil - Koyu Gri",
  "Yeşil - Koyu Yeşil",
  "Yeşil - Kırmızı",
  "Yeşil - Lacivert",
  "Yeşil - Mavi",
  "Yeşil - Mavi - Mor",
  "Yeşil - Mercan",
  "Yeşil - Mor",
  "Yeşil - Pembe",
  "Yeşil - Sarı",
  "Yeşil - Siyah",
  "Yeşil - Ten Rengi",
  "Yeşil - Turkuaz",
  "Yeşil - Turuncu",
  "Yeşil - Turuncu - Mor",
  "Yeşil - Şeffaf",
  "Yeşil Kamuflaj",
  "Zebra",
  "Zeytin Yeşili",
  "iPhone",
  "Çam Yeşili",
  "Çay",
  "Çim Yeşili",
  "Çimen Yeşili",
  "Çizgili",
  "Çizgili Deri",
  "Çiçek",
  "Çiçek Desenli",
  "Çiçek-Kuş",
  "Çok Renkli",
  "Çubuk Adam",
  "İnci Beyazı",
  "İstanbul",
  "Şafak Mavisi",
  "Şampanya",
  "Şampanya - Altın",
  "Şarap Kırmızısı",
  "Şeffaf",
  "Şeffaf - Altın",
  "Şeffaf - Beyaz",
  "Şeffaf - Füme",
  "Şeffaf - Gold",
  "Şeffaf - Gri",
  "Şeffaf - Gümüş",
  "Şeffaf - Kırmızı",
  "Şeffaf - Lacivert",
  "Şeffaf - Lila",
  "Şeffaf - Mavi",
  "Şeffaf - Mor",
  "Şeffaf - Pembe",
  "Şeffaf - Rose Gold",
  "Şeffaf - Sarı",
  "Şeffaf - Siyah",
  "Şeffaf - Turkuaz",
  "Şeffaf - Turuncu",
  "Şeffaf - Yeşil",
  "Şeffaf Beyaz",
  "Şeffaf Bronz",
  "Şeffaf Gold",
  "Şeffaf Gri",
  "Şeffaf Gül",
  "Şeffaf Kırmızı",
  "Şeffaf Mat",
  "Şeffaf Mavi",
  "Şeffaf Mor",
  "Şeffaf Pembe",
  "Şeffaf Sarı",
  "Şeffaf Siyah",
  "Şeffaf Yeşil",
  "Şeftali",
  "Şeker Pembe",
  "Şeker Pembesi",
  EMPTY_OPTION,
] as const;

/**
 * @CategoryName Telefon > Cep Telefonu Aksesuarları > Kılıflar
 * @Field Telefon Modeli
 */

export const PhoneCase_PhonesList = [
  "1",
  "Galaxy  M01 Core",
  "Galaxy 21S",
  "Galaxy 7 Fold",
  "Galaxy A01",
  "Galaxy A01 Core",
  "Galaxy A01 US Version",
  "Galaxy A02",
  "Galaxy A02s",
  "Galaxy A03",
  "Galaxy A03 Core",
  "Galaxy A03S",
  "Galaxy A04",
  "Galaxy A04 4G",
  "Galaxy A04 Core",
  "Galaxy A04e",
  "Galaxy A04e 4G",
  "Galaxy A04s",
  "Galaxy A07",
  "Galaxy A10",
  "Galaxy A10e",
  "Galaxy A10s",
  "Galaxy A11",
  "Galaxy A12",
  "Galaxy A12 4G",
  "Galaxy A12 5G",
  "Galaxy A12 Nacho",
  "Galaxy A13",
  "Galaxy A13 4G",
  "Galaxy A13 5G",
  "Galaxy A14",
  "Galaxy A14 4G",
  "Galaxy A14 5G",
  "Galaxy A2 Core",
  "Galaxy A20",
  "Galaxy A20e",
  "Galaxy A20s",
  "Galaxy A21",
  "Galaxy A21s",
  "Galaxy A22",
  "Galaxy A22 4G",
  "Galaxy A22 5G",
  "Galaxy A22e",
  "Galaxy A23",
  "Galaxy A23 4G",
  "Galaxy A23 5G",
  "Galaxy A23e",
  "Galaxy A24",
  "Galaxy A24 4G",
  "Galaxy A24 5G",
  "Galaxy A25",
  "Galaxy A27",
  "Galaxy A3",
  "Galaxy A3 (2017)",
  "Galaxy A3 2015",
  "Galaxy A3 2016",
  "Galaxy A3 2017",
  "Galaxy A3 2018",
  "Galaxy A3 New",
  "Galaxy A30",
  "Galaxy A30 Plus",
  "Galaxy A30s",
  "Galaxy A31",
  "Galaxy A32",
  "Galaxy A32 4G",
  "Galaxy A32 4G2",
  "Galaxy A32 5G",
  "Galaxy A32 LTE",
  "Galaxy A33",
  "Galaxy A33 5G",
  "Galaxy A34",
  "Galaxy A34 5G",
  "Galaxy A40",
  "Galaxy A40s",
  "Galaxy A41",
  "Galaxy A42",
  "Galaxy A42 5G",
  "Galaxy A5",
  "Galaxy A5 (2017)",
  "Galaxy A5 2015",
  "Galaxy A5 2016",
  "Galaxy A5 2017",
  "Galaxy A5 2018",
  "Galaxy A5 New",
  "Galaxy A50",
  "Galaxy A50S",
  "Galaxy A51",
  "Galaxy A51 4G",
  "Galaxy A51 5G",
  "Galaxy A510",
  "Galaxy A514G",
  "Galaxy A51S",
  "Galaxy A52",
  "Galaxy A52 5G",
  "Galaxy A52s",
  "Galaxy A52s 5G",
  "Galaxy A53",
  "Galaxy A53 5G",
  "Galaxy A54",
  "Galaxy A54 5G",
  "Galaxy A6",
  "Galaxy A6 2018",
  "Galaxy A6 Plus",
  "Galaxy A6 Plus 2018",
  "Galaxy A60",
  "Galaxy A6S",
  "Galaxy A7",
  "Galaxy A7 (2017)",
  "Galaxy A7 (2018)",
  "Galaxy A7 2015",
  "Galaxy A7 2016",
  "Galaxy A7 2017",
  "Galaxy A7 2018",
  "Galaxy A7 2019",
  "Galaxy A7 New",
  "Galaxy A70",
  "Galaxy A70E",
  "Galaxy A70s",
  "Galaxy A71",
  "Galaxy A71 4G",
  "Galaxy A71 5G",
  "Galaxy A72",
  "Galaxy A72 5G",
  "Galaxy A73",
  "Galaxy A73 5G",
  "Galaxy A74",
  "Galaxy A750",
  "Galaxy A8",
  "Galaxy A8 (2018)",
  "Galaxy A8 2015",
  "Galaxy A8 2016",
  "Galaxy A8 2018",
  "Galaxy A8 Plus",
  "Galaxy A8 Plus (2018)",
  "Galaxy A8 Plus 2018",
  "Galaxy A8 Star",
  "Galaxy A80",
  "Galaxy A81",
  "Galaxy A82",
  "Galaxy A82 5G",
  "Galaxy A8S",
  "Galaxy A9",
  "Galaxy A9 (2018)",
  "Galaxy A9 2016",
  "Galaxy A9 2018",
  "Galaxy A9 2019",
  "Galaxy A9 Pro",
  "Galaxy A9 Pro 2016",
  "Galaxy A9 Pro 2019",
  "Galaxy A9 Star",
  "Galaxy A9 Star Lite",
  "Galaxy A90",
  "Galaxy A90 5G",
  "Galaxy A91",
  "Galaxy A9S",
  "Galaxy Ace",
  "Galaxy Ace 2",
  "Galaxy Ace 3",
  "Galaxy Ace 4",
  "Galaxy Ace 5830",
  "Galaxy Ace S5830",
  "Galaxy Alpha",
  "Galaxy Beam",
  "Galaxy Beam i8530",
  "Galaxy Buds Live",
  "Galaxy C5",
  "Galaxy C5 Pro",
  "Galaxy C7",
  "Galaxy C7 Core",
  "Galaxy C7 Pro",
  "Galaxy C8",
  "Galaxy C9",
  "Galaxy C9 Pro",
  "Galaxy Chat",
  "Galaxy Core",
  "Galaxy Core 2",
  "Galaxy Core G350",
  "Galaxy Core Plus",
  "Galaxy Core Prime",
  "Galaxy Core Prime G360",
  "Galaxy Core i8262",
  "Galaxy Cover 4",
  "Galaxy Duo",
  "Galaxy Duo S7562",
  "Galaxy E5",
  "Galaxy E7",
  "Galaxy F02S",
  "Galaxy F04 4G",
  "Galaxy F12",
  "Galaxy F13",
  "Galaxy F13 4G",
  "Galaxy F14",
  "Galaxy F14 5G",
  "Galaxy F23",
  "Galaxy F23 5G",
  "Galaxy F41",
  "Galaxy F42",
  "Galaxy F52",
  "Galaxy F52 5G",
  "Galaxy F62",
  "Galaxy Fame S6810",
  "Galaxy Feel 2",
  "Galaxy Fold 3",
  "Galaxy Fold 4",
  "Galaxy G720 Grand Max",
  "Galaxy Gear S3",
  "Galaxy Gio",
  "Galaxy Gio S5660",
  "Galaxy Grand",
  "Galaxy Grand 2",
  "Galaxy Grand 2 Duos G7106",
  "Galaxy Grand 2 G7102",
  "Galaxy Grand 3 Duos",
  "Galaxy Grand Duos",
  "Galaxy Grand Duos i9082",
  "Galaxy Grand Max G7200",
  "Galaxy Grand Mega",
  "Galaxy Grand Neo",
  "Galaxy Grand Neo Plus",
  "Galaxy Grand Prime",
  "Galaxy Grand Prime G530",
  "Galaxy Grand Prime Plus",
  "Galaxy Grand Prime Pro",
  "Galaxy J1",
  "Galaxy J1 2016",
  "Galaxy J1 Ace",
  "Galaxy J1 Mini",
  "Galaxy J1 Mini Prime",
  "Galaxy J2",
  "Galaxy J2 2016",
  "Galaxy J2 Core",
  "Galaxy J2 Prime",
  "Galaxy J2 Pro",
  "Galaxy J2 Pro 2018",
  "Galaxy J3",
  "Galaxy J3 2015",
  "Galaxy J3 2016",
  "Galaxy J3 2017",
  "Galaxy J3 Prime",
  "Galaxy J3 Pro",
  "Galaxy J3 Pro 2017",
  "Galaxy J330",
  "Galaxy J330 Pro",
  "Galaxy J4",
  "Galaxy J4 2018",
  "Galaxy J4 Core",
  "Galaxy J4 Plus",
  "Galaxy J4 Plus 2018",
  "Galaxy J4 Prime",
  "Galaxy J5",
  "Galaxy J5 2015",
  "Galaxy J5 2016",
  "Galaxy J5 2017",
  "Galaxy J5 Core",
  "Galaxy J5 Prime",
  "Galaxy J5 Pro",
  "Galaxy J5 Pro 2016",
  "Galaxy J5 Pro 2017",
  "Galaxy J5 Pro 2018",
  "Galaxy J510",
  "Galaxy J530",
  "Galaxy J530 Pro",
  "Galaxy J6",
  "Galaxy J6 2018",
  "Galaxy J6 Plus",
  "Galaxy J6 Plus 2018",
  "Galaxy J6 Prime",
  "Galaxy J7",
  "Galaxy J7 2015",
  "Galaxy J7 2016",
  "Galaxy J7 2017",
  "Galaxy J7 2018",
  "Galaxy J7 Core",
  "Galaxy J7 Duo",
  "Galaxy J7 Max",
  "Galaxy J7 Nxt",
  "Galaxy J7 Plus",
  "Galaxy J7 Prime",
  "Galaxy J7 Prime 2",
  "Galaxy J7 Pro",
  "Galaxy J7 Pro 2016",
  "Galaxy J7 Pro 2017",
  "Galaxy J710",
  "Galaxy J730",
  "Galaxy J730 Pro",
  "Galaxy J8",
  "Galaxy J8 2018",
  "Galaxy J8 Plus",
  "Galaxy Jean",
  "Galaxy Jump 2",
  "Galaxy K Zoom",
  "Galaxy M01",
  "Galaxy M01 Core",
  "Galaxy M01S",
  "Galaxy M02",
  "Galaxy M02S",
  "Galaxy M04",
  "Galaxy M10",
  "Galaxy M10s",
  "Galaxy M11",
  "Galaxy M12",
  "Galaxy M13",
  "Galaxy M13 4G",
  "Galaxy M13 5G",
  "Galaxy M14",
  "Galaxy M14 5G",
  "Galaxy M20",
  "Galaxy M20S",
  "Galaxy M21",
  "Galaxy M21S",
  "Galaxy M22",
  "Galaxy M23",
  "Galaxy M23 5G",
  "Galaxy M24",
  "Galaxy M25",
  "Galaxy M30",
  "Galaxy M30s",
  "Galaxy M31",
  "Galaxy M31s",
  "Galaxy M32",
  "Galaxy M32 4G",
  "Galaxy M32 5G",
  "Galaxy M33",
  "Galaxy M33 5G",
  "Galaxy M34",
  "Galaxy M40",
  "Galaxy M40s",
  "Galaxy M42 5G",
  "Galaxy M51",
  "Galaxy M52",
  "Galaxy M52 5G",
  "Galaxy M53",
  "Galaxy M53 5G",
  "Galaxy M54",
  "Galaxy M62",
  "Galaxy M80s",
  "Galaxy Mega",
  "Galaxy Mega 2",
  "Galaxy Mega 2 G750",
  "Galaxy Mega 5.8",
  "Galaxy Mega 6.3",
  "Galaxy Mini",
  "Galaxy Mini S5570",
  "Galaxy Nexus",
  "Galaxy Nexus i9250",
  "Galaxy Note",
  "Galaxy Note 1",
  "Galaxy Note 10",
  "Galaxy Note 10 Lite",
  "Galaxy Note 10 PluS 5G",
  "Galaxy Note 10 Plus",
  "Galaxy Note 10 Pro",
  "Galaxy Note 10+ Plus",
  "Galaxy Note 12",
  "Galaxy Note 2",
  "Galaxy Note 20",
  "Galaxy Note 20 5G",
  "Galaxy Note 20 Plus",
  "Galaxy Note 20 Ultra",
  "Galaxy Note 20 Ultra 5G",
  "Galaxy Note 3",
  "Galaxy Note 3 Neo",
  "Galaxy Note 4",
  "Galaxy Note 4 Edge",
  "Galaxy Note 5",
  "Galaxy Note 5 Edge",
  "Galaxy Note 7",
  "Galaxy Note 8",
  "Galaxy Note 9",
  "Galaxy Note 9 Plus",
  "Galaxy Note Edge",
  "Galaxy Note FE",
  "Galaxy Note N7000",
  "Galaxy Note10 +",
  "Galaxy On Max",
  "Galaxy On5",
  "Galaxy On5 2016",
  "Galaxy On6",
  "Galaxy On7",
  "Galaxy On7 2016",
  "Galaxy On7 Prime",
  "Galaxy On8",
  "Galaxy Pro",
  "Galaxy Quantum 2",
  "Galaxy S Advance",
  "Galaxy S Advance i9070",
  "Galaxy S Duo",
  "Galaxy S Duos 7560 7580",
  "Galaxy S Duos 7562 7582",
  "Galaxy S Entry",
  "Galaxy S Plus",
  "Galaxy S Plus i9001",
  "Galaxy S10",
  "Galaxy S10 5G",
  "Galaxy S10 Lite",
  "Galaxy S10 Plus",
  "Galaxy S10+",
  "Galaxy S10E Plus",
  "Galaxy S10e",
  "Galaxy S10s",
  "Galaxy S11",
  "Galaxy S11 Plus",
  "Galaxy S11 Ultra",
  "Galaxy S11e",
  "Galaxy S2",
  "Galaxy S20",
  "Galaxy S20 5G",
  "Galaxy S20 FE",
  "Galaxy S20 FE 5G",
  "Galaxy S20 Lite",
  "Galaxy S20 PluS 5G",
  "Galaxy S20 Plus",
  "Galaxy S20 Ultra",
  "Galaxy S20 Ultra 5G",
  "Galaxy S20+",
  "Galaxy S20+ Plus",
  "Galaxy S21",
  "Galaxy S21 5G",
  "Galaxy S21 FE",
  "Galaxy S21 FE 5G",
  "Galaxy S21 PluS 5G",
  "Galaxy S21 Plus",
  "Galaxy S21 Ultra",
  "Galaxy S21 Ultra 5G",
  "Galaxy S21+",
  "Galaxy S21+ Plus",
  "Galaxy S22",
  "Galaxy S22 5G",
  "Galaxy S22 FE",
  "Galaxy S22 Plus",
  "Galaxy S22 Plus 5G",
  "Galaxy S22 Pro",
  "Galaxy S22 Ultra",
  "Galaxy S22 Ultra 5G",
  "Galaxy S22+",
  "Galaxy S22+ 5G",
  "Galaxy S22+ Plus",
  "Galaxy S23",
  "Galaxy S23 5G",
  "Galaxy S23 Plus",
  "Galaxy S23 Plus 5G",
  "Galaxy S23 Ultra",
  "Galaxy S23 Ultra 5G",
  "Galaxy S23+",
  "Galaxy S24",
  "Galaxy S3",
  "Galaxy S3 Mini",
  "Galaxy S3 Neo",
  "Galaxy S30",
  "Galaxy S30 Plus",
  "Galaxy S30 Ultra",
  "Galaxy S4",
  "Galaxy S4 Active",
  "Galaxy S4 Mini",
  "Galaxy S4 Zoom",
  "Galaxy S4 i9500",
  "Galaxy S5",
  "Galaxy S5 Mini",
  "Galaxy S5 Zoom",
  "Galaxy S6",
  "Galaxy S6 Edge",
  "Galaxy S6 Edge Plus",
  "Galaxy S7",
  "Galaxy S7 Active",
  "Galaxy S7 Edge",
  "Galaxy S7 Edge Plus",
  "Galaxy S8",
  "Galaxy S8 Active",
  "Galaxy S8 Plus",
  "Galaxy S9",
  "Galaxy S9 Plus",
  "Galaxy S9+",
  "Galaxy Star 2",
  "Galaxy Tab",
  "Galaxy Tab S5e",
  "Galaxy Tab S8 Ultra",
  "Galaxy Trend",
  "Galaxy Trend Lite",
  "Galaxy Trend Lite S7390",
  "Galaxy Trend Plus",
  "Galaxy Trend Plus S7580",
  "Galaxy W",
  "Galaxy W21",
  "Galaxy Watch",
  "Galaxy Wave 2",
  "Galaxy Wide 3",
  "Galaxy Win",
  "Galaxy Wonder",
  "Galaxy X Cover 5",
  "Galaxy X Cover Pro",
  "Galaxy XCover6 Pro",
  "Galaxy Xcover 4",
  "Galaxy Xcover 4s",
  "Galaxy Xcover 5",
  "Galaxy Xcover 6 Pro",
  "Galaxy Xcover Pro",
  "Galaxy Xcover Pro 2",
  "Galaxy Xcover Pro 6",
  "Galaxy Y",
  "Galaxy Y Pro",
  "Galaxy Y S5360",
  "Galaxy Z Filp 3 5G",
  "Galaxy Z Flip",
  "Galaxy Z Flip 3",
  "Galaxy Z Flip 3 5G",
  "Galaxy Z Flip 4",
  "Galaxy Z Flip 4 5G",
  "Galaxy Z Flip 5",
  "Galaxy Z Flip2",
  "Galaxy Z Flip3 5g",
  "Galaxy Z Flip4",
  "Galaxy Z Flip4 5G",
  "Galaxy Z Fold 2",
  "Galaxy Z Fold 3",
  "Galaxy Z Fold 3 5G",
  "Galaxy Z Fold 4",
  "Galaxy Z Fold 4 5G",
  "Galaxy Z Fold2",
  "Galaxy Z Fold2 5G",
  "Galaxy Z1",
  "Mi 12t",
  "Mi 12t Pro",
  "OPPO A15",
  "OPPO A15S",
  "OPPO A5 2020",
  "OPPO A5S",
  "OPPO A72",
  "OPPO A73",
  "OPPO A9",
  "OPPO A9 2020",
  "OPPO F11",
  "Oppo",
  "Oppo A1 Pro",
  "Oppo A13",
  "Oppo A17",
  "Oppo A54",
  "Oppo A54 4G",
  "Oppo A55 5G",
  "Oppo A74",
  "Oppo A74 4G",
  "Oppo A7X",
  "Oppo A83",
  "Oppo A91",
  "Oppo A92",
  "Oppo A94",
  "Oppo AX7",
  "Oppo F3",
  "Oppo Find X2",
  "Oppo Find X6",
  "Oppo Find X6 Pro",
  "Oppo RX17 Neo",
  "Oppo RX17 Pro",
  "Oppo Reno 10X Zoom",
  "Oppo Reno 2Z",
  "Oppo Reno 3",
  "Oppo Reno 3 Pro",
  "Oppo Reno 4 Lite",
  "Oppo Reno 4 Pro",
  "Oppo Reno 5",
  "Oppo Reno 5 Pro 5G",
  "Oppo Reno 6",
  "Oppo Reno 6 Pro",
  "Oppo Reno 6 Pro Plus",
  "Oppo Reno Z",
  "Oppo Reno8 5G",
  "Oppo Reno8 Lite",
  "Oppo Reno8 T 4G",
  "Oppo Reno8 T 5G",
  "Oppo Reno9",
  "Redmi  Note 11S",
  "Redmi 10",
  "Redmi 10 2022",
  "Redmi 10 5G",
  "Redmi 10 Prime",
  "Redmi 10A",
  "Redmi 10C",
  "Redmi 10C 4G",
  "Redmi 10X",
  "Redmi 10X Pro 5G",
  "Redmi 11 Prime",
  "Redmi 11 Prime 5G",
  "Redmi 12",
  "Redmi 12C",
  "Redmi 1S",
  "Redmi 2 Pro",
  "Redmi 20x",
  "Redmi 2S",
  "Redmi 2X",
  "Redmi 3",
  "Redmi 3 Pro",
  "Redmi 3S",
  "Redmi 3X",
  "Redmi 4",
  "Redmi 4 Prime",
  "Redmi 4 Pro",
  "Redmi 4A",
  "Redmi 4X",
  "Redmi 4X - Redmi 4",
  "Redmi 5",
  "Redmi 5 Plus",
  "Redmi 5A",
  "Redmi 5X",
  "Redmi 6",
  "Redmi 6 Pro",
  "Redmi 6A",
  "Redmi 6X",
  "Redmi 7",
  "Redmi 7A",
  "Redmi 8",
  "Redmi 8A",
  "Redmi 8A Pro",
  "Redmi 9",
  "Redmi 9 Power",
  "Redmi 9 Prime",
  "Redmi 9 Pro Max",
  "Redmi 9A",
  "Redmi 9AT",
  "Redmi 9C",
  "Redmi 9C NFC",
  "Redmi 9T",
  "Redmi 9i Sport",
  "Redmi 9İ",
  "Redmi A1",
  "Redmi A1 4G",
  "Redmi A1 Plus",
  "Redmi A1 Plus 4G",
  "Redmi A2",
  "Redmi A2 Plus",
  "Redmi Go",
  "Redmi K20",
  "Redmi K20 Pro",
  "Redmi K20 Pro Premium",
  "Redmi K30",
  "Redmi K30 5G",
  "Redmi K30 Pro",
  "Redmi K30 Pro Zoom",
  "Redmi K30 Ultra",
  "Redmi K30S",
  "Redmi K30i",
  "Redmi K34",
  "Redmi K40",
  "Redmi K40 Gaming",
  "Redmi K40 Pro",
  "Redmi K40 Pro Plus",
  "Redmi K40 Pro+",
  "Redmi K40S",
  "Redmi K50",
  "Redmi K50 Gaming",
  "Redmi K50 Pro",
  "Redmi K50 Ultra",
  "Redmi K50i",
  "Redmi K60",
  "Redmi K60 Pro",
  "Redmi K60E",
  "Redmi Note",
  "Redmi Note 10",
  "Redmi Note 10 4G",
  "Redmi Note 10 5G",
  "Redmi Note 10 JE",
  "Redmi Note 10 Lite",
  "Redmi Note 10 Pro",
  "Redmi Note 10 Pro 4G",
  "Redmi Note 10 Pro 5G",
  "Redmi Note 10 Pro Max",
  "Redmi Note 10T",
  "Redmi Note 10T 5G",
  "Redmi Note 10s",
  "Redmi Note 11",
  "Redmi Note 11 4G",
  "Redmi Note 11 5G",
  "Redmi Note 11 Global",
  "Redmi Note 11 Pro",
  "Redmi Note 11 Pro 4G",
  "Redmi Note 11 Pro 5G",
  "Redmi Note 11 Pro Plus",
  "Redmi Note 11 Pro Plus 5g",
  "Redmi Note 11 S",
  "Redmi Note 11 SE",
  "Redmi Note 11C",
  "Redmi Note 11E",
  "Redmi Note 11E 5G",
  "Redmi Note 11E Pro",
  "Redmi Note 11R",
  "Redmi Note 11S",
  "Redmi Note 11T",
  "Redmi Note 11T 5G",
  "Redmi Note 11T Pro",
  "Redmi Note 11T Pro 5G",
  "Redmi Note 11T Pro Plus",
  "Redmi Note 11T Pro+",
  "Redmi Note 12",
  "Redmi Note 12 4G",
  "Redmi Note 12 5G",
  "Redmi Note 12 Plus",
  "Redmi Note 12 Pro",
  "Redmi Note 12 Pro 4G",
  "Redmi Note 12 Pro 5G",
  "Redmi Note 12 Pro Plus",
  "Redmi Note 12 Pro+",
  "Redmi Note 12 Pro+ 5G",
  "Redmi Note 12 Turbo",
  "Redmi Note 12S",
  "Redmi Note 12T",
  "Redmi Note 12T Pro",
  "Redmi Note 13",
  "Redmi Note 2",
  "Redmi Note 3",
  "Redmi Note 3 Pro",
  "Redmi Note 4",
  "Redmi Note 4A",
  "Redmi Note 4X",
  "Redmi Note 5",
  "Redmi Note 5 Plus",
  "Redmi Note 5 Pro",
  "Redmi Note 5A",
  "Redmi Note 5A Prime",
  "Redmi Note 5A Pro",
  "Redmi Note 6",
  "Redmi Note 6 Pro",
  "Redmi Note 7",
  "Redmi Note 7 Pro",
  "Redmi Note 7S",
  "Redmi Note 8",
  "Redmi Note 8 Pro",
  "Redmi Note 8T",
  "Redmi Note 9",
  "Redmi Note 9 4G",
  "Redmi Note 9 5G",
  "Redmi Note 9 Pro",
  "Redmi Note 9 Pro 5G",
  "Redmi Note 9 Pro Max",
  "Redmi Note 9A",
  "Redmi Note 9C",
  "Redmi Note 9S",
  "Redmi Note 9T",
  "Redmi Note 9T Pro",
  "Redmi Pro",
  "Redmi S2",
  "Redmi Y1",
  "Redmi Y1 Lite",
  "Redmi Y2",
  "Redmi Y3",
  "Reno",
  "Reno 10X",
  "Reno 10X Zoom",
  "Reno 2",
  "Reno 2F",
  "Reno 2Z",
  "Reno 2Z 2019",
  "Reno 3",
  "Reno 3 5G",
  "Reno 3 Pro",
  "Reno 3 Pro 5G",
  "Reno 3a",
  "Reno 4",
  "Reno 4 5G",
  "Reno 4 Lite",
  "Reno 4 Pro",
  "Reno 4 Pro 4G",
  "Reno 4 Pro 5G",
  "Reno 4 SE",
  "Reno 4F",
  "Reno 4G",
  "Reno 4Z",
  "Reno 5",
  "Reno 5 4G",
  "Reno 5 5G",
  "Reno 5 K",
  "Reno 5 Lite",
  "Reno 5 Pro",
  "Reno 5 Pro 5G",
  "Reno 5 Pro Plus",
  "Reno 5 Pro+",
  "Reno 5A",
  "Reno 5F",
  "Reno 5G",
  "Reno 5Z",
  "Reno 6",
  "Reno 6 4G",
  "Reno 6 5G",
  "Reno 6 Lite",
  "Reno 6 Pro",
  "Reno 6 Pro 5G",
  "Reno 6 Pro Plus",
  "Reno 6Z",
  "Reno 7",
  "Reno 7 4G",
  "Reno 7 5G",
  "Reno 7 Lite",
  "Reno 7 Lite 5G",
  "Reno 7 Pro",
  "Reno 7 Pro 5G",
  "Reno 7 SE",
  "Reno 7 SE 5G",
  "Reno 7Z",
  "Reno 7Z 5G",
  "Reno 8",
  "Reno 8 5G",
  "Reno 8 Lite",
  "Reno 8 Lite 5G",
  "Reno 8 Pro",
  "Reno 8 Pro 5G",
  "Reno 8T 4G",
  "Reno 8T 5G",
  "Reno 9",
  "Reno 9 Pro",
  "Reno 9 Pro Plus",
  "Reno A",
  "Reno A54 4G",
  "Reno ACE",
  "Reno ACE 2",
  "Reno Z",
  "Reno2 F",
  "Reno2 Z",
  "Reno3",
  "Reno3 A",
  "Reno3 Youth",
  "Reno4",
  "Reno4 Pro",
  "Reno4 SE",
  "Reno4 Z 5G",
  "Reno5 4G",
  "Reno5 K",
  "Reno5 Lite",
  "Reno5 Pro",
  "Reno5 Z",
  "Reno7 Pro 5G",
  "Reno7 Z",
  "Reno8 Pro+",
  "Samsung (Tüm Modeller)",
  "Samsung Galaxy A03S",
  "Samsung Galaxy A04E",
  "Samsung Galaxy A52",
  "Samsung Galaxy A72",
  "Samsung Galaxy Ace Plus S7500",
  "Samsung Galaxy Corby 2 S3850",
  "Samsung Galaxy Core",
  "Samsung Galaxy E250",
  "Samsung Galaxy F52 5G",
  "Samsung Galaxy M13",
  "Samsung Galaxy M22",
  "Samsung Galaxy S İ9000",
  "Samsung Galaxy S21 FE 5G",
  "Samsung Galaxy S22",
  "Samsung Galaxy S22 Plus",
  "Samsung Galaxy S22 Ultra",
  "Samsung Galaxy S23 Plus",
  "Samsung Galaxy S23 Ultra",
  "Samsung Galaxy S3350",
  "Samsung Galaxy S3600",
  "Samsung Galaxy S5230 Star",
  "Samsung Galaxy S7 Plus",
  "Samsung Galaxy Wave S5253",
  "Samsung Galaxy Wave S7233",
  "Samsung Galaxy Wave S8500",
  "Samsung Galaxy Xcover 4",
  "Samsung Galaxy Z Flip",
  "Xiaomi 11",
  "Xiaomi 11 Lite",
  "Xiaomi 11 Pro",
  "Xiaomi 11 Ultra",
  "Xiaomi 11T",
  "Xiaomi 11T Pro",
  "Xiaomi 12",
  "Xiaomi 12 Lite",
  "Xiaomi 12 Pro",
  "Xiaomi 12 Ultra",
  "Xiaomi 12S",
  "Xiaomi 12S Ultra",
  "Xiaomi 12T",
  "Xiaomi 12T Pro",
  "Xiaomi 12T/12T Pro",
  "Xiaomi 12X",
  "Xiaomi 13",
  "Xiaomi 13 Lite",
  "Xiaomi 13 Pro",
  "Xiaomi 13 Ultra",
  "Xiaomi Mi 11T 5G",
  "Xiaomi Mi A3",
  "Xiaomi Mi Max 2",
  "Xiaomi Mi Pad 5",
  "Xiaomi Mi Poco X3 GT",
  "Xiaomi Note 8",
  "Xiaomi Poco C40",
  "Xiaomi Redmi 12C",
  "Xiaomi Redmi K40 Gaming",
  "Xiaomi Redmi Note 11T Pro+ 5G",
  "Xiaomi Redmi Note 12",
  "Xiaomi Redmi Note 12 4G",
  "iPhone 11",
  "iPhone 12",
  "iPhone 13",
  "iPhone 14",
  "iPhone 15",
  "iPhone 11 Pro",
  "iPhone 12 Pro",
  "iPhone 13 Pro",
  "iPhone 14 Pro",
  "iPhone 15 Pro",
  "iPhone 11 Pro Max",
  "iPhone 12 Pro Max",
  "iPhone 13 Pro Max",
  "iPhone 14 Pro Max",
  "iPhone 15 Pro Max",
  "iPhone 14 Plus",
  "iPhone 15 Plus",
  "iPhone 12 Mini",
  "iPhone 13 Mini",
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 6S",
  "iPhone 6S Plus",
  "iPhone 7",
  "iPhone 7 Plus",
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone SE",
  "iPhone SE 2020",
  "iPhone SE 2022",
  "iPhone X",
  "iPhone XR",
  "iPhone XS",
  "iPhone XS Max",
  "iPhone XS Plus",
] as const;

/**
 * @CategoryName Telefon > Cep Telefonu Aksesuarları > Kılıflar
 * @Field Telefon Modeli
 * @Selfmade
 */
export const PhoneCase_PhonesListExtend = [
  "Poco X3",
  "Poco X3 Pro",
  "Galaxy Z Fold 5",
  "Oppo A16",
] as const;

/**
 * @CategoryName Telefon > Cep Telefonu Aksesuarları > Kılıflar
 * @Field Uyumlu Marka
 */
export const PhoneCase_PhoneBrands = [
  "Apple",
  "Xiaomi",
  "Redmi",
  "Samsung",
  "Huawei",
  "Infinix",
  "Omix",
  "Oppo",
  "General Mobile",
  "Poco",
  "Realme",
  "Reeder",
  "Tecno",
  "iPhone",
] as const;

/**
 * @CategoryName Telefon > Cep Telefonu Aksesuarları > Kılıflar
 * @Field Garanti Tipi
 * @Optional
 */
export const PhoneCase_GuaranteeTypes = [
  "İthalatçı Garantili",
  "Sony Eurasia Garantili",
  EMPTY_OPTION,
] as const;

/**
 * @CategoryName Telefon > Cep Telefonu Aksesuarları > Kılıflar
 * @Field Su Geçirmezlik
 * @Optional
 */

export const PhoneCase_WaterProof = ["Var", "Yok", EMPTY_OPTION] as const;

/**
 * @CategoryName Telefon > Cep Telefonu Aksesuarları > Kılıflar
 * @Field Ürün  Kodu
 * @Optional
 */
export const PhoneCase_PhonesListCode = [
  EMPTY_OPTION,
  "Asus Zenfone 5",
  "Asus Zenfone 6",
  "Asus Zenfone Go",
  "Asus Zenfone Laser 5,5 inç",
  "BlackBerry",
  "BlackBerry Bold 9900",
  "BlackBerry Curve 8520",
  "BlackBerry Passport",
  "BlackBerry Z10",
  "Blackberry Q10",
  "Casper Via 8C",
  "Casper Via Air",
  "Casper Via V10",
  "Casper Via V3",
  "Casper Via V4",
  "Casper Via V6",
  "Casper Via V8",
  "Casper Via V9",
  "Dark Evo E40",
  "Dark Evo P55",
  "Discovery Elite",
  "Galaxy Nexus",
  "Galaxy S4",
  "Galaxy Z Flip 5",
  "Galaxy Z Fold 5",
  "General Mobile 4G Android One",
  "General Mobile Discovery",
  "General Mobile Discovery 2",
  "General Mobile Discovery Air",
  "HB0000012S8E",
  "HB0000017G24",
  "HB000003XBYX",
  "HB000004FKMC",
  "HB0000063R9R",
  "HB000007PTJK",
  "HB000007PV9R",
  "HTC 526 Dual Sim",
  "HTC Cha Cha",
  "HTC Desire 200",
  "HTC Desire 310",
  "HTC Desire 320",
  "HTC Desire 500",
  "HTC Desire 516",
  "HTC Desire 610",
  "HTC Desire 620",
  "HTC Desire 626",
  "HTC Desire 816",
  "HTC Desire 820",
  "HTC Desire C",
  "HTC Desire Eye",
  "HTC Desire X",
  "HTC Evo",
  "HTC Explorer",
  "HTC Incredible S",
  "HTC M8 Mini",
  "HTC One",
  "HTC One E8",
  "HTC One M7",
  "HTC One M8",
  "HTC One M9",
  "HTC One M9 Plus",
  "HTC One Mini",
  "HTC One S",
  "HTC One SV",
  "HTC One V",
  "HTC One X",
  "HTC Sensation",
  "HTC Sensation XL",
  "HTC Wildfire S",
  "HTC Windows 8 X",
  "HTC Windows Phone 8 S",
  "Huawei 8800",
  "Huawei Ascend G330",
  "Huawei Ascend G610",
  "Huawei Ascend G7",
  "Huawei Ascend G700",
  "Huawei Ascend Mate 7",
  "Huawei Ascend P1",
  "Huawei Ascend P6",
  "Huawei Ascend P7",
  "Huawei Ascend Y320",
  "Huawei Honor 6",
  "Huawei Honor x9a",
  "Huawei U8850",
  "Incipio iPhone",
  "Invisible Shield HTC One",
  "Invisible Shield S5233",
  "Invisible Shield iPhone",
  "Invisible Shield iPhone 4",
  "Koyu Evo P60",
  "Koyu Evo X5",
  "LG Avea L Bello",
  "LG G2 Mini",
  "LG G3 D855",
  "LG G3 Mini",
  "LG G3 Stylus",
  "LG G4",
  "LG G4 Stylus",
  "LG G4C",
  "LG G5",
  "LG L 80",
  "LG L70",
  "LG L90",
  "LG P760 Optimus L9",
  "LG V10",
  "Lenovo A5000",
  "Lenovo A7000",
  "Lenovo P70",
  "Lenovo S60",
  "Lenovo S90",
  "Lenovo VIBE X2",
  "Lenovo Vibe Z2 Pro",
  "Lg G2",
  "Lg L3",
  "Lg L5",
  "Lg L7",
  "Lg L7 2",
  "Lg Nexus 4",
  "Lg Nexus 5",
  "Lg Optimus G E975",
  "Lg Optimus G Pro",
  "Lg Optimus P920",
  "Lg P725",
  "Meizu MX4 Pro",
  "Microsoft Lumia 535",
  "Microsoft Lumia 640",
  "Microsoft Lumia 640 XL",
  "Motorola",
  "Motorola Defy Mini",
  "Motorola Moto G",
  "Motorola Motoluxe",
  "N8 Kılıf",
  "Nokia  Asha  501",
  "Nokia 500",
  "Nokia 6303i",
  "Nokia 700",
  "Nokia Asha 210",
  "Nokia Asha 501",
  "Nokia C2-01",
  "Nokia C3",
  "Nokia C5-03",
  "Nokia E6",
  "Nokia E7",
  "Nokia Lumia 1020",
  "Nokia Lumia 1320",
  "Nokia Lumia 1520",
  "Nokia Lumia 520",
  "Nokia Lumia 530",
  "Nokia Lumia 620",
  "Nokia Lumia 625",
  "Nokia Lumia 630",
  "Nokia Lumia 720",
  "Nokia Lumia 735",
  "Nokia Lumia 820",
  "Nokia Lumia 830",
  "Nokia Lumia 920",
  "Nokia Lumia 925",
  "Nokia Lumia 930",
  "Nokia N8",
  "Nokia N9",
  "Nokia X",
  "Nokia XL",
  "One Plus 9",
  "One Plus 9 Pro",
  "Piranha Grande",
  "Piranha Zen",
  "Prestigio MultiPhone 3350 DUO",
  "Prestigio MultiPhone 3400 DUO",
  "Prestigio MultiPhone 5044 DUO",
  "Prestigio MultiPhone 5300 DUO",
  "Prestigio MultiPhone 5400 DUO",
  "Prestigio MultiPhone 5450 DUO",
  "Prestigio MultiPhone 5500 DUO",
  "Prestigio MultiPhone 5501 DUO",
  "Prestigio MultiPhone 7600 DUO",
  "Samsung Galaxy A3",
  "Samsung Galaxy A5",
  "Samsung Galaxy A7",
  "Samsung Galaxy A8",
  "Samsung Galaxy Ace 2 i8160",
  "Samsung Galaxy Ace 4",
  "Samsung Galaxy Ace 5830",
  "Samsung Galaxy Alpha",
  "Samsung Galaxy Core 2",
  "Samsung Galaxy Core Prime G360",
  "Samsung Galaxy Core i8260",
  "Samsung Galaxy E5",
  "Samsung Galaxy E7",
  "Samsung Galaxy Gio S5660",
  "Samsung Galaxy Grand 2",
  "Samsung Galaxy Grand Neo",
  "Samsung Galaxy Grand i9082",
  "Samsung Galaxy J1",
  "Samsung Galaxy J2",
  "Samsung Galaxy J5",
  "Samsung Galaxy J7",
  "Samsung Galaxy Mega 5.8",
  "Samsung Galaxy Mega 6.3",
  "Samsung Galaxy Nexus",
  "Samsung Galaxy Note",
  "Samsung Galaxy Note 3",
  "Samsung Galaxy Note 3 Neo",
  "Samsung Galaxy Note 4",
  "Samsung Galaxy Note 5",
  "Samsung Galaxy Note 8",
  "Samsung Galaxy Note Edge",
  "Samsung Galaxy Prime",
  "Samsung Galaxy Prime G530",
  "Samsung Galaxy S Duo S7562",
  "Samsung Galaxy S2 i9100",
  "Samsung Galaxy S3 Mini i8200",
  "Samsung Galaxy S4 Zoom",
  "Samsung Galaxy S5",
  "Samsung Galaxy S5 - Galaxy Note 3",
  "Samsung Galaxy S5 Mini",
  "Samsung Galaxy S6",
  "Samsung Galaxy S6 Edge",
  "Samsung Galaxy S6 Edge Plus",
  "Samsung Galaxy S7",
  "Samsung Galaxy S7 Edge",
  "Samsung Galaxy Trend Plus S7580",
  "Samsung Galaxy Trend S7560",
  "Samsung Galaxy W i8150",
  "Samsung Galaxy Win i8550",
  "Samsung Galaxy Win i8552",
  "Samsung Galaxy Y",
  "Samsung Galaxy i9070",
  "Samsung Galaxy i9080 Grand Duos",
  "Samsung N7100",
  "Samsung S4 Active i9225",
  "Samsung S5233",
  "Samsung S5610",
  "Samsung S7390 Galaxy Trend Lite",
  "Samsung S7562 Galaxy Duo",
  "Samsung S8530",
  "Samsung Z1",
  "Samsung i8190 S3 Mini",
  "Samsung i8552",
  "Samsung i9001",
  "Samsung i9190 S4 Mini",
  "Samsung i9300 S3",
  "Samsung i9500 S4",
  "Sony Ericsson Arc S",
  "Sony Ericsson Xperia Arc S",
  "Sony Ericsson Xperia Neo / Neo V",
  "Sony Ericsson Xperia Ray",
  "Sony Xperia C3",
  "Sony Xperia C4",
  "Sony Xperia E",
  "Sony Xperia E1",
  "Sony Xperia E3",
  "Sony Xperia E8",
  "Sony Xperia Go",
  "Sony Xperia L",
  "Sony Xperia M",
  "Sony Xperia M2",
  "Sony Xperia M4 Aqua",
  "Sony Xperia P",
  "Sony Xperia S",
  "Sony Xperia SP",
  "Sony Xperia Sola",
  "Sony Xperia T2 Ultra",
  "Sony Xperia T3",
  "Sony Xperia Tipo",
  "Sony Xperia U",
  "Sony Xperia Z",
  "Sony Xperia Z Ultra",
  "Sony Xperia Z1",
  "Sony Xperia Z1 Compact",
  "Sony Xperia Z2",
  "Sony Xperia Z3",
  "Sony Xperia Z3 Compact",
  "Sony Xperia Z3 Mini",
  "Sony Xperia Z3 Plus",
  "Sony Xperia İon",
  "Turkcell T 50",
  "Turkcell T40",
  "Turkcell T60",
  "Universal",
  "Vestel Venüs 5.0V",
  "Vestel Venüs 5.0X",
  "Vestel Venüs 5.5V",
  "Vestel Venüs 5.5X",
  "Victor U2",
  "Vodafone Smart 6",
  "Xiaomi MI 4",
  "ZTE Grand X",
  "i9100",
  "iPhone 11",
  "iPhone 12 Pro",
  "iPhone 3GS",
  "iPhone 3g",
  "iPhone 4/4s",
  "iPhone 5",
  "iPhone 5/5s",
  "iPhone 5C",
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 6S",
  "iPhone 6S Plus",
  "iPhone 7",
  "iPhone 8 Plus",
] as const;

/**
 * @CategoryName Telefon > Cep Telefonu Aksesuarları > Kılıflar
 * @Field Malzeme Türü
 * @Optional
 */
export const PhoneCase_CaseMaterials = [
  "Silikon",
  "Ahşap",
  "Aynalı",
  "Aynalı Desenli - Cam",
  "Cam",
  "Cam - Silikon",
  "Deri",
  "Gerçek Deri",
  "Mika",
  "Sert Mika",
  "Plastik",
  "Sert Plastik",
  "Sert Plastik Kapak",
  "Sert Silikon",
  "Şeffaf",
  // ----
  "0.3mm Silikon",
  "Air Slim Silikon",
  "Altın",
  "Alüminyum",
  "Beyaz - Gold",
  "Cam Tozu",
  "Eva",
  "Flex",
  "Gümüş",
  "Kapaklı Kılıf",
  "Karbonfiber",
  "Kaucuk",
  "Kauçuk",
  "Keçe",
  "Koyu Pembe - Gold",
  "Kumaş",
  "Kılıf",
  "Likit",
  "Metal",
  "Mıknatıs",
  "Nano Cam",
  "Neopren",
  "Nikel",
  "Nubuk",
  "Oleofobik Nano Kaplama",
  "PU Deri",
  "PVC",
  "Pencereli Kılıflar",
  "Polikarbon",
  "Polikarbonat",
  "Polimer",
  "Poliüretan",
  "Polycarbon",
  "Premium Metalik Malzeme",
  "Recycled",
  "Rubber",
  "Safir Silikon",
  "Sierra Mavisi",
  "Suni Deri",
  "Süet",
  "TPU",
  "Tempered Cam",
  "Termoplastik Poliüretan",
  "Thermoplastic",
  EMPTY_OPTION,
] as const;

/**
 * @CategoryName Telefon > Cep Telefonu Aksesuarları > Kılıflar
 * @Field Kılıf Tipi
 * @Optional
 */
export const PhoneCase_CaseTypes = [
  "Arka Kapak",
  "Arka Kılıf",
  "Askılı Kılıf",
  "Ekran Koruyucu",
  "Ara Kapak",
  "Kapaklı Kılıf",
  "Kese",
  "Kol Bandı",
  "Sticker",
  "Çerçeve",
  "Aksesuar",
  EMPTY_OPTION,
] as const;
