import { EMPTY_OPTION } from "../../../lib/variables";

/**
 * @CategoryName Telefon > Cep Telefonu Aksesuarları > Araç İçi Telefon Tutucular > Araç İçi Telefon Tutacakları
 * @Field Renk
 * @Optional
 */
export const InCarPhoneHolder_Colors = [
  "AirVent",
  "Ahşap Rengi",
  "AirVent Wireless",
  "Akça",
  "Altuni",
  "Altın",
  "Altın - Siyah",
  "Asker Yeşili",
  "Açık Gri",
  "Açık Kahverengi",
  "Açık Mavi",
  "Açık Pembe",
  "Bakır",
  "Bebek Mavisi",
  "Bej",
  "Beyaz",
  "Beyaz - Beyaz",
  "Beyaz - Gri",
  "Beyaz Şeffaf",
  "Bordo",
  "Bronz",
  "Buz Mavi",
  "Ceviz",
  "Cherry Blossom",
  "Cornflower Papaya",
  "Cup Holder",
  "Dashboard",
  "Dashboard Wireless",
  "Desenli",
  "Fıstık Yeşili",
  "Gold",
  "Gri",
  "Gümüş",
  "Gümüş - Gri",
  "Kahve",
  "Kahverengi",
  "Khaki",
  "Koyu Gri",
  "Koyu Mavi",
  "Koyu Siyah",
  "Koyu Yeşil",
  "Krem",
  "Kömür Rengi",
  "Kırmızı",
  "Kırmızı - Beyaz",
  "Kırmızı - Kırmızı",
  "Kırmızı - Siyah",
  "Lavender",
  "Lila",
  "Mat Siyah",
  "Mavi",
  "Mavi Desenli",
  "Metalik Gri",
  "Mint Yeşili",
  "Mor",
  "Pastel Sarı",
  "Pembe",
  "Pembe - Altın",
  "Pembe - Gümüş",
  "Renkli",
  "Rose",
  "Rose - Gold",
  "Rose Gold",
  "Sarı",
  "Sarı - Beyaz",
  "Silver",
  "Siyah",
  "Siyah - Beyaz",
  "Siyah - Gri",
  "Siyah - Mavi",
  "Siyah - Siyah",
  "Siyah - Yeşil",
  "Su Yeşili",
  "Titanium",
  "Turuncu",
  "Turuncu - Siyah",
  "Yeşil",
  "Şeffaf",
  EMPTY_OPTION,
] as const;

/**
 * @CategoryName Telefon > Cep Telefonu Aksesuarları > Araç İçi Telefon Tutucular > Araç İçi Telefon Tutacakları
 * @Field Türü
 */
export const InCarPhoneHolder_Type = [
  "Dikiz Aynası",
  "Direksiyon",
  "Havalandırma",
  "Torpido Üstü",
  "Vantuzlu",
] as const;
