import { EMPTY_OPTION } from "../../../lib/variables";

/**
 * @CategoryName Telefon > Cep Telefonu Aksesuarları > Bluetooth Kulaklık Aksesuarları
 * @Field Renk
 * @Optional
 */
export const HeadphoneCase_Colors = [
  "Siyah",
  "Beyaz",
  "Pembe",
  "Mor",
  "Mavi",
  "Gold",
  "Gümüş",
  // ---
  "Akçaağaç",
  "Altın",
  "Altın - Beyaz",
  "Altın - Gümüş",
  "Altın - Kahverengi",
  "Altın - Siyah",
  "Altın Kahve",
  "Antrasit",
  "Asker Yeşili",
  "Açık Gri",
  "Açık Kahverengi",
  "Açık Kırmızı",
  "Açık Mavi",
  "Açık Mavi - Altın",
  "Açık Mavi - Gümüş",
  "Açık Mavi - Mavi",
  "Açık Mor",
  "Açık Pembe",
  "Açık Sarı",
  "Açık Siyah",
  "Açık Turuncu",
  "Açık Yeşil",
  "Açık Yeşil - Mavi",
  "Açık Yeşil - Sarı",
  "Açık Yeşil - Yeşil",
  "Bebek Mavi",
  "Bebek Mavisi",
  "Bej",
  "Bej - Beyaz",
  "Bej - Beyaz - Açık Mavi - Yeşil",
  "Bej - Koyu Yeşil",
  "Beyaz - Altın",
  "Beyaz - Bej - Yeşil - Koyu Yeşil",
  "Beyaz - Gri",
  "Beyaz - Gri - Mavi",
  "Beyaz - Gümüş",
  "Beyaz - Kırmızı",
  "Beyaz - Kırmızı - Açık Mavi - Mavi",
  "Beyaz - Kırmızı - Mavi",
  "Beyaz - Mavi",
  "Beyaz - Sarı",
  "Beyaz - Sarı - Açık Yeşil - Mavi",
  "Beyaz - Sarı - Pembe - Yeşil",
  "Beyaz - Siyah",
  "Beyaz - Yeşil",
  "Black",
  "Bordo",
  "Bordo - Lacivert",
  "Bronz",
  "Buzlu Şeffaf",
  "Ceviz Rengi",
  "Crazy Kahve",
  "Crazy Taba",
  "Dark Silver",
  "Deniz Mavisi",
  "Eflatun",
  "Elma Yeşili",
  "Floresan Yeşil",
  "Fuşya",
  "Füme",
  "Fıstık Yeşili",
  "Gece Mavisi",
  "Gece Yarısı Mavisi",
  "Gece Yeşil",
  "Gri",
  "Gri - Altın",
  "Gri - Beyaz",
  "Gri - Gümüş",
  "Gri - Kırmızı",
  "Gri - Mavi",
  "Gri - Mor",
  "Gri - Pembe",
  "Gri - Sarı",
  "Gri - Siyah",
  "Gri - Yeşil",
  "Gri - Yeşil - Pembe",
  "Gri Mavi",
  "Gri Siyah",
  "Gri Yeşil",
  "Gök Mavisi",
  "Gökkuşağı",
  "Gökyüzü Mavisi",
  "Göl Mavisi",
  "Gül Kırmızı",
  "Gülkurusu",
  "Gümüş - Gri",
  "Gümüş - Kırmızı",
  "Gümüş - Mor",
  "Gümüş - Pembe",
  "Gümüş - Sarı",
  "Gümüş - Siyah",
  "Haki",
  "Haki Yeşili",
  "Hardal",
  "Ice Blue",
  "Kahve",
  "Kahverengi",
  "Kahverengi - Beyaz",
  "Kahverengi - Siyah",
  "Kar Mavisi",
  "Karmina",
  "Kavuniçi",
  "Kavuniçi Rengi",
  "Kayısı Rengi",
  "Kiraz Ağacı Rengi",
  "Kiraz Kırmızı",
  "Kiraz Çiçeği Pembe",
  "Koyu Bej",
  "Koyu Gri",
  "Koyu Kahverengi",
  "Koyu Kırmızı",
  "Koyu Kırmızı - Kırmızı - Sarı - Beyaz",
  "Koyu Mavi",
  "Koyu Mor",
  "Koyu Pembe",
  "Koyu Pembe - Mavi",
  "Koyu Sarı",
  "Koyu Turkuaz",
  "Koyu Turuncu",
  "Koyu Yeşil",
  "Kraliyet Mavisi",
  "Krem",
  "Kum Pembesi",
  "Kumul Rengi",
  "Kırmızı",
  "Kırmızı - Altın",
  "Kırmızı - Beyaz",
  "Kırmızı - Gümüş",
  "Kırmızı - Mavi",
  "Kırmızı - Pembe",
  "Kırmızı - Sarı",
  "Kırmızı - Siyah",
  "Lacivert",
  "Lacivert - Gri",
  "Lacivert - Gri - Yeşil",
  "Lacivert - Kırmızı",
  "Lacivert - Pembe",
  "Lacivert - Siyah",
  "Lavanta Grisi",
  "Lavanta Mor",
  "Leopar",
  "Leopar - Beyaz",
  "Leopar - Kahverengi",
  "Leopar - Pembe",
  "Leopar - Yeşil",
  "Lila",
  "Lila - Pembe",
  "Limon Sarısı",
  "Mat Beyaz",
  "Mat Kırmızı",
  "Mat Siyah",
  "Matcha Yeşil",
  "Matcha Yeşili",
  "Matcha Yeşili - Altın",
  "Matcha Yeşili - Gümüş",
  "Matcha Yeşili - Kırmızı",
  "Matcha Yeşili - Yeşil",
  "Mavi - Altın",
  "Mavi - Açık Mavi",
  "Mavi - Bej",
  "Mavi - Bej - Pembe - Sarı",
  "Mavi - Beyaz",
  "Mavi - Beyaz - Sarı",
  "Mavi - Gri",
  "Mavi - Gümüş",
  "Mavi - Kahverengi",
  "Mavi - Kırmızı",
  "Mavi - Mor",
  "Mavi - Pembe",
  "Mavi - Sarı",
  "Mavi - Siyah",
  "Mavi - Turuncu",
  "Mavi - Yeşil",
  "Mercan",
  "Mercan - Turuncu",
  "Mint",
  "Mint Yeşili",
  "Mor - Altın",
  "Mor - Gümüş",
  "Mor - Kırmızı",
  "Mor - Mermer",
  "Mor - Pembe",
  "Mor - Siyah",
  "Mor - Yeşil",
  "Mürdüm",
  "Nane Yeşili",
  "Neon Sarı",
  "Neon Yeşil",
  "Ordu Yeşili",
  "Parlak Siyah",
  "Parlak Yeşil",
  "Parlak Şeffaf",
  "Parlament Mavisi",
  "Pembe - Altın",
  "Pembe - Açık Kırmızı - Turuncu - Kırmızı",
  "Pembe - Beyaz",
  "Pembe - Beyaz - Açık Yeşil - Mavi",
  "Pembe - Gri",
  "Pembe - Gri - Yeşil",
  "Pembe - Gümüş",
  "Pembe - Koyu Pembe",
  "Pembe - Kırmızı",
  "Pembe - Mavi",
  "Pembe - Mor",
  "Pembe - Sarı",
  "Pembe - Yeşil",
  "Petrol Mavi",
  "Pudra",
  "Renkli",
  "Rose",
  "Rose Gold",
  "Safir Mavi",
  "Safir Mavisi",
  "Saks",
  "Saks Mavi",
  "Sap Yeşili",
  "Sarı",
  "Sarı - Altın",
  "Sarı - Beyaz",
  "Sarı - Gümüş",
  "Sarı - Lacivert",
  "Sarı - Mavi",
  "Sarı - Mor",
  "Sarı - Siyah",
  "Sarı - Yeşil",
  "Siyah - Altın",
  "Siyah - Açık Yeşil",
  "Siyah - Beyaz",
  "Siyah - Gri",
  "Siyah - Gümüş",
  "Siyah - Kahve",
  "Siyah - Kahverengi",
  "Siyah - Kırmızı",
  "Siyah - Mavi",
  "Siyah - Mor",
  "Siyah - Ordu Yeşili",
  "Siyah - Pembe",
  "Siyah - Renkli",
  "Siyah - Safir Mavi",
  "Siyah - Sarı",
  "Siyah - Siyah",
  "Siyah - Turuncu",
  "Siyah - Yeşil",
  "Siyah Gri",
  "Soft Kırmızı",
  "Soft Mavi",
  "Soft Pembe",
  "Somon",
  "Su Yeşili",
  "Süt Beyazı",
  "Taba",
  "Taş",
  "Titanyum Gri",
  "Turkuaz",
  "Turuncu",
  "Turuncu - Koyu Yeşil",
  "Turuncu - Siyah",
  "Turuncu - Yeşil",
  "Yeşil",
  "Yeşil - Altın",
  "Yeşil - Beyaz",
  "Yeşil - Gümüş",
  "Yeşil - Koyu Yeşil",
  "Yeşil - Kırmızı",
  "Yeşil - Pembe",
  "Yeşil - Sarı",
  "Yeşil - Siyah",
  "Yeşil - Turuncu",
  "Zeytin Yeşili",
  "Zümrüt Yeşili",
  "Çam Ormanı Yeşil",
  "Çam Yeşili",
  "Çam İğnesi Yeşili",
  "Çim Yeşili",
  "Çimen Gri",
  "Çimen Yeşili",
  "Şampanya - Altın",
  "Şarap Kırmızı",
  "Şarap Kırmızısı",
  "Şeffaf",
  "Şeffaf - Altın",
  "Şeffaf - Gümüş",
  "Şeffaf - Kırmızı",
  "Şeffaf - Siyah",
  "Şeffaf - Yeşil",
  "Şeffaf Altın - Altın",
  "Şeffaf Altın - Gümüş",
  "Şeffaf Altın - Siyah",
  "Şeffaf Beyaz",
  "Şeffaf Kırmızı - Altın",
  "Şeffaf Kırmızı - Gümüş",
  "Şeffaf Kırmızı - Kırmızı",
  "Şeffaf Kırmızı - Siyah",
  "Şeffaf Mavi",
  "Şeffaf Pembe",
  "Şeffaf Sarı",
  "Şeffaf Siyah",
  "Şeffaf Siyah - Altın",
  "Şeffaf Siyah - Gümüş",
  "Şeffaf Siyah - Kırmızı",
  "Şeffaf Siyah - Siyah",
  "Şeffaf Yeşil - Altın",
  "Şeffaf Yeşil - Gümüş",
  "Şeffaf Yeşil - Yeşil",
  EMPTY_OPTION,
] as const;

/**
 * @CategoryName Telefon > Cep Telefonu Aksesuarları > Bluetooth Kulaklık Aksesuarları
 * @Field Kulaklık Aksesuarı Türü
 */
export const HeadphoneCase_HeadphoneAccessoryType = ["Kılıf", "Askı"] as const;

/**
 * @Selfmade
 */
export const HeadphoneCase_CustomHeadphonesList = [
  "Airpods 1. Nesil",
  "Airpods 2. Nesil",
  "Airpods 3. Nesil",
  "Airpods Pro",
  "Airpods 2. Nesil Pro",
  "Belirtilmemiş",
  "Cx True Wireless",
  "Enco Buds",
  "Freebuds 4i",
  "Galaxy Buds2",
  "Galaxy Buds2 Pro",
  "Lp1 Livepods",
  "Momentum True Wireless 3",
  "Redmi Buds 3",
  "Tune 225",
  "Tune 230",
  "W32 Enco Air",
  "Wave 100",
  "Wave 300",
  "WF-1000XM3",
  "Wf-1000xm4",
  "Wf-c500",
  "WI-C310",
] as const;
